###
### detected_entity SENSOR
###

## human readable status
- platform: template
  sensors:
    motion_detected_entity_status:
      friendly_name: Found
      entity_id:
        - sensor.motion_detected_entity_when
        - sensor.motion_detected_entity_ago
        - sensor.motion_detected_entity_count
      value_template: >-
        {% set device = states('sensor.motion_detected_entity_device') %}
        {% set camera = states('sensor.motion_detected_entity_camera') %}
        {% set count = states('sensor.motion_detected_entity_count')|int %}
        {% set ago = states('sensor.motion_detected_entity_ago')|int %}
        {% set when = states('sensor.motion_detected_entity_when') %}
        {% set what = states('sensor.motion_detect_entity') %}
        {{ count }} {{ what }};
        from {{ device -}}/{{- camera }};
        at {{ when -}}; {{ ago }} seconds ago

## entity_count
- platform: template
  sensors:
    motion_detected_entity_count:
      friendly_name: detected entity count
      entity_id:
        - counter.motion_detected_entity_counter
        - sensor.motion_detected_entity_ago
      unit_of_measurement: entities
      value_template: >-
        {{ states('sensor.motion_detected_count_entity')|int }}

## counter
- platform: template
  sensors:
    motion_detected_entity_counter:
      friendly_name: Found
      entity_id:
        - counter.motion_detected_entity_counter
      unit_of_measurement: count
      value_template: >
        {{ states('counter.motion_detected_entity_counter')|int }}

## device
- platform: template
  sensors:
    # device
    motion_detected_entity_device:
      friendly_name: Detected entity device
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {{ states('sensor.motion_detected_device') }}

## camera
- platform: template
  sensors:
    motion_detected_entity_camera:
      friendly_name: Detected entity camera
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {{ states('sensor.motion_detected_camera') }}

## date
- platform: template
  sensors:
    motion_detected_entity_date:
      entity_id:
        - counter.motion_detected_entity_counter
      unit_of_measurement: seconds
      value_template: >-
        {{ states('sensor.motion_detected_date')|int }}

## when - human readable
- platform: template
  sensors:
    motion_detected_entity_when:
      friendly_name: Detected entity at
      entity_id:
        - sensor.motion_detected_entity_date
      value_template: >-
        {% set s = states('sensor.motion_detected_entity_date')|int %}
        {% if s > 0 %}
          {% set n = utcnow().timestamp() %}
          {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}; {{ (n|int-s)|int }} lag
        {% else %}never{% endif %}

## ago
- platform: template
  sensors:
    motion_detected_entity_ago:
      friendly_name: Found ago
      entity_id:
        - sensor.motion_detected_entity_date
        - sensor.time
      unit_of_measurement: seconds
      value_template: >
        {% set s = states('sensor.motion_detected_entity_date')|int %}
        {% if s > 0 %}
          {% set s = utcnow().timestamp()|int - s %}
          {% if s < 86400 %}{{ s }}{%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

## detected_entity_list
- platform: template
  sensors:
    motion_detected_entity_list:
      friendly_name: Detected entity list
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {{ states('sensor.motion_detected_list') }}

## percent
- platform: template
  sensors:
    motion_detected_entity_percent:
      friendly_name: Detected entity percent
      entity_id:
        - counter.motion_detected_entity_counter
        - counter.motion_annotated_counter
      unit_of_measurement: '%'
      value_template: >-
        {% if states.counter.motion_detected_entity_counter|lower != 'none'
              and states.counter.motion_detected_entity_counter.state != 'null'
              and states.counter.motion_annotated_counter|lower != 'none'
              and states.counter.motion_annotated_counter.state|int > 0 %}
          {{ ( states.counter.motion_detected_entity_counter.state|int / states.counter.motion_annotated_counter.state|int ) * 100.0 }}
        {%- else -%}null{%- endif -%}

## snapshot
- platform: template
  sensors:
    motion_detected_entity_snapshot:
      friendly_name: Detected snapshot
      entity_id:
        - sensor.motion_detected_entity_camera
      value_template: >-
        {% set c = states('sensor.motion_detected_entity_camera') %}
        {% if c is not none and c|lower != 'unknown' and c|length > 0 %}
          {% set bu = states('sensor.motion_base_url') %}
          {% if bu != 'unknown' %}
            {% set p = bu + '/local/images/motion_detected_entity-' + c + '.jpg' %}
          {% else %}
            {% set p = states('sensor.motion_testsignal_picture') %}
          {% endif %}
        {% else %}
          {% set p = states('sensor.motion_noisesignal_picture') %}
        {% endif %}
        {% if p is defined and p|lower != 'none' and p != 'unknown' and p != 'null' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

## picture
- platform: template
  sensors:
    motion_detected_entity_picture:
      friendly_name: Any detected entity picture
      entity_id:
        #- sensor.motion_detected_picture
        - counter.motion_detected_entity_counter
      value_template: >-
        {% if is_state('binary_sensor.motion_detected_entity','on') %}
          {% set p = states('sensor.motion_detected_picture') %}
        {% else %}
          {% set p = states('sensor.motion_detected_entity_picture') %}
        {% endif %}
        {% if p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

###
# statistics
###

## ago
- platform: template
  sensors:
    motion_detected_entity_ago_mean:
      friendly_name: Found ago avg
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_min_value:
      friendly_name: Found ago min
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_max_value:
      friendly_name: Found ago max
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_stdev:
      friendly_name: Found ago stdev
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_change:
      friendly_name: Found ago change
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_stdev_change:
      friendly_name: Found ago stdev change
      entity_id:
        - sensor.motion_detected_entity_ago_stdev_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_entity_ago_stdev_statistics|lower != 'none' %}
          {{ states.sensor.motion_detected_entity_ago_stdev_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## counter
- platform: template
  sensors:
    motion_detected_entity_counter_mean:
      friendly_name: Found avg
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_min_value:
      friendly_name: Found min
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_max_value:
      friendly_name: Found max
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_stdev:
      friendly_name: Found stdev
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_change:
      friendly_name: Found change
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## percent
- platform: template
  sensors:
    motion_detected_entity_percent_mean:
      friendly_name: Detected entity percent avg
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_min_value:
      friendly_name: Detected entity percent min
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_max_value:
      friendly_name: Detected entity percent max
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_stdev:
      friendly_name: Detected entity percent stdev
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_change:
      friendly_name: Detected entity percent change
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## count
- platform: template
  sensors:
    motion_detected_entity_count_mean:
      friendly_name: Detected entity count avg
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_min_value:
      friendly_name: Detected entity count min
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_max_value:
      friendly_name: Detected entity count max
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_stdev:
      friendly_name: Detected entity count stdev
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_change:
      friendly_name: Detected entity count change
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

# counter
- platform: statistics
  name: motion_detected_entity_counter_statistics
  entity_id: sensor.motion_detected_entity_counter
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_entity_counter_stdev_statistics
  entity_id: sensor.motion_detected_entity_counter_stdev
  sampling_size: 100
  max_age:
    hours: 72

# count
- platform: statistics
  name: motion_detected_entity_count_statistics
  entity_id: sensor.motion_detected_entity_count
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_entity_count_stdev_statistics
  entity_id: sensor.motion_detected_entity_count_stdev
  sampling_size: 100
  max_age:
    hours: 72

# ago
- platform: statistics
  name: motion_detected_entity_ago_statistics
  entity_id: sensor.motion_detected_entity_ago
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_entity_ago_stdev_statistics
  entity_id: sensor.motion_detected_entity_ago_stdev
  sampling_size: 100
  max_age:
    hours: 72

# percent
- platform: statistics
  name: motion_detected_entity_percent_statistics
  entity_id: sensor.motion_detected_entity_percent
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_entity_percent_stdev_statistics
  entity_id: sensor.motion_detected_entity_percent_stdev
  sampling_size: 100
  max_age:
    hours: 72

###
### variable detection; produce array of booleans
###

- platform: template
  sensors:
    motion_detected_person:
      entity_id:
        - counter.motion_detected_counter
        - sensor.motion_detected_ago
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_person','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle:
      entity_id:
        - counter.motion_detected_counter
        - sensor.motion_detected_ago
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_vehicle','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal:
      entity_id:
        - counter.motion_detected_counter
        - sensor.motion_detected_ago
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_animal','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}
