###
### detected SENSOR
###

## human readable status
- platform: template
  sensors:
    motion_detected_status:
      friendly_name: Seen
      entity_id:
        - sensor.motion_detected_when
        - sensor.motion_detected_camera
        - sensor.motion_detected_device
        - sensor.motion_detected_count
        - sensor.motion_detected_list
        - sensor.motion_detected_ago
      value_template: >-
        {% set device = states('sensor.motion_detected_device')  %}
        {% set camera = states('sensor.motion_detected_camera')  %}
        {% set count = states('sensor.motion_detected_count')|int %}
        {% set ago = states('sensor.motion_detected_ago')|int %}
        {% set when = states('sensor.motion_detected_when') %}
        {% set what = states('sensor.motion_detected_list') %}
        {{ count }} entities: {{ what }}; from {{ device -}}/{{- camera }} at {{ when -}}; {{ ago }} seconds ago

## count
- platform: template
  sensors:
    motion_detected_count:
      friendly_name: Detected count
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: entities
      value_template: >-
        {{ states('sensor.motion_annotated_count')|int }}

## entity count
- platform: template
  sensors:
    motion_detected_count_entity:
      friendly_name: Detected count entity
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: entities
      value_template: >-
        {{ states('sensor.motion_annotated_count_entity')|int }}

## counter
- platform: template
  sensors:
    motion_detected_counter:
      friendly_name: Seen
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: count
      value_template: >
        {{ states('counter.motion_detected_counter')|int }}

## device
- platform: template
  sensors:
    # device
    motion_detected_device:
      friendly_name: Detected device
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
        {{ states('sensor.motion_annotated_device') }}

## camera
- platform: template
  sensors:
    motion_detected_camera:
      friendly_name: Detected camera
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
        {{ states('sensor.motion_annotated_camera') }}

## date
- platform: template
  sensors:
    motion_detected_date:
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: seconds
      value_template: >-
        {{ states('sensor.motion_annotated_date')|int }}

## when - human readable
- platform: template
  sensors:
    motion_detected_when:
      friendly_name: Detected at
      entity_id:
        - sensor.motion_detected_date
      value_template: >-
        {% set s = states('sensor.motion_detected_date')|int %}
        {% if s > 0 %}
          {% set n = utcnow().timestamp() %}
          {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}; {{ (n|int-s)|int }} lag
        {% else %}never{% endif %}

## ago
- platform: template
  sensors:
    motion_detected_ago:
      friendly_name: Seen ago
      entity_id:
        - sensor.motion_detected_date
        - sensor.time
      unit_of_measurement: seconds
      value_template: >
        {% set s = states('sensor.motion_detected_date')|int %}
        {% if s > 0 %}
          {% set s = utcnow().timestamp()|int - s %}
          {% if s < 86400 %}{{ s }}{%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

## detected
- platform: template
  sensors:
    motion_detected_array:
      friendly_name: Detected array
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
        {{ states('sensor.motion_annotated_detected') }}

## detected_list
- platform: template
  sensors:
    motion_detected_list:
      friendly_name: Detected list
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
        {{ states('sensor.motion_annotated_list') }}

## percent
- platform: template
  sensors:
    motion_detected_percent:
      friendly_name: Detected percent
      entity_id:
        - counter.motion_detected_counter
        - counter.motion_annotated_counter
      unit_of_measurement: '%'
      value_template: >-
        {% if states.counter.motion_detected_counter|lower != 'none'
              and states.counter.motion_detected_counter.state != 'null'
              and states.counter.motion_annotated_counter|lower != 'none'
              and states.counter.motion_annotated_counter.state|int > 0 %}
          {{ ( states.counter.motion_detected_counter.state|int / states.counter.motion_annotated_counter.state|int ) * 100.0 }}
        {%- else -%}null{%- endif -%}

## snapshot
- platform: template
  sensors:
    motion_detected_snapshot:
      friendly_name: Detected snapshot
      entity_id:
        - sensor.motion_detected_camera
      value_template: >-
        {% set c = states('sensor.motion_detected_camera') %}
        {% if c is not none and c|lower != 'unknown' and c|length > 0 %}
          {% set bu = states('sensor.motion_base_url') %}
          {% if bu != 'unknown' %}
            {% set p = bu + '/local/images/motion_detected-' + c + '.jpg' %}
          {% else %}
            {% set p = states('sensor.motion_testsignal_picture') %}
          {% endif %}
        {% else %}
          {% set p = states('sensor.motion_noisesignal_picture') %}
        {% endif %}
        {% if p is defined and p|lower != 'none' and p != 'unknown' and p != 'null' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}
        
## picture
- platform: template
  sensors:
    motion_detected_picture:
      friendly_name: Any detected picture
      entity_id:
        #- sensor.motion_annotated_picture
        - counter.motion_detected_counter
      value_template: >-
        {% if is_state('binary_sensor.motion_detected','on') %}
          {% set p = states('sensor.motion_annotated_picture') %}
        {% else %}
          {% set p = states('sensor.motion_detected_picture') %}
        {% endif %}
        {% if p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
           {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

###
# statistics
###

## ago
- platform: template
  sensors:
    motion_detected_ago_mean:
      friendly_name: Seen ago avg
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_ago_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_min_value:
      friendly_name: Seen ago min
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_max_value:
      friendly_name: Seen ago max
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_stdev:
      friendly_name: Seen ago stdev
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_change:
      friendly_name: Seen ago change
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_stdev_change:
      friendly_name: Seen ago stdev change
      entity_id:
        - sensor.motion_detected_ago_stdev_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_ago_stdev_statistics|lower != 'none' %}
          {{ states.sensor.motion_detected_ago_stdev_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## counter
- platform: template
  sensors:
    motion_detected_counter_mean:
      friendly_name: Seen avg
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_min_value:
      friendly_name: Seen min
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_max_value:
      friendly_name: Seen max
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_stdev:
      friendly_name: Seen stdev
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_change:
      friendly_name: Seen change
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## percent
- platform: template
  sensors:
    motion_detected_percent_mean:
      friendly_name: Detected percent avg
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_min_value:
      friendly_name: Detected percent min
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_max_value:
      friendly_name: Detected percent max
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_stdev:
      friendly_name: Detected percent stdev
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_change:
      friendly_name: Detected percent change
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## count
- platform: template
  sensors:
    motion_detected_count_mean:
      friendly_name: Detected count avg
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_count_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_min_value:
      friendly_name: Detected count min
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_count_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_max_value:
      friendly_name: Detected count max
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_count_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_stdev:
      friendly_name: Detected count stdev
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_change:
      friendly_name: Detected count change
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_count_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

# counter
- platform: statistics
  name: motion_detected_counter_statistics
  entity_id: sensor.motion_detected_counter
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_counter_stdev_statistics
  entity_id: sensor.motion_detected_counter_stdev
  sampling_size: 100
  max_age:
    hours: 72

# count
- platform: statistics
  name: motion_detected_count_statistics
  entity_id: sensor.motion_detected_count
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_count_stdev_statistics
  entity_id: sensor.motion_detected_count_stdev
  sampling_size: 100
  max_age:
    hours: 72

# ago
- platform: statistics
  name: motion_detected_ago_statistics
  entity_id: sensor.motion_detected_ago
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_ago_stdev_statistics
  entity_id: sensor.motion_detected_ago_stdev
  sampling_size: 100
  max_age:
    hours: 72

# percent
- platform: statistics
  name: motion_detected_percent_statistics
  entity_id: sensor.motion_detected_percent
  sampling_size: 100
  max_age:
    hours: 72
- platform: statistics
  name: motion_detected_percent_stdev_statistics
  entity_id: sensor.motion_detected_percent_stdev
  sampling_size: 100
  max_age:
    hours: 72
