- platform: template
  sensors:
    motion_base_url:
      entity_id:
        - sensor.hostip
        - input_number.homeassistant_port
        - input_select.homeassistant_url
      value_template: >-
        {% if states.input_select.homeassistant_url.state|string == 'local' %}
          {{ 'http://' + states.sensor.host_lan_ip.attributes.ipv4 + ':' + states.input_number.homeassistant_port.state|int|string }}
        {% elif states.input_select.homeassistant_url.state|string == 'remote' %}
          {{ states.sensor.homeassistant_url.state }}
        {% else %}null{% endif %}
