##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_annotated_image
  still_image_url: >-
    {% if states.sensor.motion_event_annotated is defined %}
      {% set camera = states.sensor.motion_event_annotated.attributes.event.camera %}
      {% if camera is defined and camera|length %}
        {% set device = 'camera.motion_annotated_' + camera %}
        {{ state_attr(device, 'entity_picture') }}
      {% else %}null{% endif %} 
    {% else %}null{% endif %}
- platform: generic
  name: motion_detected_image
  still_image_url: >-
    {% if states.sensor.motion_event_annotated is defined %}
      {% set camera = states.sensor.motion_event_annotated.attributes.event.camera %}
      {% if camera is defined and camera|length %}
        {% set device = 'camera.motion_annotated_' + camera %}
        {{ state_attr(device, 'entity_picture') }}
      {% else %}null{% endif %} 
    {% else %}null{% endif %}
- platform: generic
  name: motion_detected_image
  still_image_url: >-
    {% if states.sensor.motion_event_annotated is defined %}
      {% set camera = states.sensor.motion_event_annotated.attributes.event.camera %}
      {% if camera is defined and camera|length %}
        {% set device = 'camera.motion_annotated_' + camera %}
        {{ state_attr(device, 'entity_picture') }}
      {% else %}null{% endif %} 
    {% else %}null{% endif %}
