##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_annotated_image
  still_image_url: >-
    {{ states.sensor.motion_annotated_picture.state }}
- platform: generic
  name: motion_detected_image
  still_image_url: >-
    {{ states.sensor.motion_detected_picture.state }}
- platform: generic
  name: motion_detected_entity_image
  still_image_url: >-
    {{ states.sensor.motion_detected_entity_picture.state }}
