##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_annotated_image
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {{ states.sensor.motion_annotated_picture.state }}
