##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_detected_entity_image
  verify_ssl: false
  #limit_refetch_to_url_change: true
  still_image_url: >-
    {{ states.sensor.motion_detected_entity_picture.state }}
