##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_detected_entity_image
  verify_ssl: false
  #limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states.sensor.motion_detected_entity_picture != none and states.sensor.motion_detected_entity_picture.state != none %}
      {{ states.sensor.motion_detected_entity_picture.state }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
