##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_detected_image
  #limit_refetch_to_url_change: true
  still_image_url: >-
    {{ states.sensor.motion_detected_picture.state }}
