##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_detected_image
  verify_ssl: false
  #limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states.sensor.motion_detected_picture != none and states.sensor.motion_detected_picture.state != 'null' %}
      {% if  states.sensor.motion_detected_picture.state != 'unknown' %}
        {{ states.sensor.motion_detected_picture.state }}
      {% else %}{{ states.sensor.motion_base_url.state + '/local/images/no-signal.jpg' }}{% endif %}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

#    {% if states.sensor.motion_detected_picture != none and states.sensor.motion_detected_picture.state != 'null' %}
#      {{ states.sensor.motion_detected_picture.state }}
#    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/no-signal.jpg' }}{% endif %}
