##
## end CAMERA
##

# per event
- platform: mqtt
  name: motion_event_average
  topic: 'motion/+/+/image-average'
- platform: mqtt
  name: motion_event_blend
  topic: 'motion/+/+/image-blend'
- platform: mqtt
  name: motion_event_animated_mask
  topic: 'motion/+/+/image-animated-mask'
- platform: mqtt
  name: motion_event_composite
  topic: 'motion/+/+/image-composite'
- platform: mqtt
  name: motion_event_animated
  topic: 'motion/+/+/image-animated'
- platform: mqtt
  name: motion_event_end
  topic: 'motion/+/+/image/end'

# per image
- platform: mqtt
  name: motion_image_last
  topic: 'motion/+/+/image'
- platform: mqtt
  name: motion_image_cropped
  topic: 'motion/+/+/image-cropped'

- platform: generic
  name: motion_end_image
  verify_ssl: false
  still_image_url: >-
    {% if states.sensor.motion_end_picture != none and states.sensor.motion_end_picture.state != 'null' %}
      {{ states.sensor.motion_end_picture.state }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

