##
## most recent image (via MQTT)
##
- platform: mqtt
  name: motion_image_current
  topic: 'motion/+/+/image'
- platform: mqtt
  name: motion_image_last
  topic: 'motion/+/+/image/end'
- platform: mqtt
  name: motion_average_last
  topic: 'motion/+/+/image-average'
- platform: mqtt
  name: motion_blend_last
  topic: 'motion/+/+/image-blend'
- platform: mqtt
  name: motion_animated_last_mask
  topic: 'motion/+/+/image-animated-mask'
- platform: mqtt
  name: motion_composite_last
  topic: 'motion/+/+/image-composite'
- platform: mqtt
  name: motion_animated_last
  topic: 'motion/+/+/image-animated'
- platform: mqtt
  name: motion_annotated_last
  topic: 'motion/+/+/image/end/+'
- platform: mqtt
  name: motion_cropped_last
  topic: 'motion/+/+/image-cropped'
