- platform: template
  sensors:
    internet_test_state:
      entity_id:
        - sensor.internet_test
        - sensor.internet_test_ago
      value_template: >
        {{ states.sensor.internet_test_ago.state|int > 30 }}
    internet_slow:
      entity_id:
        - sensor.internet_test_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.internet_receive_mean.state|float) - (states.sensor.internet_test_receive.state|float))
               / (states.sensor.internet_receive_statistics.attributes.standard_deviation|float) 
             > (states.input_number.internet_deviation.state|float)) }}
        {%- else -%}null{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    internet_slow_persistent:
      entity_id:
        - sensor.internet_test_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.internet_receive_mean.state|float) - (states.sensor.internet_test_receive.state|float))
               / (states.sensor.internet_receive_stdev_mean.state|float) 
             > (states.input_number.internet_deviation.state|float)) }}
        {%- else -%}null{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    internet_fast:
      entity_id:
        - sensor.internet_test_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.internet_test_receive.state|float) - (states.sensor.internet_receive_mean.state|float))
               / (states.sensor.internet_receive_statistics.attributes.standard_deviation|float)) 
             > (states.input_number.internet_deviation.state|float) }}
        {%- else -%}null{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    internet_fast_persistent:
      entity_id:
        - sensor.internet_test_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.internet_test_receive.state|float) - (states.sensor.internet_receive_mean.state|float))
               / (states.sensor.internet_receive_stdev_mean.state|float)) 
             > (states.input_number.internet_deviation.state|float) }}
        {%- else -%}null{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
