- platform: template
  sensors:
    motion_state:
      entity_id:
        - sensor.motion_event_end
        - sensor.motion_ago
      value_template: >
        {{ states.sensor.motion_event_end.state }}
    motion_low:
      entity_id:
        - sensor.motion_count
        - sensor.motion_count_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_count_statistics.state|float) - (states.sensor.motion_count.state|float))
               / (states.sensor.motion_count_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_low_persistent:
      entity_id:
        - sensor.motion_count
        - sensor.motion_count_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_count_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.motion_count_statistics.state|float) - (states.sensor.motion_count.state|float))
               / (states.sensor.motion_count_stdev_mean.state|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_high:
      entity_id:
        - sensor.motion_count
        - sensor.motion_count_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_count.state|float) - (states.sensor.motion_count_statistics.state|float))
               / (states.sensor.motion_count_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_high_persistent:
      entity_id:
        - sensor.motion_count
        - sensor.motion_count_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.input_number.motion_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_count.state|float) - (states.sensor.motion_count_statistics.state|float))
               / (states.sensor.motion_count_stdev_mean.state|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
- platform: template
  sensors:
    motion_event_image_state:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_event_image_ago
      value_template: >
        {{ states.sensor.motion_event_image.state }}
    motion_image_low:
      entity_id:
        - sensor.motion_event_image_count
        - sensor.motion_event_image_count_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_event_image_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_event_image_count_statistics.state|float) - (states.sensor.motion_event_image_count.state|float))
               / (states.sensor.motion_event_image_count_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_image_low_persistent:
      entity_id:
        - sensor.motion_event_image_count
        - sensor.motion_event_image_count_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_event_image_count_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.motion_event_image_count_statistics.state|float) - (states.sensor.motion_event_image_count.state|float))
               / (states.sensor.motion_event_image_count_stdev_mean.state|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_image_high:
      entity_id:
        - sensor.motion_event_image_count
        - sensor.motion_event_image_count_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_event_image_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_event_image_count.state|float) - (states.sensor.motion_event_image_count_statistics.state|float))
               / (states.sensor.motion_event_image_count_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_image_high_persistent:
      entity_id:
        - sensor.motion_event_image_count
        - sensor.motion_event_image_count_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.input_number.motion_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_event_image_count.state|float) - (states.sensor.motion_event_image_count_statistics.state|float))
               / (states.sensor.motion_event_image_count_stdev_mean.state|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
        - sensor.motion_detect_entity
      value_template: >-
        {% if states.sensor.motion_event_annotated is defined %}
          {% if states.sensor.motion_event_annotated.attributes.count|int > 0 %}True{% else %}False{% endif %}
        {% else %}False{% endif %}
    motion_detected_entity:
      entity_id:
        - sensor.motion_detected_entity_count
        - sensor.motion_detect_entity
      value_template: >-
        {% if states.sensor.motion_detected_entity_count is defined %}
          {{ states.sensor.motion_detected_entity_count.state > 0 }}
        {% else %}False{% endif %}
