###
### EVENT END
###

- platform: template
  sensors:
    motion_state:
      entity_id:
        - sensor.motion_event_end
        - sensor.motion_ago
      value_template: >
        {{ states.sensor.motion_event_end.state == 'True' }}
    motion_low:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_counter_statistics.state|float) - (states.sensor.motion_counter.state|float))
               / (states.sensor.motion_counter_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_low_persistent:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.motion_counter_statistics.state|float) - (states.sensor.motion_counter.state|float))
               / (states.sensor.motion_counter_stdev_mean.state|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_high:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_counter.state|float) - (states.sensor.motion_counter_statistics.state|float))
               / (states.sensor.motion_counter_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_high_persistent:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.input_number.motion_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_counter.state|float) - (states.sensor.motion_counter_statistics.state|float))
               / (states.sensor.motion_counter_stdev_mean.state|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy

###
### EVENT IMAGE
###

- platform: template
  sensors:
    motion_image_state:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_image_ago
      value_template: >
        {{ states.sensor.motion_event_image.state }}
    motion_image_low:
      entity_id:
        - sensor.motion_image_counter
        - sensor.motion_image_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_image_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_image_counter_statistics.state|float) - (states.sensor.motion_image_counter.state|float))
               / (states.sensor.motion_image_counter_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_image_low_persistent:
      entity_id:
        - sensor.motion_image_counter
        - sensor.motion_image_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_image_counter_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.motion_image_counter_statistics.state|float) - (states.sensor.motion_image_counter.state|float))
               / (states.sensor.motion_image_counter_stdev_mean.state|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_image_high:
      entity_id:
        - sensor.motion_image_counter
        - sensor.motion_image_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_image_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_image_counter.state|float) - (states.sensor.motion_image_counter_statistics.state|float))
               / (states.sensor.motion_image_counter_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_image_high_persistent:
      entity_id:
        - sensor.motion_image_counter
        - sensor.motion_image_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.input_number.motion_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_image_counter.state|float) - (states.sensor.motion_image_counter_statistics.state|float))
               / (states.sensor.motion_image_counter_stdev_mean.state|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy

##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
        - sensor.motion_annotated_ago
      value_template: >
        {{ states.sensor.motion_event_annotated.state }}
    motion_detected:
      entity_id:
        - sensor.motion_annotated_count
      value_template: >-
        {% if states.sensor.motion_annotated_count is defined %}
          {{ states.sensor.motion_annotated_count.state|int > 0 }}
        {% else %}False{% endif %}
    motion_detected_entity:
      entity_id:
        - sensor.motion_detected_entity_count
      value_template: >-
        {% if states.sensor.motion_detected_entity_count is defined %}
          {{ states.sensor.motion_detected_entity_count.state|int > 0 }}
        {% else %}False{% endif %}
