###
### laundry cameras
###
- platform: mjpeg
  mjpeg_url: http://laundry.dcmartin.com/img/video.mjpeg
  still_image_url: http://laundry.dcmartin.com/img/snapshot.cgi
  name: motion_live_laundry
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_image_laundry
  topic: 'motion/+/laundry/image'
- platform: mqtt
  name: motion_average_laundry
  topic: 'motion/+/laundry/image-average'
- platform: mqtt
  name: motion_blend_laundry
  topic: 'motion/+/laundry/image-blend'
- platform: mqtt
  name: motion_animated_mask_laundry
  topic: 'motion/+/laundry/image-animated-mask'
- platform: mqtt
  name: motion_composite_laundry
  topic: 'motion/+/laundry/image-composite'
- platform: mqtt
  name: motion_animated_laundry
  topic: 'motion/+/laundry/image-animated'
- platform: mqtt
  name: motion_annotated_laundry
  topic: 'motion/+/laundry/image/+'
- platform: mqtt
  name: motion_cropped_laundry
  topic: 'motion/+/laundry/image-cropped'
