###
### woodshed cameras
###
- platform: mjpeg
  mjpeg_url: http://woodshed.dcmartin.com/img/video.mjpeg
  still_image_url: http://woodshed.dcmartin.com/img/snapshot.cgi
  name: motion_live_woodshed
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_image_woodshed
  topic: 'motion/+/woodshed/image'
- platform: mqtt
  name: motion_average_woodshed
  topic: 'motion/+/woodshed/image-average'
- platform: mqtt
  name: motion_blend_woodshed
  topic: 'motion/+/woodshed/image-blend'
- platform: mqtt
  name: motion_animated_mask_woodshed
  topic: 'motion/+/woodshed/image-animated-mask'
- platform: mqtt
  name: motion_composite_woodshed
  topic: 'motion/+/woodshed/image-composite'
- platform: mqtt
  name: motion_animated_woodshed
  topic: 'motion/+/woodshed/image-animated'
- platform: mqtt
  name: motion_annotated_woodshed
  topic: 'motion/+/woodshed/image/+'
- platform: mqtt
  name: motion_cropped_woodshed
  topic: 'motion/+/woodshed/image-cropped'
