###
### frontwalk cameras
###
- platform: mjpeg
  mjpeg_url: http://frontwalk.dcmartin.com/img/video.mjpeg
  still_image_url: http://frontwalk.dcmartin.com/img/snapshot.cgi
  name: motion_live_frontwalk
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_image_frontwalk
  topic: 'motion/+/frontwalk/image'
- platform: mqtt
  name: motion_average_frontwalk
  topic: 'motion/+/frontwalk/image-average'
- platform: mqtt
  name: motion_blend_frontwalk
  topic: 'motion/+/frontwalk/image-blend'
- platform: mqtt
  name: motion_animated_mask_frontwalk
  topic: 'motion/+/frontwalk/image-animated-mask'
- platform: mqtt
  name: motion_composite_frontwalk
  topic: 'motion/+/frontwalk/image-composite'
- platform: mqtt
  name: motion_animated_frontwalk
  topic: 'motion/+/frontwalk/image-animated'
- platform: mqtt
  name: motion_annotated_frontwalk
  topic: 'motion/+/frontwalk/image/+'
- platform: mqtt
  name: motion_cropped_frontwalk
  topic: 'motion/+/frontwalk/image-cropped'
