###
### frontdoor cameras
###
- platform: mjpeg
  mjpeg_url: http://frontdoor.dcmartin.com/img/video.mjpeg
  still_image_url: http://frontdoor.dcmartin.com/img/snapshot.cgi
  name: motion_live_frontdoor
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_image_frontdoor
  topic: 'motion/+/frontdoor/image'
- platform: mqtt
  name: motion_average_frontdoor
  topic: 'motion/+/frontdoor/image-average'
- platform: mqtt
  name: motion_blend_frontdoor
  topic: 'motion/+/frontdoor/image-blend'
- platform: mqtt
  name: motion_animated_mask_frontdoor
  topic: 'motion/+/frontdoor/image-animated-mask'
- platform: mqtt
  name: motion_composite_frontdoor
  topic: 'motion/+/frontdoor/image-composite'
- platform: mqtt
  name: motion_animated_frontdoor
  topic: 'motion/+/frontdoor/image-animated'
- platform: mqtt
  name: motion_annotated_frontdoor
  topic: 'motion/+/frontdoor/image/+'
- platform: mqtt
  name: motion_cropped_frontdoor
  topic: 'motion/+/frontdoor/image-cropped'
