###
### dogpond cameras
###
- platform: mjpeg
  mjpeg_url: http://dogpond.dcmartin.com/img/video.mjpeg
  still_image_url: http://dogpond.dcmartin.com/img/snapshot.cgi
  name: motion_live_dogpond
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_image_dogpond
  topic: 'motion/+/dogpond/image'
- platform: mqtt
  name: motion_average_dogpond
  topic: 'motion/+/dogpond/image-average'
- platform: mqtt
  name: motion_blend_dogpond
  topic: 'motion/+/dogpond/image-blend'
- platform: mqtt
  name: motion_animated_mask_dogpond
  topic: 'motion/+/dogpond/image-animated-mask'
- platform: mqtt
  name: motion_composite_dogpond
  topic: 'motion/+/dogpond/image-composite'
- platform: mqtt
  name: motion_animated_dogpond
  topic: 'motion/+/dogpond/image-animated'
- platform: mqtt
  name: motion_annotated_dogpond
  topic: 'motion/+/dogpond/image/+'
- platform: mqtt
  name: motion_cropped_dogpond
  topic: 'motion/+/dogpond/image-cropped'
