settings_startup:
  name: settings_startup
  control: hidden
  entities:
    - input_number.startup_download_deviation
    - input_number.startup_average_deviation
    - input_number.startup_measurement_deviation
    - input_number.startup_client_deviation
