###
### nmap DEVICE_TRACKER
###

- platform: nmap_tracker
  hosts: !secret nmap-tracker-hosts
  home_interval: 10
  interval_seconds: 30
  new_device_defaults:
    track_new_devices: true
  consider_home: 180
  exclude:
    - !secret nmap-tracker-exclude
