- platform: mjpeg
  name: motion_live_backyard
  mjpeg_url: http://192.168.1.183/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_diningroom
  mjpeg_url: http://192.168.1.182/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_dogpond
  mjpeg_url: http://192.168.1.251:8090/4
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_dogshedfront
  mjpeg_url: http://192.168.1.172/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_dogshedmiddle
  mjpeg_url: http://192.168.1.170/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_dogshed
  mjpeg_url: http://192.168.1.173/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_dogyard
  mjpeg_url: http://192.168.1.169/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_equipmentroom
  mjpeg_url: http://192.168.1.165/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_fireplace
  mjpeg_url: http://192.168.1.166/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_foyer
  mjpeg_url: http://192.168.1.178/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_frontdoor
  mjpeg_url: http://192.168.1.37:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_frontwalk
  mjpeg_url: http://192.168.1.179/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_interiorgate
  mjpeg_url: http://192.168.1.251:8090/2
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_kitchen
  mjpeg_url: http://192.168.1.34:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_laundry
  mjpeg_url: http://192.168.1.177/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_livingroom
  mjpeg_url: http://192.168.1.164/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_phinterior
  mjpeg_url: http://192.168.1.39:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_pondview
  mjpeg_url: http://192.168.1.251:8090/5
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_poolcam
  mjpeg_url: http://192.168.1.251:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_road
  mjpeg_url: http://192.168.1.251:8090/3
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_shed
  mjpeg_url: http://192.168.1.251:8090/6
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_sideyard
  mjpeg_url: http://192.168.1.171/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

- platform: mjpeg
  name: motion_live_window
  mjpeg_url: http://192.168.1.40:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

- platform: mjpeg
  name: motion_live_woodshed
  mjpeg_url: http://192.168.1.163/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password
