###
## binary_sensor/internet.yaml
###

- platform: template
  sensors:
    internet_test:
      entity_id:
        - sensor.internet_test
        - sensor.internet_ago
      value_template: >
        {% if states.sensor.internet_ago.state|int > 30 %}False{% else %}True{% endif %}

- platform: template
  sensors:
    internet_slow:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states('sensor.internet_receive_statistics')|lower != 'unavailable' and state_attr('sensor.internet_receive_statistics','standard_deviation')|float > 0.0 %}
        {{ (((states.sensor.internet_receive_mean.state|float) - (states.sensor.internet_receive.state|float))
             / (state_attr('sensor.internet_receive_statistics','standard_deviation')|float) 
           > (states.input_number.internet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    internet_fast:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states('sensor.internet_receive_statistics')|lower != 'unavailable' and state_attr('sensor.internet_receive_statistics','standard_deviation')|float > 0 %}
        {{ (((states.sensor.internet_receive.state|float) - (states.sensor.internet_receive_mean.state|float))
             / (state_attr('sensor.internet_receive_statistics','standard_deviation')|float)) 
           > (states.input_number.internet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

- platform: template
  sensors:
    internet_slow_persistent:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states('input_number.internet_deviation')|lower != 'unavailable' 
             and states('sensor.internet_receive')|lower != 'unavailable' 
             and states('sensor.internet_receive_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.internet_receive_mean')|float) - (states('sensor.internet_receive')|float))
             / (states('sensor.internet_receive_stdev_mean')|float) 
           > (states('input_number.internet_deviation')|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    internet_fast_persistent:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states('input_number.internet_deviation')|lower != 'unavailable' 
             and states('sensor.internet_receive')|lower != 'unavailable' 
             and states('sensor.internet_receive_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.internet_receive')|float) - (states('sensor.internet_receive_mean')|float))
             / (states('sensor.internet_receive_stdev_mean')|float)) 
           > (states('input_number.internet_deviation')|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

