###
## binary_sensor/internet.yaml
###

- platform: template
  sensors:
    internet_test:
      value_template: >-
        {% if states('sensor.internet_ago')|int > 30 %}False{% else %}{{ states('sensor.internet_test')|lower == 'true' }}{% endif %}

- platform: template
  sensors:
    internet_slow:
      value_template: >-
        {% set id = states('input_number.internet_deviation') %}
        {% set ir = states('sensor.internet_receive') %}
        {% set irm = states('sensor.internet_receive_mean') %}
        {% set irs = states('sensor.internet_receive_statistics') %}
        {% set irsd = state_attr('sensor.internet_receive_statistics','standard_deviation') %}
        {% if id|lower != 'unavailable' 
          and ir|lower != 'unavailable' 
          and irm|lower != 'unavailable' 
          and irs|lower != 'unavailable' 
          and irsd|float > 0 %}
          {{ (((irm|float) - (ir|float)) / (irsd|float) > (id|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    internet_fast:
      value_template: >-
        {% if states('input_number.internet_deviation')|lower != 'unavailable' 
             and states('sensor.internet_receive')|lower != 'unavailable' 
             and states('sensor.internet_receive_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_statistics')|lower != 'unavailable' 
             and state_attr('sensor.internet_receive_statistics','standard_deviation')|float > 0 %}
        {{ (((states('sensor.internet_receive')|float) - (states('sensor.internet_receive_mean')|float))
             / (state_attr('sensor.internet_receive_statistics','standard_deviation')|float)) 
           > (states('input_number.internet_deviation')|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

- platform: template
  sensors:
    internet_slow_persistent:
      value_template: >-
        {% if states('input_number.internet_deviation')|lower != 'unavailable' 
             and states('sensor.internet_receive')|lower != 'unavailable' 
             and states('sensor.internet_receive_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.internet_receive_mean')|float) - (states('sensor.internet_receive')|float))
             / (states('sensor.internet_receive_stdev_mean')|float) 
           > (states('input_number.internet_deviation')|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    internet_fast_persistent:
      value_template: >-
        {% if states('input_number.internet_deviation')|lower != 'unavailable' 
             and states('sensor.internet_receive')|lower != 'unavailable' 
             and states('sensor.internet_receive_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.internet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.internet_receive')|float) - (states('sensor.internet_receive_mean')|float))
             / (states('sensor.internet_receive_stdev_mean')|float)) 
           > (states('input_number.internet_deviation')|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

