###
## binary_sensor/intranet.yaml
###

- platform: template
  sensors:
    intranet_test:
      entity_id:
        - sensor.intranet_test
        - sensor.intranet_ago
      value_template: >
        {% if states.sensor.intranet_ago.state|int > 30 %}False{% else %}True{% endif %}

- platform: template
  sensors:
    intranet_slow:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_statistics
        - input_number.intranet_deviation
      value_template: >-
        {% if states('sensor.intranet_receive_statistics')|lower != 'unavailable' and state_attr('sensor.intranet_receive_statistics','standard_deviation')|float > 0.0 %}
        {{ (((states.sensor.intranet_receive_mean.state|float) - (states.sensor.intranet_receive.state|float))
             / (state_attr('sensor.intranet_receive_statistics','standard_deviation')|float) 
           > (states.input_number.intranet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    intranet_fast:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_statistics
        - input_number.intranet_deviation
      value_template: >-
        {% if states('sensor.intranet_receive_statistics')|lower != 'unavailable' and state_attr('sensor.intranet_receive_statistics','standard_deviation')|float > 0 %}
        {{ (((states.sensor.intranet_receive.state|float) - (states.sensor.intranet_receive_mean.state|float))
             / (state_attr('sensor.intranet_receive_statistics','standard_deviation')|float)) 
           > (states.input_number.intranet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

- platform: template
  sensors:
    intranet_slow_persistent:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_stdev_mean
        - input_number.intranet_deviation
      value_template: >-
        {% if states('input_number.intranet_deviation')|lower != 'unavailable' 
             and states('sensor.intranet_receive')|lower != 'unavailable' 
             and states('sensor.intranet_receive_mean')|lower != 'unavailable' 
             and states('sensor.intranet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.intranet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.intranet_receive_mean')|float) - (states('sensor.intranet_receive')|float))
             / (states('sensor.intranet_receive_stdev_mean')|float) 
           > (states('input_number.intranet_deviation')|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad

- platform: template
  sensors:
    intranet_fast_persistent:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_stdev_mean
        - input_number.intranet_deviation
      value_template: >-
        {% if states('input_number.intranet_deviation')|lower != 'unavailable' 
             and states('sensor.intranet_receive')|lower != 'unavailable' 
             and states('sensor.intranet_receive_mean')|lower != 'unavailable' 
             and states('sensor.intranet_receive_stdev_mean')|lower != 'unavailable' 
             and states('sensor.intranet_receive_stdev_mean')|float > 0 %}
        {{ (((states('sensor.intranet_receive')|float) - (states('sensor.intranet_receive_mean')|float))
             / (states('sensor.intranet_receive_stdev_mean')|float)) 
           > (states('input_number.intranet_deviation')|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

