- platform: template
  sensors:
    weather_forecast:
      friendly_name: Weather forecast
      icon_template: 'mdi:help-network'
      value_template: >-
        {{ states.weather.home.attributtion|lower != 'unknown' }}
