##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
        - sensor.motion_annotated_ago
      value_template: >
        {% if states.sensor.motion_event_annotated|lower != 'none' %}
          {{ states('sensor.motion_event_annotated')|lower == 'true' }}
        {% else %}null{% endif %}
