##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {% if states.sensor.motion_event_annotated != none %}
          {{ states.sensor.motion_event_annotated.state|lower == 'true' }}
        {% else %}null{% endif %}
