##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {% if states.sensor.motion_event_annotated != none %}
          {{ states.sensor.motion_event_annotated.state|lower == 'true' }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_complete:
      entity_id:
        - camera.motion_event_annotated
      value_template: >
        {% if states('camera.motion_event_annotated') != 'unknown' %}
          {% set s = states.sensor.motion_event_annotated.last_updated %}
          {% set c = states.camera.motion_event_annotated.last_updated %}
          {% set d = as_timestamp(c) - as_timestamp(s) %}
          {{ d|int > 0 and d|int < states('input_number.motion_annotated_complete')|int }}
        {% else %}null{% endif %}
