###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - binary_sensor.motion_annotated
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated != none %}
          {{ states.sensor.motion_event_annotated.state|lower == 'true' 
             and states('sensor.motion_annotated_count')|int > 0 }}
        {% else %}null{% endif %}
