###
### detected_entity BINARY_SENSOR
###

- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - binary_sensor.motion_annotated
        - sensor.motion_detected_entity_count
      value_template: >-
        {% if states.sensor.motion_detected_entity_count != none %}
          {{ states.sensor.motion_detected_entity_count.state|int > 0 }}
        {% else %}null{% endif %}
