###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {{ states('sensor.motion_annotated_count')|int > 0 }}
