###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {% if states.sensor.motion_detected_count is defined %}
          {{ states.sensor.motion_detected_count.state|int > 0 }}
        {% else %}null{% endif %}
    # counter of events
    motion_detected_counter_low:
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_counter_statistics
        - input_number.motion_detected_counter_deviation
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_detected_counter_statistics.state|float) - (states.sensor.motion_detected_counter.state|float))
               / (states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_detected_counter_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_detected_counter_low_persistent:
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_counter_stdev_statistics
        - input_number.motion_detected_counter_deviation
      value_template: >-
        {% if states.sensor.motion_detected_counter_stdev_statistics.state|float > 0 %}
          {{ (((states.sensor.motion_detected_counter_statistics.state|float) - (states.sensor.motion_detected_counter.state|float))
               / (states.sensor.motion_detected_counter_stdev_statistics.state|float)
             > (states.input_number.motion_detected_counter_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_detected_counter_high:
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_counter_statistics
        - input_number.motion_detected_counter_deviation
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_detected_counter.state|float) - (states.sensor.motion_detected_counter_statistics.state|float))
               / (states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_detected_counter_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_detected_counter_high_persistent:
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_counter_stdev_statistics
        - input_number.motion_detected_counter_deviation
      value_template: >-
        {% if states.input_number.motion_detected_counter_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_detected_counter.state|float) - (states.sensor.motion_detected_counter_statistics.state|float))
               / (states.sensor.motion_detected_counter_stdev_statistics.state|float))
             > (states.input_number.motion_detected_counter_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    # count of entities
    motion_detected_count_low:
      entity_id:
        - sensor.motion_detected_count
        - sensor.motion_detected_count_statistics
        - input_number.motion_detected_count_deviation
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_detected_count_statistics.state|float) - (states.sensor.motion_detected_count.state|float))
               / (states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_detected_count_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_detected_count_low_persistent:
      entity_id:
        - sensor.motion_detected_count
        - sensor.motion_detected_count_stdev_statistics
        - input_number.motion_detected_count_deviation
      value_template: >-
        {% if states.sensor.motion_detected_count_stdev_statistics.state|float > 0 %}
          {{ (((states.sensor.motion_detected_count_statistics.state|float) - (states.sensor.motion_detected_count.state|float))
               / (states.sensor.motion_detected_count_stdev_statistics.state|float)
             > (states.input_number.motion_detected_count_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_detected_count_high:
      entity_id:
        - sensor.motion_detected_count
        - sensor.motion_detected_count_statistics
        - input_number.motion_detected_count_deviation
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_detected_count.state|float) - (states.sensor.motion_detected_count_statistics.state|float))
               / (states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_detected_count_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_detected_count_high_persistent:
      entity_id:
        - sensor.motion_detected_count
        - sensor.motion_detected_count_stdev_statistics
        - input_number.motion_detected_count_deviation
      value_template: >-
        {% if states.input_number.motion_detected_count_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_detected_count.state|float) - (states.sensor.motion_detected_count_statistics.state|float))
               / (states.sensor.motion_detected_count_stdev_statistics.state|float))
             > (states.input_number.motion_detected_count_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
