###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - binary_sensor.motion_annotated
      value_template: >-
        {% if states.sensor.motion_event_annotated != none 
              and states.sensor.motion_event_annotated.attributes.count|int is number %}
          {{ states.sensor.motion_event_annotated.attributes.count|int > 0 }}
        {% else %}null{% endif %}
