###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - binary_sensor.motion_annotated
      value_template: >-
        {{ is_state('binary_sensor.motion_annotated','on') and states('sensor.motion_annotated_count')|int > 0 }}
