###
### detected_entity BINARY_SENSOR
###

- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - group.motion_detected_entity_webcams
      value_template: >-
        {{ is_state('group.motion_detected_entity_webcams','on') }}

#- platform: template
#  sensors:
#    motion_detected_entity:
#      entity_id:
#        - sensor.motion_detect_entity_count
#      value_template: >-
#        {% if states.sensor.motion_detect_entity_count != none and states.sensor.motion_detect_entity_count.state != 'null' %}
#          {{ states.sensor.motion_detect_entity_count.state|int > 0 }}
#        {% else %}null{% endif %}
