###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {{ state_attr('sensor.motion_event_annotated','count')|int > 0
           and states('sensor.motion_detected_ago') != 'null'
           and states('sensor.motion_detected_ago')|int < states('input_number.motion_detected_entity_ago')|int }}

