###
### DETECTED ENTITY
###

- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - binary_sensor.motion_detected
      value_template: >-
        {% if states.sensor.motion_detected_entity_count is defined
              and states.sensor.motion_detected_entity_count.state is defined
              and states.sensor.motion_detected_entity_count.state|int is number %}
          {{ states.sensor.motion_detected_entity_count.state|int > 0 }}
        {% else %}null{% endif %}
