###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - group.motion_detected_webcams
      value_template: >-
        {{ is_state('group.motion_detected_webcams','on') }}

#- platform: template
#  sensors:
#    motion_detected:
#      entity_id:
#        - sensor.motion_event_annotated
#      value_template: >-
#        {% if states.sensor.motion_event_annotated != none 
#              and state_attr('sensor.motion_event_annotated','count') != none %}
#          {{ states.sensor.motion_event_annotated.attributes.count|int > 0 }}
#        {% else %}null{% endif %}
