###
### detected_entity BINARY_SENSOR
###


- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - sensor.motion_annotated_entity_count
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count')|int > 0 
           and states('sensor.motion_detected_entity_ago') != 'null'
           and states('sensor.motion_detected_entity_ago')|int < states('input_number.motion_detected_entity_ago')|int }}
