###
### detected_entity BINARY_SENSOR
###


- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - binary_sensor.motion_detected
        - sensor.motion_detected_entity_ago
      value_template: >-
        {{ states('binary_sensor.motion_detected') == 'on'
           and states('sensor.motion_annotated_entity_count')|int > 0 }}
