###
### detected_entity BINARY_SENSOR
###


- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count')|int > 0 }}
