###
### BINARY_SENSOR DETECTED
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {{ state_attr('sensor.motion_event_annotated','count')|int > 0 }}
