###
### EVENT END
###

- platform: template
  sensors:
    motion_end_state:
      entity_id:
        - sensor.motion_event_end
      value_template: >
        {{ states.sensor.motion_event_end.state|lower == 'true' }}
