##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
        - sensor.motion_annotated_ago
      value_template: >
        {{ states.sensor.motion_event_annotated.state == 'True' }}
    motion_detected:
      entity_id:
        - sensor.motion_annotated_count
      value_template: >-
        {% if states.sensor.motion_annotated_count is defined %}
          {{ states.sensor.motion_annotated_count.state|int > 0 }}
        {% else %}False{% endif %}
    motion_detected_entity:
      entity_id:
        - sensor.motion_detected_entity_count
      value_template: >-
        {% if states.sensor.motion_detected_entity_count is defined %}
          {{ states.sensor.motion_detected_entity_count.state|int > 0 }}
        {% else %}False{% endif %}
