##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {{ states.sensor.motion_event_annotated.state == 'True' }}
    # counter of events
    motion_annotated_counter_low:
      entity_id:
        - sensor.motion_annotated_counter
        - sensor.motion_annotated_counter_statistics
        - input_number.motion_annotated_counter_deviation
      value_template: >-
        {% if states.sensor.motion_annotated_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_annotated_counter_statistics.state|float) - (states.sensor.motion_annotated_counter.state|float))
               / (states.sensor.motion_annotated_counter_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_annotated_counter_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_annotated_counter_low_persistent:
      entity_id:
        - sensor.motion_annotated_counter
        - sensor.motion_annotated_counter_stdev_statistics
        - input_number.motion_annotated_counter_deviation
      value_template: >-
        {% if states.sensor.motion_annotated_counter_stdev_statistics.state|float > 0 %}
          {{ (((states.sensor.motion_annotated_counter_statistics.state|float) - (states.sensor.motion_annotated_counter.state|float))
               / (states.sensor.motion_annotated_counter_stdev_statistics.state|float)
             > (states.input_number.motion_annotated_counter_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_annotated_counter_high:
      entity_id:
        - sensor.motion_annotated_counter
        - sensor.motion_annotated_counter_statistics
        - input_number.motion_annotated_counter_deviation
      value_template: >-
        {% if states.sensor.motion_annotated_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_annotated_counter.state|float) - (states.sensor.motion_annotated_counter_statistics.state|float))
               / (states.sensor.motion_annotated_counter_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_annotated_counter_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_annotated_counter_high_persistent:
      entity_id:
        - sensor.motion_annotated_counter
        - sensor.motion_annotated_counter_stdev_statistics
        - input_number.motion_annotated_counter_deviation
      value_template: >-
        {% if states.input_number.motion_annotated_counter_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_annotated_counter.state|float) - (states.sensor.motion_annotated_counter_statistics.state|float))
               / (states.sensor.motion_annotated_counter_stdev_statistics.state|float))
             > (states.input_number.motion_annotated_counter_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
