###
### EVENT END
###

- platform: template
  sensors:
    motion_state:
      entity_id:
        - sensor.motion_event_end
        - sensor.motion_ago
      value_template: >
        {{ states.sensor.motion_event_end.state == 'True' }}
    motion_low:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_counter_statistics.state|float) - (states.sensor.motion_counter.state|float))
               / (states.sensor.motion_counter_statistics.attributes.standard_deviation|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_low_persistent:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.motion_counter_statistics.state|float) - (states.sensor.motion_counter.state|float))
               / (states.sensor.motion_counter_stdev_mean.state|float)
             > (states.input_number.motion_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    motion_high:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_statistics
        - input_number.motion_deviation
      value_template: >-
        {% if states.sensor.motion_counter_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.motion_counter.state|float) - (states.sensor.motion_counter_statistics.state|float))
               / (states.sensor.motion_counter_statistics.attributes.standard_deviation|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    motion_high_persistent:
      entity_id:
        - sensor.motion_counter
        - sensor.motion_counter_stdev_mean
        - input_number.motion_deviation
      value_template: >-
        {% if states.input_number.motion_deviation.state|float > 0 %}
          {{ (((states.sensor.motion_counter.state|float) - (states.sensor.motion_counter_statistics.state|float))
               / (states.sensor.motion_counter_stdev_mean.state|float))
             > (states.input_number.motion_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
