###
# motion/binary_sensor/webcams.yaml
###

- platform: template
  sensors:
    motion_detected_entity_webcams:
      entity_id:
        - group.motion_detected_entity_webcams
      value_template: >
        {% if states.group.motion_detected_entity_webcams|lower != 'none'
              and state_attr('group.motion_detected_entity_webcams','entity_id')|lower != 'none'
              and states.group.motion_detected_entity_webcams.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_detected_entity_webcams.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_webcams:
      entity_id:
        - group.motion_detected_webcams
      value_template: >
        {% if states.group.motion_detected_webcams|lower != 'none'
              and state_attr('group.motion_detected_webcams','entity_id')|lower != 'none'
              and states.group.motion_detected_webcams.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_detected_webcams.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_annotated_webcams:
      entity_id:
        - group.motion_annotated_webcams
      value_template: >
        {% if states.group.motion_annotated_webcams|lower != 'none'
              and state_attr('group.motion_annotated_webcams','entity_id')|lower != 'none'
              and states.group.motion_annotated_webcams.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_annotated_webcams.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_end_webcams:
      entity_id:
        - group.motion_end_webcams
      value_template: >
        {% if states.group.motion_end_webcams|lower != 'none'
              and state_attr('group.motion_end_webcams','entity_id')|lower != 'none'
              and states.group.motion_end_webcams.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_end_webcams.state }}
        {% else %}null{% endif %}
