###
### backyard cameras
###
- platform: mjpeg
  mjpeg_url: http://backyard.dcmartin.com/img/video.mjpeg
  still_image_url: http://backyard.dcmartin.com/img/snapshot.cgi
  name: motion_live_backyard
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_backyard
  topic: 'motion/+/backyard/image'
- platform: mqtt
  name: motion_image_backyard
  topic: 'motion/+/backyard/image/end'
- platform: mqtt
  name: motion_average_backyard
  topic: 'motion/+/backyard/image-average'
- platform: mqtt
  name: motion_blend_backyard
  topic: 'motion/+/backyard/image-blend'
- platform: mqtt
  name: motion_animated_mask_backyard
  topic: 'motion/+/backyard/image-animated-mask'
- platform: mqtt
  name: motion_composite_backyard
  topic: 'motion/+/backyard/image-composite'
- platform: mqtt
  name: motion_animated_backyard
  topic: 'motion/+/backyard/image-animated'
- platform: mqtt
  name: motion_annotated_backyard
  topic: 'motion/+/backyard/image/end/+'
- platform: mqtt
  name: motion_cropped_backyard
  topic: 'motion/+/backyard/image-cropped'
