###
### diningroom cameras
###
- platform: mjpeg
  mjpeg_url: http://diningroom.dcmartin.com/img/video.mjpeg
  still_image_url: http://diningroom.dcmartin.com/img/snapshot.cgi
  name: motion_live_diningroom
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_diningroom
  topic: 'motion/+/diningroom/image'
- platform: mqtt
  name: motion_image_diningroom
  topic: 'motion/+/diningroom/image/end'
- platform: mqtt
  name: motion_average_diningroom
  topic: 'motion/+/diningroom/image-average'
- platform: mqtt
  name: motion_blend_diningroom
  topic: 'motion/+/diningroom/image-blend'
- platform: mqtt
  name: motion_animated_mask_diningroom
  topic: 'motion/+/diningroom/image-animated-mask'
- platform: mqtt
  name: motion_composite_diningroom
  topic: 'motion/+/diningroom/image-composite'
- platform: mqtt
  name: motion_animated_diningroom
  topic: 'motion/+/diningroom/image-animated'
- platform: mqtt
  name: motion_annotated_diningroom
  topic: 'motion/+/diningroom/image/end/+'
- platform: mqtt
  name: motion_cropped_diningroom
  topic: 'motion/+/diningroom/image-cropped'
