###
### dogshedmiddle cameras
###
- platform: mjpeg
  mjpeg_url: http://dogshedmiddle.dcmartin.com/img/video.mjpeg
  still_image_url: http://dogshedmiddle.dcmartin.com/img/snapshot.cgi
  name: motion_live_dogshedmiddle
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image'
- platform: mqtt
  name: motion_image_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image/end'
- platform: mqtt
  name: motion_average_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-average'
- platform: mqtt
  name: motion_blend_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-blend'
- platform: mqtt
  name: motion_animated_mask_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-animated-mask'
- platform: mqtt
  name: motion_composite_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-composite'
- platform: mqtt
  name: motion_animated_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-animated'
- platform: mqtt
  name: motion_annotated_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image/end/+'
- platform: mqtt
  name: motion_cropped_dogshedmiddle
  topic: 'motion/+/dogshedmiddle/image-cropped'
