###
### dogshed cameras
###
- platform: mjpeg
  mjpeg_url: http://dogshed.dcmartin.com/img/video.mjpeg
  still_image_url: http://dogshed.dcmartin.com/img/snapshot.cgi
  name: motion_live_dogshed
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_dogshed
  topic: 'motion/+/dogshed/image'
- platform: mqtt
  name: motion_image_dogshed
  topic: 'motion/+/dogshed/image/end'
- platform: mqtt
  name: motion_average_dogshed
  topic: 'motion/+/dogshed/image-average'
- platform: mqtt
  name: motion_blend_dogshed
  topic: 'motion/+/dogshed/image-blend'
- platform: mqtt
  name: motion_animated_mask_dogshed
  topic: 'motion/+/dogshed/image-animated-mask'
- platform: mqtt
  name: motion_composite_dogshed
  topic: 'motion/+/dogshed/image-composite'
- platform: mqtt
  name: motion_animated_dogshed
  topic: 'motion/+/dogshed/image-animated'
- platform: mqtt
  name: motion_annotated_dogshed
  topic: 'motion/+/dogshed/image/end/+'
- platform: mqtt
  name: motion_cropped_dogshed
  topic: 'motion/+/dogshed/image-cropped'
