###
### dogshedfront cameras
###
- platform: mjpeg
  mjpeg_url: http://dogshedfront.dcmartin.com/img/video.mjpeg
  still_image_url: http://dogshedfront.dcmartin.com/img/snapshot.cgi
  name: motion_live_dogshedfront
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_dogshedfront
  topic: 'motion/+/dogshedfront/image'
- platform: mqtt
  name: motion_image_dogshedfront
  topic: 'motion/+/dogshedfront/image/end'
- platform: mqtt
  name: motion_average_dogshedfront
  topic: 'motion/+/dogshedfront/image-average'
- platform: mqtt
  name: motion_blend_dogshedfront
  topic: 'motion/+/dogshedfront/image-blend'
- platform: mqtt
  name: motion_animated_mask_dogshedfront
  topic: 'motion/+/dogshedfront/image-animated-mask'
- platform: mqtt
  name: motion_composite_dogshedfront
  topic: 'motion/+/dogshedfront/image-composite'
- platform: mqtt
  name: motion_animated_dogshedfront
  topic: 'motion/+/dogshedfront/image-animated'
- platform: mqtt
  name: motion_annotated_dogshedfront
  topic: 'motion/+/dogshedfront/image/end/+'
- platform: mqtt
  name: motion_cropped_dogshedfront
  topic: 'motion/+/dogshedfront/image-cropped'
