###
### dogyard cameras
###
- platform: mjpeg
  mjpeg_url: http://dogyard.dcmartin.com/img/video.mjpeg
  still_image_url: http://dogyard.dcmartin.com/img/snapshot.cgi
  name: motion_live_dogyard
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_dogyard
  topic: 'motion/+/dogyard/image'
- platform: mqtt
  name: motion_image_dogyard
  topic: 'motion/+/dogyard/image/end'
- platform: mqtt
  name: motion_average_dogyard
  topic: 'motion/+/dogyard/image-average'
- platform: mqtt
  name: motion_blend_dogyard
  topic: 'motion/+/dogyard/image-blend'
- platform: mqtt
  name: motion_animated_mask_dogyard
  topic: 'motion/+/dogyard/image-animated-mask'
- platform: mqtt
  name: motion_composite_dogyard
  topic: 'motion/+/dogyard/image-composite'
- platform: mqtt
  name: motion_animated_dogyard
  topic: 'motion/+/dogyard/image-animated'
- platform: mqtt
  name: motion_annotated_dogyard
  topic: 'motion/+/dogyard/image/end/+'
- platform: mqtt
  name: motion_cropped_dogyard
  topic: 'motion/+/dogyard/image-cropped'
