###
### fireplace cameras
###
- platform: mjpeg
  mjpeg_url: http://fireplace.dcmartin.com/img/video.mjpeg
  still_image_url: http://fireplace.dcmartin.com/img/snapshot.cgi
  name: motion_live_fireplace
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_fireplace
  topic: 'motion/+/fireplace/image'
- platform: mqtt
  name: motion_image_fireplace
  topic: 'motion/+/fireplace/image/end'
- platform: mqtt
  name: motion_average_fireplace
  topic: 'motion/+/fireplace/image-average'
- platform: mqtt
  name: motion_blend_fireplace
  topic: 'motion/+/fireplace/image-blend'
- platform: mqtt
  name: motion_animated_mask_fireplace
  topic: 'motion/+/fireplace/image-animated-mask'
- platform: mqtt
  name: motion_composite_fireplace
  topic: 'motion/+/fireplace/image-composite'
- platform: mqtt
  name: motion_animated_fireplace
  topic: 'motion/+/fireplace/image-animated'
- platform: mqtt
  name: motion_annotated_fireplace
  topic: 'motion/+/fireplace/image/end/+'
- platform: mqtt
  name: motion_cropped_fireplace
  topic: 'motion/+/fireplace/image-cropped'
