###
### foyer cameras
###
- platform: mjpeg
  mjpeg_url: http://foyer.dcmartin.com/img/video.mjpeg
  still_image_url: http://foyer.dcmartin.com/img/snapshot.cgi
  name: motion_live_foyer
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_foyer
  topic: 'motion/+/foyer/image'
- platform: mqtt
  name: motion_image_foyer
  topic: 'motion/+/foyer/image/end'
- platform: mqtt
  name: motion_average_foyer
  topic: 'motion/+/foyer/image-average'
- platform: mqtt
  name: motion_blend_foyer
  topic: 'motion/+/foyer/image-blend'
- platform: mqtt
  name: motion_animated_mask_foyer
  topic: 'motion/+/foyer/image-animated-mask'
- platform: mqtt
  name: motion_composite_foyer
  topic: 'motion/+/foyer/image-composite'
- platform: mqtt
  name: motion_animated_foyer
  topic: 'motion/+/foyer/image-animated'
- platform: mqtt
  name: motion_annotated_foyer
  topic: 'motion/+/foyer/image/end/+'
- platform: mqtt
  name: motion_cropped_foyer
  topic: 'motion/+/foyer/image-cropped'
