###
### gravelpad cameras
###
- platform: mjpeg
  mjpeg_url: http://gravelpad.dcmartin.com/img/video.mjpeg
  still_image_url: http://gravelpad.dcmartin.com/img/snapshot.cgi
  name: motion_live_gravelpad
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_gravelpad
  topic: 'motion/+/gravelpad/image'
- platform: mqtt
  name: motion_image_gravelpad
  topic: 'motion/+/gravelpad/image/end'
- platform: mqtt
  name: motion_average_gravelpad
  topic: 'motion/+/gravelpad/image-average'
- platform: mqtt
  name: motion_blend_gravelpad
  topic: 'motion/+/gravelpad/image-blend'
- platform: mqtt
  name: motion_animated_mask_gravelpad
  topic: 'motion/+/gravelpad/image-animated-mask'
- platform: mqtt
  name: motion_composite_gravelpad
  topic: 'motion/+/gravelpad/image-composite'
- platform: mqtt
  name: motion_animated_gravelpad
  topic: 'motion/+/gravelpad/image-animated'
- platform: mqtt
  name: motion_annotated_gravelpad
  topic: 'motion/+/gravelpad/image/end/+'
- platform: mqtt
  name: motion_cropped_gravelpad
  topic: 'motion/+/gravelpad/image-cropped'
