###
### livingroom cameras
###
- platform: mjpeg
  mjpeg_url: http://livingroom.dcmartin.com/img/video.mjpeg
  still_image_url: http://livingroom.dcmartin.com/img/snapshot.cgi
  name: motion_live_livingroom
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_livingroom
  topic: 'motion/+/livingroom/image'
- platform: mqtt
  name: motion_image_livingroom
  topic: 'motion/+/livingroom/image/end'
- platform: mqtt
  name: motion_average_livingroom
  topic: 'motion/+/livingroom/image-average'
- platform: mqtt
  name: motion_blend_livingroom
  topic: 'motion/+/livingroom/image-blend'
- platform: mqtt
  name: motion_animated_mask_livingroom
  topic: 'motion/+/livingroom/image-animated-mask'
- platform: mqtt
  name: motion_composite_livingroom
  topic: 'motion/+/livingroom/image-composite'
- platform: mqtt
  name: motion_animated_livingroom
  topic: 'motion/+/livingroom/image-animated'
- platform: mqtt
  name: motion_annotated_livingroom
  topic: 'motion/+/livingroom/image/end/+'
- platform: mqtt
  name: motion_cropped_livingroom
  topic: 'motion/+/livingroom/image-cropped'
