###
### phexterior cameras
###
- platform: mjpeg
  mjpeg_url: http://phexterior.dcmartin.com/img/video.mjpeg
  still_image_url: http://phexterior.dcmartin.com/img/snapshot.cgi
  name: motion_live_phexterior
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_phexterior
  topic: 'motion/+/phexterior/image'
- platform: mqtt
  name: motion_image_phexterior
  topic: 'motion/+/phexterior/image/end'
- platform: mqtt
  name: motion_average_phexterior
  topic: 'motion/+/phexterior/image-average'
- platform: mqtt
  name: motion_blend_phexterior
  topic: 'motion/+/phexterior/image-blend'
- platform: mqtt
  name: motion_animated_mask_phexterior
  topic: 'motion/+/phexterior/image-animated-mask'
- platform: mqtt
  name: motion_composite_phexterior
  topic: 'motion/+/phexterior/image-composite'
- platform: mqtt
  name: motion_animated_phexterior
  topic: 'motion/+/phexterior/image-animated'
- platform: mqtt
  name: motion_annotated_phexterior
  topic: 'motion/+/phexterior/image/end/+'
- platform: mqtt
  name: motion_cropped_phexterior
  topic: 'motion/+/phexterior/image-cropped'
