###
### pondview cameras
###
- platform: mjpeg
  mjpeg_url: http://pondview.dcmartin.com/img/video.mjpeg
  still_image_url: http://pondview.dcmartin.com/img/snapshot.cgi
  name: motion_live_pondview
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_pondview
  topic: 'motion/+/pondview/image'
- platform: mqtt
  name: motion_image_pondview
  topic: 'motion/+/pondview/image/end'
- platform: mqtt
  name: motion_average_pondview
  topic: 'motion/+/pondview/image-average'
- platform: mqtt
  name: motion_blend_pondview
  topic: 'motion/+/pondview/image-blend'
- platform: mqtt
  name: motion_animated_mask_pondview
  topic: 'motion/+/pondview/image-animated-mask'
- platform: mqtt
  name: motion_composite_pondview
  topic: 'motion/+/pondview/image-composite'
- platform: mqtt
  name: motion_animated_pondview
  topic: 'motion/+/pondview/image-animated'
- platform: mqtt
  name: motion_annotated_pondview
  topic: 'motion/+/pondview/image/end/+'
- platform: mqtt
  name: motion_cropped_pondview
  topic: 'motion/+/pondview/image-cropped'
