###
### sideyard cameras
###
- platform: mjpeg
  mjpeg_url: http://sideyard.dcmartin.com/img/video.mjpeg
  still_image_url: http://sideyard.dcmartin.com/img/snapshot.cgi
  name: motion_live_sideyard
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_sideyard
  topic: 'motion/+/sideyard/image'
- platform: mqtt
  name: motion_image_sideyard
  topic: 'motion/+/sideyard/image/end'
- platform: mqtt
  name: motion_average_sideyard
  topic: 'motion/+/sideyard/image-average'
- platform: mqtt
  name: motion_blend_sideyard
  topic: 'motion/+/sideyard/image-blend'
- platform: mqtt
  name: motion_animated_mask_sideyard
  topic: 'motion/+/sideyard/image-animated-mask'
- platform: mqtt
  name: motion_composite_sideyard
  topic: 'motion/+/sideyard/image-composite'
- platform: mqtt
  name: motion_animated_sideyard
  topic: 'motion/+/sideyard/image-animated'
- platform: mqtt
  name: motion_annotated_sideyard
  topic: 'motion/+/sideyard/image/end/+'
- platform: mqtt
  name: motion_cropped_sideyard
  topic: 'motion/+/sideyard/image-cropped'
