###
### upperpathgate cameras
###
- platform: mjpeg
  mjpeg_url: http://upperpathgate.dcmartin.com/img/video.mjpeg
  still_image_url: http://upperpathgate.dcmartin.com/img/snapshot.cgi
  name: motion_live_upperpathgate
  username: !secret wcv80n-username
  password: !secret wcv80n-password
- platform: mqtt
  name: motion_current_upperpathgate
  topic: 'motion/+/upperpathgate/image'
- platform: mqtt
  name: motion_image_upperpathgate
  topic: 'motion/+/upperpathgate/image/end'
- platform: mqtt
  name: motion_average_upperpathgate
  topic: 'motion/+/upperpathgate/image-average'
- platform: mqtt
  name: motion_blend_upperpathgate
  topic: 'motion/+/upperpathgate/image-blend'
- platform: mqtt
  name: motion_animated_mask_upperpathgate
  topic: 'motion/+/upperpathgate/image-animated-mask'
- platform: mqtt
  name: motion_composite_upperpathgate
  topic: 'motion/+/upperpathgate/image-composite'
- platform: mqtt
  name: motion_animated_upperpathgate
  topic: 'motion/+/upperpathgate/image-animated'
- platform: mqtt
  name: motion_annotated_upperpathgate
  topic: 'motion/+/upperpathgate/image/end/+'
- platform: mqtt
  name: motion_cropped_upperpathgate
  topic: 'motion/+/upperpathgate/image-cropped'
