###
### start BINARY_SENSOR
###

## state
- platform: template
  sensors:
    startup_state:
      entity_id:
        - sensor.startup_latest_id
        - sensor.startup_ago
      value_template: >
        {{ states.sensor.startup_event.state }}

## high low 
- platform: template
  sensors:
    startup_client_low:
      entity_id:
        - sensor.startup_client_count
        - sensor.startup_client_count_statistics
        - input_number.startup_client_deviation
      value_template: >-
        {% if states.sensor.startup_client_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.startup_client_count_statistics.state|float) - (states.sensor.startup_client_count.state|float))
               / (states.sensor.startup_client_count_statistics.attributes.standard_deviation|float) 
             > (states.input_number.startup_client_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    startup_client_low_persistent:
      entity_id:
        - sensor.startup_client_count
        - sensor.startup_client_count_stdev_mean
        - input_number.startup_client_deviation
      value_template: >-
        {% if states.sensor.startup_client_count_stdev_mean.state|float > 0 %}
          {{ (((states.sensor.startup_client_count_statistics.state|float) - (states.sensor.startup_client_count.state|float))
               / (states.sensor.startup_client_count_stdev_mean.state|float) 
             > (states.input_number.startup_client_deviation.state|float)) }}
        {%- else -%}false{%- endif -%}
      icon_template: >
          mdi:emoticon-sad
    startup_client_high:
      entity_id:
        - sensor.startup_client_count
        - sensor.startup_client_count_statistics
        - input_number.startup_client_deviation
      value_template: >-
        {% if states.sensor.startup_client_count_statistics.attributes.standard_deviation|float > 0 %}
          {{ (((states.sensor.startup_client_count.state|float) - (states.sensor.startup_client_count_statistics.state|float))
               / (states.sensor.startup_client_count_statistics.attributes.standard_deviation|float)) 
             > (states.input_number.startup_client_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
    startup_client_high_persistent:
      entity_id:
        - sensor.startup_client_count
        - sensor.startup_client_count_stdev_mean
        - input_number.startup_client_deviation
      value_template: >-
        {% if states.input_number.startup_client_deviation.state|float > 0 %}
          {{ (((states.sensor.startup_client_count.state|float) - (states.sensor.startup_client_count_statistics.state|float))
               / (states.sensor.startup_client_count_stdev_mean.state|float)) 
             > (states.input_number.startup_client_deviation.state|float) }}
        {%- else -%}false{%- endif -%}
      icon_template: >-
          mdi:emoticon-happy
