###
# homeassistant/sensor/motion/alarm.yaml
###

- platform: statistics
  name: motion_schedule_wake_statistics
  entity_id: sensor.motion_schedule_wake
  sampling_size: 100
  max_age:
    hours: 720

- platform: template
  sensors:
    motion_schedule_wake_mean:
      friendly_name: 'First person Î¼'
      icon_template: 'mdi:clock'
      unit_of_measurement: 'seconds'
      value_template: >-
        {% if states('sensor.motion_schedule_wake_statistics') != 'unknown' %}
          {{ states('sensor.motion_schedule_wake_statistics')|float }}
        {%- else -%}null{%- endif -%}

- platform: template
  sensors:
    motion_alarm_wake_begin:
      friendly_name: 'Wake time begin'
      icon_template: 'mdi:alarm-check'
      value_template: >-
        {% set s = states('input_number.motion_alarm_wake_begin')|int %}
        {% if s > 0 %}
          {% set h = (s/3600)|int %}
          {% set m = ((s-(h*3600))/60)|int %}
          {% set s = (s % 60)|int %}
          {% if h < 1 %}
            {% if m < 1 %}
              {{- '00:00:' + '%02d' % s -}}
            {% else %}
            {{- '00:' + '%02d' % m + ':' + '%02d' % s -}}
            {% endif %}
          {% else %}
            {{- '%02d' % h + ':' + '%02d' % m + ':' + '%02d' % s -}}
          {% endif %}
        {%- else -%}{{- '00:00:00' -}}{%- endif -%}

- platform: template
  sensors:
    motion_schedule_wake:
      friendly_name: 'First person'
      unit_of_measurement: seconds
      icon_template: 'mdi:clock'
      value_template: >-
        {{ null }}

