- platform: template
  sensors:
    motion_alarm_wake_begin:
      friendly_name: 'Wake-up time'
      icon_template: 'mdi:clock'
      value_template: >
        {% set s = states('input_number.motion_alarm_wake_begin')|int %}
        {% if s > 0 %}
          {% set h = (s/3600)|int %}
          {% set m = ((s-(h*3600))/60)|int %}
          {% set s = (s % 60)|int %}
          {% if h < 1 %}
            {% if m < 1 %}
              {{- '00:00:' + '%02d' % s -}}
            {% else %}
            {{- '00:' + '%02d' % m + ':' + '%02d' % s -}}
            {% endif %}
          {% else %}
            {{- '%02d' % h + ':' + '%02d' % m + ':' + '%02d' % s -}}
          {% endif %}
        {%- else -%}'00:00'{%- endif -%}
