###
# sensor/motion/alpr.yaml
###

## status
- platform: template
  sensors:
    motion_alpr_status:
      friendly_name: ALPR
      value_template: >-
        {% if is_state('binary_sensor.motion_alpr','on') %}
          {% set e = state_attr('sensor.motion_event_alpr','event') %}
          {% if e is mapping %}
            {% set n = utcnow().timestamp()|int %}
            {% set end = e.end|int %}
            {% set event = e.event %}
            {% set device = e.device %}
            {% set camera = e.camera %}
            {% set elapsed = e.elapsed|int %}
            {% set what = state_attr('sensor.motion_event_alpr','detected') %}
            {% if what is none or what|lower == 'unknown' or what|length == 0 %}{% set what = 'nothing' %}{% endif %} 
            {% set count = state_attr('sensor.motion_event_alpr','count')|int %}
            {% set when = end|timestamp_custom("%a %b %d %I:%M:%S %p %Z") %}
            {% set delay = n - end %}
            ALPR: {{ count }} {{ what }};
            from {{ device -}}/{{- camera -}}/{{- event -}};
            at {{ when }};
            delay: {{ delay }};
            duration: {{ elapsed }};
            counter: {{ states('counter.motion_alpr_counter') -}}/{{- states('sensor.motion_alpr_counter') -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_alpr_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

## count
- platform: template
  sensors:
    motion_alpr_count:
      friendly_name: ALPR count
      unit_of_measurement: entities
      value_template: >
        {% if is_state('binary_sensor.motion_alpr','on') or is_state('binary_sensor.motion_alpr_expired','off') %}
          {% set count = state_attr('sensor.motion_event_alpr','count') %}
          {% if count is not none and count|lower != 'unknown' and count != 'null' %}
            {{ count|int }}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## entity_count
- platform: template
  sensors:
    motion_alpr_count_entity:
      friendly_name: ALPR count entity
      unit_of_measurement: entities
      value_template: >-
        {% if is_state('binary_sensor.motion_alpr','on') or is_state('binary_sensor.motion_alpr_expired','off') %}
          {% set detected = state_attr('sensor.motion_event_alpr','detected') %}
          {% if detected is not none and detected|lower != 'unknown' and detected != 'null' %}
            {% set count = detected|selectattr('entity','==',states('sensor.motion_detect_entity'))|map(attribute='count')|sum %}
            {% if count is not none and count|lower != 'unknown' and count != 'null' %}
              {{ count|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## counter
- platform: template
  sensors:
    motion_alpr_counter:
      friendly_name: ALPR counter
      unit_of_measurement: count
      value_template: >
        {{ states('counter.motion_alpr_counter')|int }}

## date
- platform: template
  sensors:
    # date
    motion_alpr_date:
      unit_of_measurement: seconds
      value_template: >-
        {% if is_state('binary_sensor.motion_alpr','on') or is_state('binary_sensor.motion_alpr_expired','off') %}
          {% set e = state_attr('sensor.motion_event_alpr','event') %}
          {% if e is mapping %}
            {% set s = e.end %}
            {% if s is not none and s|lower != 'unknown' and s != 'null' and s|int > 0 %}
              {{ s|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_alpr_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## when
- platform: template
  sensors:
    motion_alpr_when:
      friendly_name: ALPR at
      value_template: >-
        {% set s = states('sensor.motion_alpr_date')|int %}
        {% if s > 0 %}
          {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
        {% else %}never{% endif %}

## ago
- platform: template
  sensors:
    motion_alpr_ago:
      friendly_name: ALPR ago
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_alpr_date')|int %}
        {% if s > 0 %}
          {% set s = utcnow().timestamp()|int - s %}
          {% if s < 86400 %}{{ s }}{%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

## delay
- platform: template
  sensors:
    motion_alpr_delay:
      friendly_name: ALPR delay
      unit_of_measurement: seconds
      value_template: >
        {% set e = state_attr('sensor.motion_event_alpr','event') %}
        {% if e is mapping %}
          {% set s = e.end %}
          {% if s is not none and s|lower != 'unknown' and s != 'null' and s|int > 0 %}
            {{ utcnow().timestamp()|int - s|int }}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

## percent
- platform: template
  sensors:
    motion_alpr_percent:
      friendly_name: ALPR percent
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_alpr_counter')|int > 0 and states('sensor.motion_end_counter')|int > 0 %}
          {% set value = states.sensor.motion_alpr_counter.state|int / states.sensor.motion_end_counter.state|int * 100.0 %}
          {{ "%.2f"|format(value|float) }}
        {%- else -%}null{%- endif -%}

## device
- platform: template
  sensors:
    motion_alpr_device:
      friendly_name: ALPR device
      value_template: >-
        {% if state_attr('sensor.motion_event_alpr','event')|lower != 'none' %}
          {{ states.sensor.motion_event_alpr.attributes.event.device }}
        {% else %}null{% endif %}

## camera
- platform: template
  sensors:
    motion_alpr_camera:
      friendly_name: ALPR camera
      value_template: >-
        {% if state_attr('sensor.motion_event_alpr','event')|lower != 'none' %}
          {{ states.sensor.motion_event_alpr.attributes.event.camera }}
        {% else %}null{% endif %}

## snapshot
#- platform: template
#  sensors:
#    motion_alpr_snapshot:
#      friendly_name: ALPR snapshot
#      value_template: >-
#        {% set event = state_attr('sensor.motion_event_alpr','event') %}
#        {% if event is not none and event|lower != 'unknown' and event != 'null' %}
#          {% set ep = '/local/images/motion_alpr-' + event.camera + '.jpg' %}
#          {% set bu = states('sensor.motion_base_url') %}
#          {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
#            {% set p = bu + ep %}
#          {% endif %}
#        {% endif %}
#        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
#          {{ p }}
#        {% else %}
#          {{ states('sensor.motion_nosignal_picture') }}
#        {% endif %}

###
# statistics
###

## percent
- platform: template
  sensors:
    motion_alpr_percent_mean:
      friendly_name: ALPR percent avg
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_alpr_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_alpr_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_alpr_percent_min_value:
      friendly_name: ALPR percent min
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_alpr_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_alpr_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_alpr_percent_max_value:
      friendly_name: ALPR percent max
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_alpr_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_alpr_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_alpr_percent_stdev:
      friendly_name: ALPR percent stdev
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_alpr_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_alpr_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_alpr_percent_change:
      friendly_name: ALPR percent change
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_alpr_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_alpr_percent_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

- platform: statistics
  name: motion_alpr_percent_statistics
  entity_id: sensor.motion_alpr_percent
  sampling_size: 100
  max_age:
    hours: 72
