###
# sensor/motion/camera.yaml
###

## IDK if this will ever be used

- platform: template
  sensors:
    motion_detected_entity_camera_url:
      friendly_name: Detected entity camera URL 
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='netcam_url')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_userpass:
      friendly_name: Detected entity camera userpass
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='userpass')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_username:
      friendly_name: Detected entity camera username
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='username')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_password:
      friendly_name: Detected entity camera password
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='password')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_status_camera_counter:
      friendly_name: Camera found-lost
      entity_id:
        - sensor.motion_status_camera_lost_counter
        - sensor.motion_status_camera_found_counter
      value_template: >-
        {{ states('sensor.motion_status_camera_found_counter')|int - states('sensor.motion_status_camera_lost_counter')|int }}

### LOST

## counter
- platform: template
  sensors:
    motion_status_camera_lost_counter:
      friendly_name: Total lost counter
      entity_id:
        - counter.motion_status_camera_lost_counter
      unit_of_measurement: count
      value_template: >
        {% if states('counter.motion_status_camera_lost_counter') != 'unknown' %}
          {{ states('counter.motion_status_camera_lost_counter')|int }}
        {%- else -%}null{%- endif -%}

## counter
- platform: template
  sensors:
    motion_status_camera_lost_counter_mean:
      friendly_name: status_camera_lost counter avg
      entity_id:
        - sensor.motion_status_camera_lost_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_lost_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_lost_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_lost_counter_min_value:
      friendly_name: status_camera_lost counter min
      entity_id:
        - sensor.motion_status_camera_lost_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_lost_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_lost_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_lost_counter_max_value:
      friendly_name: status_camera_lost counter max
      entity_id:
        - sensor.motion_status_camera_lost_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_lost_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_lost_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_lost_counter_stdev:
      friendly_name: status_camera_lost counter stdev
      entity_id:
        - sensor.motion_status_camera_lost_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_status_camera_lost_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_lost_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}

# counter
- platform: statistics
  name: motion_status_camera_lost_counter_statistics
  entity_id: sensor.motion_status_camera_lost_counter
  sampling_size: 1000
  max_age:
    hours: 72

### FOUND

## counter
- platform: template
  sensors:
    motion_status_camera_found_counter:
      friendly_name: Total found counter
      entity_id:
        - counter.motion_status_camera_found_counter
      unit_of_measurement: count
      value_template: >
        {% if states('counter.motion_status_camera_found_counter') != 'unknown' %}
          {{ states('counter.motion_status_camera_found_counter')|int }}
        {%- else -%}null{%- endif -%}

## counter
- platform: template
  sensors:
    motion_status_camera_found_counter_mean:
      friendly_name: status_camera_found counter avg
      entity_id:
        - sensor.motion_status_camera_found_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_found_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_found_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_found_counter_min_value:
      friendly_name: status_camera_found counter min
      entity_id:
        - sensor.motion_status_camera_found_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_found_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_found_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_found_counter_max_value:
      friendly_name: status_camera_found counter max
      entity_id:
        - sensor.motion_status_camera_found_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_status_camera_found_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_found_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_status_camera_found_counter_stdev:
      friendly_name: status_camera_found counter stdev
      entity_id:
        - sensor.motion_status_camera_found_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_status_camera_found_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_status_camera_found_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}

# counter
- platform: statistics
  name: motion_status_camera_found_counter_statistics
  entity_id: sensor.motion_status_camera_found_counter
  sampling_size: 1000
  max_age:
    hours: 72
