###
# sensor/motion/camera.yaml
###

- platform: template
  sensors:
    motion_detected_entity_camera_url:
      friendly_name: Detected entity camera URL 
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='netcam_url')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_userpass:
      friendly_name: Detected entity camera userpass
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='userpass')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_username:
      friendly_name: Detected entity camera username
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='username')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_entity_camera_password:
      friendly_name: Detected entity camera password
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
        {% set camera = state_attr('sensor.motion_event_annotated','event').camera %}
        {% set value = state_attr('sensor.motion_device_start','cameras')|selectattr('name','==',camera)|map(attribute='password')|list|first %}
        {% if value is not none and value|lower != 'unknown' %}
          {{ value }}
        {% else %}null{% endif %}

