###
## sensor/motion/config.yaml
###

- platform: template
  sensors:
    motion_group:
      value_template: >-
        {% if states.input_text.motion_group is defined %}
          {{ states.input_text.motion_group.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_device:
      value_template: >-
        {% if states.input_text.motion_device is defined %}
          {{ states.input_text.motion_device.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_client:
      value_template: >-
        {% if states.input_text.motion_client is defined %}
          {{ states.input_text.motion_client.state }}
        {% else %}null{% endif %}


- platform: template
  sensors:
    motion_sensor_domain_count:
      friendly_name: '# sensor'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.sensor|length }}

- platform: template
  sensors:
    motion_camera_domain_count:
      friendly_name: '# camera'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.camera|length }}

- platform: template
  sensors:
    motion_domain_counter_domain_count:
      friendly_name: '# counter'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.counter|length }}

- platform: template
  sensors:
    motion_automations_domain_count:
      friendly_name: '# automation'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.automation|length }}

- platform: template
  sensors:
    motion_binary_sensor_domain_count:
      friendly_name: '# binary_sensor'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.binary_sensor|length }}

- platform: template
  sensors:
    motion_input_boolean_domain_count:
      friendly_name: '# input_boolean'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.input_boolean|length }}

- platform: template
  sensors:
    motion_input_number_domain_count:
      friendly_name: '# input_number'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.input_number|length }}

- platform: template
  sensors:
    motion_input_text_domain_count:
      friendly_name: '# input_text'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.input_text|length }}

- platform: template
  sensors:
    motion_input_select_domain_count:
      friendly_name: '# input_select'
      icon_templare: 'mdi:counter'
      unit_of_measurement: component
      value_template: >-
        {{ states.input_select|length }}
