###
## sensor/motion/config.yaml
###

- platform: template
  sensors:
    motion_group:
      entity_id:
        - input_text.motion_group
      value_template: >-
        {% if states.input_text.motion_group is defined %}
          {{ states.input_text.motion_group.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_client:
      entity_id:
        - input_text.motion_client
      value_template: >-
        {% if states.input_text.motion_client is defined %}
          {{ states.input_text.motion_client.state }}
        {% else %}null{% endif %}

