###
## sensor/motion/config.yaml
###

- platform: template
  sensors:
    motion_group:
      value_template: >-
        {% if states.input_text.motion_group is defined %}
          {{ states.input_text.motion_group.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_device:
      value_template: >-
        {% if states.input_text.motion_device is defined %}
          {{ states.input_text.motion_device.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_client:
      value_template: >-
        {% if states.input_text.motion_client is defined %}
          {{ states.input_text.motion_client.state }}
        {% else %}null{% endif %}


- platform: template
  sensors:
    motion_sensor_count:
      value_template: >-
        {{ states.sensor|length }}

- platform: template
  sensors:
    motion_camera_count:
      value_template: >-
        {{ states.camera|length }}

- platform: template
  sensors:
    motion_counter_count:
      value_template: >-
        {{ states.counter|length }}

- platform: template
  sensors:
    motion_automations_count:
      value_template: >-
        {{ states.automation|length }}

- platform: template
  sensors:
    motion_binary_sensor_count:
      value_template: >-
        {{ states.binary_sensor|length }}

- platform: template
  sensors:
    motion_input_boolean_count:
      value_template: >-
        {{ states.input_boolean|length }}

- platform: template
  sensors:
    motion_input_number_count:
      value_template: >-
        {{ states.input_number|length }}

- platform: template
  sensors:
    motion_input_text_count:
      value_template: >-
        {{ states.input_text|length }}

- platform: template
  sensors:
    motion_input_select_count:
      value_template: >-
        {{ states.input_select|length }}
