###
# homeassistant/sensor/motion/detected_animal.yaml
###

- platform: template
  sensors:
    motion_detected_animal_status:
      friendly_name: ANIMAL
      icon_template: 'mdi:cow'
      value_template: >-
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set n = utcnow().timestamp()|int %}
          {% set end = states('sensor.motion_detected_animal_date') %}
          {% set event = states('sensor.motion_detected_animal_event') %}
          {% set device = states('sensor.motion_detected_animal_device') %}
          {% set camera = states('sensor.motion_detected_animal_camera') %}
          {% set elapsed = states('sensor.motion_detected_animal_elapsed') %}
          {% set when = states('sensor.motion_detected_animal_when') %}
          {% set confidence = states('sensor.motion_detected_animal_confidence')|int %}
          {% set what = 'animal' %}
          {% set count = states('sensor.motion_detected_animal_count') %}
          {% set delay = n - end|int %}
          ANIMAL: {{ count }} {{ what }} @ {{ confidence -}}%;
          from {{ device -}}/{{- camera -}}/{{- event -}};
          at {{ when }};
          delay: {{ delay }};
          duration: {{ elapsed }};
          counter: {{ states('counter.motion_detected_animal_counter') -}}/{{- states('sensor.motion_detected_animal_counter') -}}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_camera_detected_animal_live:
      friendly_name: Animal camera live
      value_template: >-
        {% set camera = states('sensor.motion_detected_animal_camera') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% set ep = state_attr('camera.motion_live_' + camera,'entity_picture') %}
          {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}
 
# array of animal count
- platform: template
  sensors:
    motion_detected_animal:
      icon_template: 'mdi:counter'
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_animal','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','results') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for results in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if results.entity in options and results.confidence|int > states('sensor.motion_detected_animal_threshold')|int %}
                1
              {% else %}
                0
              {% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_threshold:
      friendly_name: Animal threshold
      unit_of_measurement: '%' 
      icon_template: 'mdi:percent'
      value_template: >-
        {{ states('input_number.motion_detected_animal_percent')|int }}

- platform: template
  sensors:
    motion_detected_animal_threshold_deviation:
      friendly_name: Animal threshold deviation
      unit_of_measurement: '%'
      icon_template: 'mdi:sigma-lower'
      value_template: >-
        {% set p = states('input_number.motion_detected_animal_percent_deviation')|float %}
        {% if p is not none and p|lower != 'unknown' and p|lower != 'none' and p|lower != 'unavailable' %}
          {{ states('input_number.motion_detected_animal_percent_deviation')|float }}
        {% else %}null{% endif %}
 
- platform: template
  sensors:
    motion_detected_animal_threshold_tune:
      friendly_name: Animal auto-threshold
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >-
        {% set m = states('sensor.motion_detected_animal_confidence_max_value')|float %}
        {% set d = states('sensor.motion_detected_animal_confidence_stdev')|float %}
        {% set p = states('sensor.motion_detected_animal_threshold_deviation')|float %}
        {% set n = ( m - p * d )|float %}
        {% set z = states('sensor.motion_detected_animal_threshold')|float %}
        {% if n > z %}{{ n|int }}{% else %}{{ z|int }}{% endif %}
 
# sum of animal entity count
- platform: template
  sensors:
    motion_detected_animal_count:
      friendly_name: Animal count
      unit_of_measurement: 'animal'
      icon_template: 'mdi:counter'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') or is_state('binary_sensor.motion_detected_animal_expired','off') %}
          {% set s = states('sensor.motion_detected_animal') %}
          {% if s|lower != 'unknown' and s|lower != none %}
            {% set s = s|from_json %}
            {% if s|lower != 'unknown' and s|lower != none and s is iterable %}
              {{ s|sum|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## sensor from counter

- platform: template
  sensors:
    motion_detected_animal_counter:
      unit_of_measurement: 'animal'
      value_template: >
        {{ states('counter.motion_detected_animal_counter') }}

## TODAY

- platform: history_stats
  name: motion_today_animal_ratio
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_animal_counter
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_animal_time
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: template
  sensors:
    motion_detected_animal_ratio_today:
      friendly_name: Today animal ratio
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >
        {{ states('sensor.motion_today_animal_ratio') }}

- platform: template
  sensors:
    motion_detected_animal_counter_today:
      friendly_name: Today animal counter
      unit_of_measurement: 'events'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states('sensor.motion_today_animal_counter')|int }}

- platform: template
  sensors:
    motion_detected_animal_time_today:
      friendly_name: Today animal time
      unit_of_measurement: 'hours'
      icon_template: 'mdi:timer-outline'
      value_template: >
        {{ states('sensor.motion_today_animal_time')|float }}

- platform: template
  sensors:
    motion_detected_animal_status_today:
      friendly_name: Today animal
      icon_template: 'mdi:cow'
      value_template: >-
        {% set c = states('sensor.motion_detected_animal_counter_today') %}
        {% set r = states('sensor.motion_detected_animal_ratio_today') %}
        {% set t = states('sensor.motion_detected_animal_time_today') %}
        {% if c|lower != 'unknown' and r|lower != 'unknown' and t|lower != 'unknown' %}
          {{ c -}}; {{ t }} hours; {{ r }}%
        {% else %}No animals detected today{% endif %}

- platform: template
  sensors:
    motion_detected_animal_confidence:
      friendly_name: Animal confidence
      icon_template: 'mdi:cow'
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','results') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|length > 0 %}
            {% set l = s|selectattr('entity','==','animal')|map(attribute='confidence')|list %}
            {% if l is not none and l|length > 0 %}
              {% set p = s|selectattr('entity','==','animal')|map(attribute='confidence')|max|int %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_confidence') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## confidence
- platform: template
  sensors:
    motion_detected_animal_confidence_mean:
      friendly_name: Animal confidence mean
      unit_of_measurement: '%'
      icon_template: 'mdi:sigma'
      value_template: >-
        {% if states('sensor.motion_detected_animal_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_animal_confidence_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_animal_confidence_min_value:
      friendly_name: Animal confidence min
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_animal_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_animal_confidence_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_animal_confidence_max_value:
      friendly_name: Animal confidence max
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_animal_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_animal_confidence_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_animal_confidence_stdev:
      friendly_name: Animal confidence stdev
      icon_template: 'mdi:sigma-lower'
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_animal_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_animal_confidence_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_animal_confidence_change:
      friendly_name: Animal confidence change
      unit_of_measurement: delta
      icon_template: 'mdi:delta'
      value_template: >
        {% if states('sensor.motion_detected_animal_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_animal_confidence_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

# confidence
- platform: statistics
  name: motion_detected_animal_confidence_statistics
  entity_id: sensor.motion_detected_animal_confidence
  sampling_size: 100
  max_age:
    hours: 72

- platform: template
  sensors:
    motion_detected_animal_event:
      friendly_name: Animal event
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.event %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_event') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_device:
      friendly_name: Animal device
      icon_template: 'mdi:raspberry-pi'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.device %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}


- platform: template
  sensors:
    motion_detected_animal_camera:
      friendly_name: Animal camera
      icon_template: 'mdi:camera'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.camera %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_elapsed:
      friendly_name: Animal elapsed
      icon_template: 'mdi:timer'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.elapsed %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_elapsed') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_date:
      friendly_name: Animal date
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.end %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_ago:
      friendly_name: Animal ago
      icon_template: 'mdi:camera-timer'
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_detected_animal_date') %}
        {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
          {{ as_timestamp(now())|int - s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_when:
      friendly_name: Animal when
      icon_template: 'mdi:calendar-clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = states('sensor.motion_detected_animal_date') %}
          {% if s|int > 0 %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_when') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}
