###
# homeassistant/sensor/motion/detected_person.yaml
###

# array of person count
- platform: template
  sensors:
    motion_detected_person:
      friendly_name: Detected person count
      icon_template: 'mdi:counter'
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_person','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

# sum of person entity count
- platform: template
  sensors:
    motion_detected_person_count:
      friendly_name: Count of person(s)
      unit_of_measurement: 'person'
      icon_template: 'mdi:account'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_person') %}
          {% if s|lower != 'unknown' and s|lower != none %}
            {% set s = s|from_json %}
            {% if s|lower != 'unknown' and s|lower != none and s is iterable %}
              {{ s|sum|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## sensor from counter

- platform: template
  sensors:
    motion_detected_person_counter:
      unit_of_measurement: 'person'
      value_template: >
        {{ states('counter.motion_detected_person_counter') }}

## TODAY

- platform: history_stats
  name: motion_today_person_ratio
  entity_id: binary_sensor.motion_detected_person
  state: 'on'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_person_counter
  entity_id: binary_sensor.motion_detected_person
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_person_time
  entity_id: binary_sensor.motion_detected_person
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: template
  sensors:
    motion_person_ratio_today:
      friendly_name: Today person ratio
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >
        {{ states('sensor.motion_today_person_ratio') }}

- platform: template
  sensors:
    motion_person_counter_today:
      friendly_name: Today person counter
      unit_of_measurement: 'events'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states('sensor.motion_today_person_counter')|int }}

- platform: template
  sensors:
    motion_person_time_today:
      friendly_name: Today person time
      unit_of_measurement: 'hours'
      icon_template: 'mdi:timer-outline'
      value_template: >
        {{ states('sensor.motion_today_person_time')|float }}

- platform: template
  sensors:
    motion_person_status_today:
      friendly_name: Today person
      icon_template: 'mdi:account'
      value_template: >-
        {% set c = states('sensor.motion_person_counter_today') %}
        {% set r = states('sensor.motion_person_ratio_today') %}
        {% set t = states('sensor.motion_person_time_today') %}
        {% if c|lower != 'unknown' and r|lower != 'unknown' and t|lower != 'unknown' %}
          {{ c -}}; {{ t }} hours; {{ r }}%
        {% else %}No persons detected today{% endif %}

- platform: template
  sensors:
    motion_person_event:
      friendly_name: Person event
      icon_template: 'mdi:clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_event') %}
          {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
            {{ s }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_event') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_person_device:
      friendly_name: Person device
      icon_template: 'mdi:map-marker'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_device') %}
          {% if s is not none and s|lower != 'unknown' and s|length > 0 %}
            {{ s }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}


- platform: template
  sensors:
    motion_person_camera:
      friendly_name: Person camera
      icon_template: 'mdi:map-marker'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_camera') %}
          {% if s is not none and s|lower != 'unknown' and s|length > 0 %}
            {{ s }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_person_elapsed:
      friendly_name: Person elapsed
      icon_template: 'mdi:timeer'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_elapsed') %}
          {% if s is not none and s|lower != 'unknown' and s|length > 0 %}
            {{ s }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_elapsed') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_person_date:
      friendly_name: Person date
      icon_template: 'mdi:clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_detected_date') %}
          {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
            {{ s }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_person_ago:
      friendly_name: Person last ago
      icon_template: 'mdi:timer-outline'
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_person_date') %}
        {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
          {{ as_timestamp(now())|int - s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_person_when:
      friendly_name: Person when
      icon_template: 'mdi:clock-outline'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_person','on') or is_state('binary_sensor.motion_detected_person_expired','off') %}
          {% set s = states('sensor.motion_person_date') %}
          {% if s|int > 0 %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_person_when') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_camera_detected_person_live:
      friendly_name: Detected person camera live
      value_template: >-
        {% set camera = states('sensor.motion_detected_person_camera') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% set ep = state_attr('camera.motion_live_' + camera,'entity_picture') %}
          {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}
