###
# homeassistant/sensor/motion/detected_vehicle.yaml
###

- platform: template
  sensors:
    motion_detected_vehicle_status:
      friendly_name: VEHICLE
      icon_template: 'mdi:car'
      value_template: >-
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set n = utcnow().timestamp()|int %}
          {% set end = states('sensor.motion_detected_vehicle_date') %}
          {% set event = states('sensor.motion_detected_vehicle_event') %}
          {% set device = states('sensor.motion_detected_vehicle_device') %}
          {% set camera = states('sensor.motion_detected_vehicle_camera') %}
          {% set elapsed = states('sensor.motion_detected_vehicle_elapsed') %}
          {% set when = states('sensor.motion_detected_vehicle_when') %}
          {% set confidence = states('sensor.motion_detected_vehicle_confidence')|int %}
          {% set what = 'vehicle' %}
          {% set count = states('sensor.motion_detected_vehicle_count') %}
          {% set delay = n - end|int %}
          VEHICLE: {{ count }} {{ what }} @ {{ confidence -}}%;
          from {{ device -}}/{{- camera -}}/{{- event -}};
          at {{ when }};
          delay: {{ delay }};
          duration: {{ elapsed }};
          counter: {{ states('counter.motion_detected_vehicle_counter') -}}/{{- states('sensor.motion_detected_vehicle_counter') -}}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_camera_detected_vehicle_live:
      friendly_name: Vehicle camera live
      value_template: >-
        {% set camera = states('sensor.motion_detected_vehicle_camera') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% set ep = state_attr('camera.motion_live_' + camera,'entity_picture') %}
          {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}
 
# array of vehicle count
- platform: template
  sensors:
    motion_detected_vehicle:
      icon_template: 'mdi:counter'
      value_template: >-
        {%- set options = state_attr('input_select.motion_detect_vehicle','options') -%}
        {%- if options is not none and options|lower != 'unknown' and options|length > 0 -%}
          {%- set array = state_attr('sensor.motion_event_annotated','results') -%}
          {%- if array is not none and array|lower != 'unknown' and array|length > 0 -%}
            {%- for results in array -%}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {%- if results.entity in options and results.confidence|int > states('sensor.motion_detected_vehicle_threshold')|int -%}
                1
              {%- else -%}
                0
              {%- endif -%}
              {%- if loop.last -%}]{%- endif -%}
            {%- endfor -%}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

- platform: template
  sensors:
    motion_detected_vehicle_threshold:
      friendly_name: Vehicle threshold
      unit_of_measurement: '%' 
      icon_template: 'mdi:percent'
      value_template: >-
        {% if is_state('input_boolean.motion_detected_vehicle_tune','off') %}
          {{ states('input_number.motion_detected_vehicle_percent')|int }}
        {% else %}
          {{ states('sensor.motion_detected_vehicle_threshold_tune') }}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_threshold_deviation:
      friendly_name: Vehicle threshold deviation
      unit_of_measurement: '%'
      icon_template: 'mdi:sigma-lower'
      value_template: >-
        {% set p = states('input_number.motion_detected_vehicle_percent_deviation')|float %}
        {% if p is not none and p|lower != 'unknown' and p|lower != 'none' and p|lower != 'unavailable' %}
          {{ states('input_number.motion_detected_vehicle_percent_deviation')|float }}
        {% else %}null{% endif %}
 
- platform: template
  sensors:
    motion_detected_vehicle_threshold_tune:
      friendly_name: Vehicle auto-threshold
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >-
        {% set m = states('sensor.motion_detected_vehicle_confidence_max_value')|float %}
        {% set d = states('sensor.motion_detected_vehicle_confidence_stdev')|float %}
        {% set p = states('sensor.motion_detected_vehicle_threshold_deviation')|float %}
        {% set n = ( m - p * d )|float %}
        {% set z = states('input_number.motion_detected_vehicle_percent')|float %}
        {% if n > z %}{{ n|int }}{% else %}{{ z|int }}{% endif %}
 
# sum of vehicle entity count
- platform: template
  sensors:
    motion_detected_vehicle_count:
      friendly_name: Vehicle count
      unit_of_measurement: 'vehicle'
      icon_template: 'mdi:counter'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') or is_state('binary_sensor.motion_detected_vehicle_expired','off') %}
          {% set s = states('sensor.motion_detected_vehicle') %}
          {% if s|lower != 'unknown' and s|lower != none %}
            {% set s = s|from_json %}
            {% if s|lower != 'unknown' and s|lower != none and s is iterable %}
              {{ s|sum|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## sensor from counter

- platform: template
  sensors:
    motion_detected_vehicle_counter:
      unit_of_measurement: 'vehicle'
      value_template: >
        {{ states('counter.motion_detected_vehicle_counter') }}

## TODAY

- platform: history_stats
  name: motion_today_vehicle_ratio
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_vehicle_counter
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_vehicle_time
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: template
  sensors:
    motion_detected_vehicle_ratio_today:
      friendly_name: Today vehicle ratio
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >
        {{ states('sensor.motion_today_vehicle_ratio') }}

- platform: template
  sensors:
    motion_detected_vehicle_counter_today:
      friendly_name: Today vehicle counter
      unit_of_measurement: 'events'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states('sensor.motion_today_vehicle_counter')|int }}

- platform: template
  sensors:
    motion_detected_vehicle_time_today:
      friendly_name: Today vehicle time
      unit_of_measurement: 'hours'
      icon_template: 'mdi:timer-outline'
      value_template: >
        {{ states('sensor.motion_today_vehicle_time')|float }}

- platform: template
  sensors:
    motion_detected_vehicle_status_today:
      friendly_name: Today vehicle
      icon_template: 'mdi:car'
      value_template: >-
        {% set c = states('sensor.motion_detected_vehicle_counter_today') %}
        {% set r = states('sensor.motion_detected_vehicle_ratio_today') %}
        {% set t = states('sensor.motion_detected_vehicle_time_today') %}
        {% if c|lower != 'unknown' and r|lower != 'unknown' and t|lower != 'unknown' %}
          {{ c -}}; {{ t }} hours; {{ r }}%
        {% else %}No vehicles detected today{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_confidence:
      friendly_name: Animal confidence
      icon_template: 'mdi:cow'
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','results') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|length > 0 %}
            {% set options = state_attr('input_select.motion_detect_vehicle','options') %}
            {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
              {% set l = s|selectattr('entity','in',options)|map(attribute='confidence')|list %}
              {% if l is not none and l|length > 0 %}
                {% set p = s|selectattr('entity','in',options)|map(attribute='confidence')|max|int %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_confidence') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## confidence
- platform: template
  sensors:
    motion_detected_vehicle_confidence_mean:
      friendly_name: Vehicle confidence mean
      unit_of_measurement: '%'
      icon_template: 'mdi:sigma'
      value_template: >-
        {% if states('sensor.motion_detected_vehicle_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_vehicle_confidence_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_vehicle_confidence_min_value:
      friendly_name: Vehicle confidence min
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_vehicle_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_vehicle_confidence_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_vehicle_confidence_max_value:
      friendly_name: Vehicle confidence max
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_vehicle_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_vehicle_confidence_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_vehicle_confidence_stdev:
      friendly_name: Vehicle confidence stdev
      icon_template: 'mdi:sigma-lower'
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_vehicle_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_vehicle_confidence_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_vehicle_confidence_change:
      friendly_name: Vehicle confidence change
      unit_of_measurement: delta
      icon_template: 'mdi:delta'
      value_template: >
        {% if states('sensor.motion_detected_vehicle_confidence_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_vehicle_confidence_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

# confidence
- platform: statistics
  name: motion_detected_vehicle_confidence_statistics
  entity_id: sensor.motion_detected_vehicle_confidence
  sampling_size: 100
  max_age:
    hours: 72

- platform: template
  sensors:
    motion_detected_vehicle_event:
      friendly_name: Vehicle event
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.event %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_event') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_device:
      friendly_name: Vehicle device
      icon_template: 'mdi:raspberry-pi'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.device %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}


- platform: template
  sensors:
    motion_detected_vehicle_camera:
      friendly_name: Vehicle camera
      icon_template: 'mdi:camera'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.camera %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_elapsed:
      friendly_name: Vehicle elapsed
      icon_template: 'mdi:timer'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.elapsed %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_elapsed') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_date:
      friendly_name: Vehicle date
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {% set p = s.end %}
          {% endif %}
        {% endif %}
        {% if p is defined %}
          {{ p }}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_ago:
      friendly_name: Vehicle ago
      icon_template: 'mdi:camera-timer'
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_detected_vehicle_date') %}
        {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
          {{ as_timestamp(now())|int - s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_when:
      friendly_name: Vehicle when
      icon_template: 'mdi:calendar-clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = states('sensor.motion_detected_vehicle_date') %}
          {% if s|int > 0 %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_when') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}
