###
# homeassistant/sensor/motion/detected_animal.yaml
###

- platform: template
  sensors:
    motion_detected_animal_status:
      friendly_name: ANIMAL
      icon_template: 'mdi:account'
      value_template: >-
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set n = utcnow().timestamp()|int %}
          {% set end = states('sensor.motion_detected_animal_date') %}
          {% set event = states('sensor.motion_detected_animal_event') %}
          {% set device = states('sensor.motion_detected_animal_device') %}
          {% set camera = states('sensor.motion_detected_animal_camera') %}
          {% set elapsed = states('sensor.motion_detected_animal_elapsed') %}
          {% set when = states('sensor.motion_detected_animal_when') %}
          {% set what = 'animal' %}
          {% set count = states('sensor.motion_detected_animal_count') %}
          {% set delay = n - end|int %}
          ANIMAL: {{ count }} {{ what }};
          from {{ device -}}/{{- camera -}}/{{- event -}};
          at {{ when }};
          delay: {{ delay }};
          duration: {{ elapsed }};
          counter: {{ states('counter.motion_detected_animal_counter') -}}/{{- states('sensor.motion_detected_animal_counter') -}}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_camera_detected_animal_live:
      friendly_name: Detected animal camera live
      value_template: >-
        {% set camera = states('sensor.motion_detected_animal_camera') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% set ep = state_attr('camera.motion_live_' + camera,'entity_picture') %}
          {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}
 
# array of animal count
- platform: template
  sensors:
    motion_detected_animal:
      friendly_name: Detected animal count
      icon_template: 'mdi:counter'
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_animal','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

# sum of animal entity count
- platform: template
  sensors:
    motion_detected_animal_count:
      friendly_name: Count of animal(s)
      unit_of_measurement: 'animal'
      icon_template: 'mdi:account'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = states('sensor.motion_detected_animal') %}
          {% if s|lower != 'unknown' and s|lower != none %}
            {% set s = s|from_json %}
            {% if s|lower != 'unknown' and s|lower != none and s is iterable %}
              {{ s|sum|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## sensor from counter

- platform: template
  sensors:
    motion_detected_animal_counter:
      unit_of_measurement: 'animal'
      value_template: >
        {{ states('counter.motion_detected_animal_counter') }}

## TODAY

- platform: history_stats
  name: motion_today_animal_ratio
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_animal_counter
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_animal_time
  entity_id: binary_sensor.motion_detected_animal
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: template
  sensors:
    motion_detected_animal_ratio_today:
      friendly_name: Today animal ratio
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >
        {{ states('sensor.motion_today_animal_ratio') }}

- platform: template
  sensors:
    motion_detected_animal_counter_today:
      friendly_name: Today animal counter
      unit_of_measurement: 'events'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states('sensor.motion_today_animal_counter')|int }}

- platform: template
  sensors:
    motion_detected_animal_time_today:
      friendly_name: Today animal time
      unit_of_measurement: 'hours'
      icon_template: 'mdi:timer-outline'
      value_template: >
        {{ states('sensor.motion_today_animal_time')|float }}

- platform: template
  sensors:
    motion_detected_animal_status_today:
      friendly_name: Today animal
      icon_template: 'mdi:account'
      value_template: >-
        {% set c = states('sensor.motion_detected_animal_counter_today') %}
        {% set r = states('sensor.motion_detected_animal_ratio_today') %}
        {% set t = states('sensor.motion_detected_animal_time_today') %}
        {% if c|lower != 'unknown' and r|lower != 'unknown' and t|lower != 'unknown' %}
          {{ c -}}; {{ t }} hours; {{ r }}%
        {% else %}No animals detected today{% endif %}

- platform: template
  sensors:
    motion_detected_animal_event:
      friendly_name: Animal event
      icon_template: 'mdi:clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.event }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_event') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_device:
      friendly_name: Animal device
      icon_template: 'mdi:map-marker'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.device }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}


- platform: template
  sensors:
    motion_detected_animal_camera:
      friendly_name: Animal camera
      icon_template: 'mdi:map-marker'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.camera }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_elapsed:
      friendly_name: Animal elapsed
      icon_template: 'mdi:timeer'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.elapsed }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_elapsed') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_date:
      friendly_name: Animal date
      icon_template: 'mdi:clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.date }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_animal_ago:
      friendly_name: Animal last ago
      icon_template: 'mdi:timer-outline'
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_detected_animal_date') %}
        {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
          {{ as_timestamp(now())|int - s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_when:
      friendly_name: Animal when
      icon_template: 'mdi:clock-outline'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_animal','on') %}
          {% set s = states('sensor.motion_detected_animal_date') %}
          {% if s|int > 0 %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_animal_when') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}
