###
# homeassistant/sensor/motion/detected_vehicle.yaml
###

- platform: template
  sensors:
    motion_detected_vehicle_status:
      friendly_name: VEHICLE
      icon_template: 'mdi:car'
      value_template: >-
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set n = utcnow().timestamp()|int %}
          {% set end = states('sensor.motion_detected_vehicle_date') %}
          {% set event = states('sensor.motion_detected_vehicle_event') %}
          {% set device = states('sensor.motion_detected_vehicle_device') %}
          {% set camera = states('sensor.motion_detected_vehicle_camera') %}
          {% set elapsed = states('sensor.motion_detected_vehicle_elapsed') %}
          {% set when = states('sensor.motion_detected_vehicle_when') %}
          {% set what = 'vehicle' %}
          {% set count = states('sensor.motion_detected_vehicle_count') %}
          {% set delay = n - end|int %}
          VEHICLE: {{ count }} {{ what }};
          from {{ device -}}/{{- camera -}}/{{- event -}};
          at {{ when }};
          delay: {{ delay }};
          duration: {{ elapsed }};
          counter: {{ states('counter.motion_detected_vehicle_counter') -}}/{{- states('sensor.motion_detected_vehicle_counter') -}}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_camera_detected_vehicle_live:
      friendly_name: Detected vehicle camera live
      value_template: >-
        {% set camera = states('sensor.motion_detected_vehicle_camera') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% set ep = state_attr('camera.motion_live_' + camera,'entity_picture') %}
          {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}
 
# array of vehicle count
- platform: template
  sensors:
    motion_detected_vehicle:
      friendly_name: Detected vehicle count
      icon_template: 'mdi:counter'
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_vehicle','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

# sum of vehicle entity count
- platform: template
  sensors:
    motion_detected_vehicle_count:
      friendly_name: Count of vehicle(s)
      unit_of_measurement: 'vehicle'
      icon_template: 'mdi:counter'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = states('sensor.motion_detected_vehicle') %}
          {% if s|lower != 'unknown' and s|lower != none %}
            {% set s = s|from_json %}
            {% if s|lower != 'unknown' and s|lower != none and s is iterable %}
              {{ s|sum|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

## sensor from counter

- platform: template
  sensors:
    motion_detected_vehicle_counter:
      unit_of_measurement: 'vehicle'
      value_template: >
        {{ states('counter.motion_detected_vehicle_counter') }}

## TODAY

- platform: history_stats
  name: motion_today_vehicle_ratio
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_vehicle_counter
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: motion_today_vehicle_time
  entity_id: binary_sensor.motion_detected_vehicle
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: template
  sensors:
    motion_detected_vehicle_ratio_today:
      friendly_name: Today vehicle ratio
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >
        {{ states('sensor.motion_today_vehicle_ratio') }}

- platform: template
  sensors:
    motion_detected_vehicle_counter_today:
      friendly_name: Today vehicle counter
      unit_of_measurement: 'events'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states('sensor.motion_today_vehicle_counter')|int }}

- platform: template
  sensors:
    motion_detected_vehicle_time_today:
      friendly_name: Today vehicle time
      unit_of_measurement: 'hours'
      icon_template: 'mdi:timer-outline'
      value_template: >
        {{ states('sensor.motion_today_vehicle_time')|float }}

- platform: template
  sensors:
    motion_detected_vehicle_status_today:
      friendly_name: Today vehicle
      icon_template: 'mdi:car'
      value_template: >-
        {% set c = states('sensor.motion_detected_vehicle_counter_today') %}
        {% set r = states('sensor.motion_detected_vehicle_ratio_today') %}
        {% set t = states('sensor.motion_detected_vehicle_time_today') %}
        {% if c|lower != 'unknown' and r|lower != 'unknown' and t|lower != 'unknown' %}
          {{ c -}}; {{ t }} hours; {{ r }}%
        {% else %}No vehicles detected today{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_event:
      friendly_name: Vehicle event
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.event }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_event') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_device:
      friendly_name: Vehicle device
      icon_template: 'mdi:raspberry-pi'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.device }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}


- platform: template
  sensors:
    motion_detected_vehicle_camera:
      friendly_name: Vehicle camera
      icon_template: 'mdi:camera'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.camera }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_elapsed:
      friendly_name: Vehicle elapsed
      icon_template: 'mdi:timer'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.elapsed }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_elapsed') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_date:
      friendly_name: Vehicle date
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = state_attr('sensor.motion_event_annotated','event') %}
          {% if s is not none and s is mapping %}
            {{ s.date }}
          {% else %}null{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_ago:
      friendly_name: Vehicle last ago
      icon_template: 'mdi:camera-timer'
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_detected_vehicle_date') %}
        {% if s is not none and s|lower != 'unknown' and s|int > 0 %}
          {{ as_timestamp(now())|int - s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_when:
      friendly_name: Vehicle when
      icon_template: 'mdi:calendar-clock'
      value_template: >
        {% if is_state('binary_sensor.motion_detected_vehicle','on') %}
          {% set s = states('sensor.motion_detected_vehicle_date') %}
          {% if s|int > 0 %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_detected_vehicle_when') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'none' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}
