###
# homeassistant/sensor/motion/detected_person.yaml
###

- platform: template
  sensors:
    motion_detected_person:
      friendly_name: Detected person
      entity_id:
        - counter.motion_detected_counter
        - sensor.motion_detected_ago
      value_template: >-
        {% set options = state_attr('input_select.motion_detect_person','options') %}
        {% if options is not none and options|lower != 'unknown' and options|length > 0 %}
          {% set array = state_attr('sensor.motion_event_annotated','detected') %}
          {% if array is not none and array|lower != 'unknown' and array|length > 0 %}
            {% for detected in array %}
              {%- if loop.first -%}[{%- else -%},{%- endif -%}
              {% if detected.entity in options %}{{ detected.count }}{% else %}0{% endif %}
              {%- if loop.last -%}]{%- endif -%}
            {% endfor %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}
