###
## homeassistant/sensor/motion/device_ipaddr.yaml
###

- platform: template
  sensors:
    ## entity selected from input_select.motion_detect_entity (e.g. 'person')
    motion_device_ipaddr:
      friendly_name: Device IP address
      icon_template: 'mdi:raspberry-pi'
      value_template: >-
        {% if states.input_select.motion_device_ipaddr is defined %}
          {{ states.input_select.motion_device_ipaddr.state }}
        {% else %}null{% endif %}
