
## human readable
- platform: template
  sensors:
    motion_end_status:
      friendly_name: Movement 
      entity_id:
        - counter.motion_end_counter
      value_template: >-
        {% set e = state_attr('sensor.motion_event_end','group') %}
        {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
          {% set n = utcnow().timestamp()|int %}
          {% set end = state_attr('sensor.motion_event_end','end') %}
          {% set event = state_attr('sensor.motion_event_end','event') %}
          {% set camera = state_attr('sensor.motion_event_end','camera') %}
          {% set device = state_attr('sensor.motion_event_end','device') %}
          {% set elapsed = state_attr('sensor.motion_event_end','elapsed')|int %}
          {% set ago = n - end %}
          {% set when = end|timestamp_custom("%a %b %d %I:%M:%S %p %Z") %}
          MOVEMENT: {{ count }} {{ what }};
          from {{ device -}}/{{- camera -}}/{{- event -}};
          at {{ when }};
          ago: {{ ago }};
          duration: {{ elapsed }};
          counter: {{ states('counter.motion_end_counter') -}}/{{- states('sensor.motion_end_counter') -}}
        {% else %}
          {% set s = states('sensor.motion_end_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO PRIOR STATUS{% endif %}
        {% endif %}

## timing
- platform: template
  sensors:
    motion_end_date:
      entity_id:
        - sensor.motion_event_end
      unit_of_measurement: seconds
      value_template: >-
        {% set date = state_attr('sensor.motion_event_end','date')|int %}
        {% if date  > 0 %} {{ date }} {%- else -%}null{%- endif -%}

# human readable
- platform: template
  sensors:
    motion_end_when:
      entity_id:
        - sensor.motion_end_date
      value_template: >
        {% set s = states('sensor.motion_end_date')|int %}
        {% if s > 0 %}
          {% set n = now().timestamp() %}
          {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}; {{ (n|int-s)|int }} ago
        {% else %}never{% endif %}

# seconds ago
- platform: template
  sensors:
    motion_end_ago:
      friendly_name: End ago
      entity_id:
        - sensor.motion_end_date
        - sensor.time
      unit_of_measurement: seconds
      value_template: >
        {% set s = states('sensor.motion_end_date')|int %}
        {% if s > 0 %}
          {% set s = utcnow().timestamp()|int - s %}
          {% if s < 86400 %}{{ s }}{%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}

# seconds elapsed
- platform: template
  sensors:
    motion_end_elapsed:
      entity_id:
        - sensor.motion_event_end
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_event_end|lower != 'none'
              and state_attr('sensor.motion_event_end','elapsed')|lower != 'none' %}
          {{ states.sensor.motion_event_end.attributes.elapsed|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_end_counter:
      friendly_name: Total movements
      entity_id:
        - counter.motion_end_counter
      unit_of_measurement: count
      value_template: >
        {{ states('counter.motion_end_counter')|int }}

- platform: template
  sensors:
    motion_end_device:
      entity_id:
        - sensor.motion_event_end
      value_template: >
        {% if states.sensor.motion_event_end|lower != 'none'
              and state_attr('sensor.motion_event_end','device')|lower != 'none' %}
          {{ states.sensor.motion_event_end.attributes.device }}
        {% else %} null {% endif %}

- platform: template
  sensors:
    motion_end_camera:
      entity_id:
        - sensor.motion_event_end
      value_template: >
        {% if states.sensor.motion_event_end|lower != 'none'
              and state_attr('sensor.motion_event_end','camera')|lower != 'none' %}
          {{ states.sensor.motion_event_end.attributes.camera }}
        {% else %} null {% endif %}

- platform: template
  sensors:
    motion_end_image_count:
      entity_id:
        - sensor.motion_event_end
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_event_end|lower != 'none'
              and state_attr('sensor.motion_event_end','images')|lower != 'none' %}
          {{ states.sensor.motion_event_end.attributes.images | length }}
        {% else %} null {% endif %}

## snapshot
- platform: template
  sensors:
    motion_end_snapshot:
      friendly_name: End snapshot
      entity_id:
        - sensor.motion_event_end
      value_template: >-
        {% set c = state_attr('sensor.motion_event_end','camera') %}
        {% if c is not none and c|lower != 'unknown' and c|length > 0 %}
          {% set ep = '/local/images/motion_end-' + c + '.jpg' %}
        {% else %}
          {% set ep = '/local/images/motion_end.jpg' %}
        {% endif %}
        {% set bu = states('sensor.motion_base_url') %}
        {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
          {% set p = bu + ep %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

#- platform: template
#  sensors:
#    motion_end_picture:
#      friendly_name: End picture
#      entity_id:
#        - counter.motion_end_counter
#      value_template: >-
#        {% set ep = state_attr('camera.motion_event_end','entity_picture') %}
#        {% if ep is not none and ep|lower != 'unknown' and ep|length > 0 %}
#          {% set bu = states('sensor.motion_base_url') %}
#          {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
#            {% set p = bu + ep %}
#          {% endif %}
#        {% else %}
#          {% set p = states('sensor.motion_noisesignal_picture') %}
#        {% endif %}
#        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
#          {{ p }}
#        {% else %}
#          {{ states('sensor.motion_nosignal_picture') }}
#        {% endif %}

##
# statistics
##

## ago
- platform: template
  sensors:
    motion_end_ago_mean:
      entity_id:
        - sensor.motion_end_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_ago_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_ago_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_end_ago_min_value:
      entity_id:
        - sensor.motion_end_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_ago_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_ago_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_ago_max_value:
      entity_id:
        - sensor.motion_end_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_ago_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_ago_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_ago_stdev:
      entity_id:
        - sensor.motion_end_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_ago_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_end_ago_change:
      entity_id:
        - sensor.motion_end_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_ago_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_ago_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

- platform: template
  sensors:
    motion_end_elapsed_mean:
      entity_id:
        - sensor.motion_end_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_elapsed_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_elapsed_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_end_elapsed_min_value:
      entity_id:
        - sensor.motion_end_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_elapsed_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_elapsed_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_elapsed_max_value:
      entity_id:
        - sensor.motion_end_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_elapsed_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_elapsed_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_elapsed_stdev:
      entity_id:
        - sensor.motion_end_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_elapsed_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_elapsed_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_end_elapsed_change:
      entity_id:
        - sensor.motion_end_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_end_elapsed_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_elapsed_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## counter
# count derived
- platform: template
  sensors:
    motion_end_counter_mean:
      entity_id:
        - sensor.motion_end_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_end_counter_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_end_counter_min_value:
      entity_id:
        - sensor.motion_end_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_end_counter_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_counter_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_counter_max_value:
      entity_id:
        - sensor.motion_end_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_end_counter_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_counter_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_end_counter_stdev:
      entity_id:
        - sensor.motion_end_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_end_counter_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_end_counter_change:
      entity_id:
        - sensor.motion_end_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_end_counter_statistics|lower != 'none' %}
          {{ states.sensor.motion_end_counter_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}

## statistics

# seconds ago
- platform: statistics
  name: motion_end_ago_statistics
  entity_id: sensor.motion_end_ago
  sampling_size: 1000
  max_age:
    hours: 72
- platform: statistics
  name: motion_end_ago_stdev_statistics
  entity_id: sensor.motion_end_ago_stdev
  sampling_size: 1000
  max_age:
    hours: 72

# counting events
- platform: statistics
  name: motion_end_counter_statistics
  entity_id: sensor.motion_end_counter
  sampling_size: 1000
  max_age:
    hours: 72
- platform: statistics
  name: motion_end_counter_stdev_statistics
  entity_id: sensor.motion_end_counter_stdev
  sampling_size: 1000
  max_age:
    hours: 72

# seconds elapsed
- platform: statistics
  name: motion_end_elapsed_statistics
  entity_id: sensor.motion_end_elapsed
  sampling_size: 1000
  max_age:
    hours: 72
- platform: statistics
  name: motion_end_elapsed_stdev_statistics
  entity_id: sensor.motion_end_elapsed_stdev
  sampling_size: 1000
  max_age:
    hours: 72
