- platform: template
  sensors:
    motion_mqtt_broker:
      friendly_name: MQTT broker
      entity_id:
        - input_text.motion_mqtt_broker
      value_template: >
        {{ states('input_text.motion_mqtt_broker') }}

- platform: template
  sensors:
    motion_mqtt_port:
      friendly_name: MQTT port
      entity_id:
        - input_text.motion_mqtt_port
      value_template: >
        {{ states('input_text.motion_mqtt_port')|int }}
