
# picture
- platform: template
  sensors:
    motion_overview_picture:
      friendly_name: Overview
      icon_template: 'mdi:view-dashboard-variant-outline'
      value_template: >-
          {% if states.sensor.motion_base_url|lower != 'none' and states.sensor.motion_base_url.state != 'unknown' %}
            {{ states.sensor.motion_base_url.state + '/local/images/overview.jpg' }}
          {% else %}{{ null }}{% endif %}
 
# animated
- platform: template
  sensors:
    motion_overview_animated:
      friendly_name: Overview animated
      icon_template: 'mdi:view-dashboard-variant'
      value_template: >-
          {% if states.sensor.motion_base_url|lower != 'none' and states.sensor.motion_base_url.state != 'unknown' %}
            {{ states.sensor.motion_base_url.state + '/local/images/overview.gif' }}
          {% else %}{{ null }}{% endif %}
