###
# person_face
###

## snapshot
- platform: template
  sensors:
    motion_detected_person_face_snapshot:
      friendly_name: Detected person face snapshot
      entity_id:
        - counter.motion_detected_person_face_counter
      value_template: >-
        {% set event = state_attr('sensor.motion_event_face','event') %}
        {% if event is not none and event|lower != 'unknown' and event != 'null' %}
          {% set ep = '/local/images/motion_detected_person_face-' + event.camera + '.jpg' %}
          {% set bu = states('sensor.motion_base_url') %}
          {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
            {% set p = bu + ep %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

- platform: template
  sensors:
    motion_detected_person_face_picture:
      friendly_name: Person face picture
      entity_id:
        - counter.motion_person_face_counter
      value_template: >-
        {% set ep = state_attr('camera.motion_event_face','entity_picture') %}
        {% if ep is not none and ep|lower != 'unknown' and ep|length > 0 %}
          {% set bu = states('sensor.motion_base_url') %}
          {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
            {% set p = bu + ep %}
          {% endif %}
        {% else %}
          {% set p = states('sensor.motion_noisesignal_picture') %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}
