###
## homeassistant/sensor/motion/selected.yaml
###

- platform: template
  sensors:
    motion_camera_name_selected:
      friendly_name: Selected camera name
      entity_id:
        - input_select.motion_camera_name
      value_template: >-
        {{ states('input_select.motion_camera_name') }}

- platform: template
  sensors:
    motion_camera_selected:
      friendly_name: Selected camera picture
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set event = state_attr('sensor.motion_event_annotated','event') %}
            {% if event is not none and event|lower != 'unknown' and event != 'null' %}
              {% set c = event.camera %}
            {% endif %}
          {% elif selected in state_attr('input_select.motion_camera_name','options') %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected_entity-' + c + '.jpg' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_animated:
      friendly_name: Selected camera picture
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set event = state_attr('sensor.motion_event_annotated','event') %}
            {% if event is not none and event|lower != 'unknown' and event != 'null' %}
              {% set c = event.camera %}
            {% endif %}
          {% elif selected in state_attr('input_select.motion_camera_name','options') %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected_entity-' + c + '.gif' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}
