###
## homeassistant/sensor/motion/selected.yaml
###


- platform: template
  sensors:
    motion_camera_name_selected:
      friendly_name: Selected camera name
      entity_id:
        - input_select.motion_camera_name
      value_template: >-
        {% set camera = states('input_select.motion_camera_name') %}
        {% if camera == 'latest' %}
          {% set event = state_attr('sensor.motion_event_annotated','event') %}
          {% if event is not none and event|lower != 'unavailable' and event|lower != 'unknown' and event != 'null' %}
            {% set c = event.camera %}
          {% endif %}
        {% else %}
          {% set c = camera %}
        {% endif %}
        {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
          {{ c }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_camera_selected_live:
      friendly_name: Selected camera live
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set camera = states('sensor.motion_camera_name_selected') %}
        {% if camera is not none and camera|lower != 'unavailable' and camera|lower != 'unknown' and camera != 'null' and camera|length > 0 %}
          {% if camera == 'latest' %}
            {% set event = state_attr('sensor.motion_event_annotated','event') %}
            {% if event is not none and event|lower != 'unavailable' and event|lower != 'unknown' and event != 'null' %}
              {% set c = event.camera %}
            {% endif %}
          {% else %}
            {% set c = camera %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = state_attr('camera.motion_live_' + c,'entity_picture') %}
            {% if ep is not none and ep|lower != 'unknown' and ep|lower != 'unavailable' and ep|length > 0 %}
              {% set bu = states('sensor.motion_base_url') %}
              {% if bu is not none and bu|lower != 'unknown' and bu|lower != 'unavailable' and bu|length > 0 %}
                {% set p = bu + ep %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unavailable' and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_animated') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_annotated:
      friendly_name: Selected camera annotated
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set event = state_attr('sensor.motion_event_annotated','event') %}
            {% if event is not none and event|lower != 'unavailable' and event|lower != 'unknown' and event != 'null' %}
              {% set c = event.camera %}
            {% endif %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_annotated-' + c + '.jpg' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_detected:
      friendly_name: Selected camera detected
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set c = states('sensor.motion_detected_camera') %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected-' + c + '.jpg' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_detected_entity:
      friendly_name: Selected camera detected_entity
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set c = states('sensor.motion_detected_entity_camera') %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected_entity-' + c + '.jpg' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_animated_annotated:
      friendly_name: Selected camera animated annotated
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set event = state_attr('sensor.motion_event_annotated','event') %}
            {% if event is not none and event|lower != 'unavailable' and event|lower != 'unknown' and event != 'null' %}
              {% set c = event.camera %}
            {% endif %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_annotated-' + c + '.gif' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_testsignal_animated') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_animated_detected:
      friendly_name: Selected camera animated detected
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set c = states('sensor.motion_detected_camera') %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected-' + c + '.gif' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_testsignal_animated') }}
        {% endif %}

- platform: template
  sensors:
    motion_camera_selected_animated_detected_entity:
      friendly_name: Selected camera animated detected_entity
      entity_id:
        - sensor.motion_camera_name_selected
      value_template: >-
        {% set selected = states('sensor.motion_camera_name_selected') %}
        {% if selected is not none and selected|lower != 'unknown' and selected != 'null' and selected|length > 0 %}
          {% if selected == 'latest' %}
            {% set c = states('sensor.motion_detected_entity_camera') %}
          {% else %}
            {% set c = selected %}
          {% endif %}
          {% if c is defined and c is not none and c|lower != 'unavailable' and c|lower != 'unknown' and c|length > 0 %}
            {% set ep = '/local/images/motion_detected_entity-' + c + '.gif' %}
            {% set bu = states('sensor.motion_base_url') %}
            {% if bu is not none and bu|lower != 'unknown' and bu|length > 0 %}
              {% set p = bu + ep %}
            {% endif %}
          {% endif %}
        {% endif %}
        {% if p is defined and p is not none and p|lower != 'unknown' and p|length > 0 %}
          {{ p }}
        {% else %}
          {{ states('sensor.motion_testsignal_animated') }}
        {% endif %}
