###
# homeassistant/sensor/motion/switch.yaml
###

- platform: template
  sensors:
    motion_switch_status_array:
      friendly_name: Switch states
      unit_of_measurement: 'switch'
      value_template: >-
        [{%- for state in states.switch -%}
          {%- if loop.first -%}{%- else -%},{%- endif -%}
          {%- set s = state.state_with_unit|lower -%}
          {%- if s == 'on' or s == 'off' -%}1{%- else -%}0{%- endif -%}
        {%- endfor -%}]

- platform: template
  sensors:
    motion_switch_count:
      friendly_name: Switch count
      icon_template: 'mdi:counter'
      unit_of_measurement: 'switch'
      value_template: >-
        {{ states('sensor.motion_switch_status_array')|from_json|length }}

- platform: template
  sensors:
    motion_switch_count_on:
      friendly_name: Switch on count
      icon_template: 'mdi:counter'
      unit_of_measurement: 'switch'
      value_template: >-
        {{ states('sensor.motion_switch_status_array')|from_json|sum }}

- platform: template
  sensors:
    motion_switch_count_off:
      friendly_name: Switch off count
      icon_template: 'mdi:counter'
      unit_of_measurement: 'switch'
      value_template: >-
        {{ states('sensor.motion_switch_count')|int - states('sensor.motion_switch_count_on')|int  }}

- platform: template
  sensors:
    motion_switch_percent:
      friendly_name: Switch percent
      icon_template: 'mdi:light-switch'
      unit_of_measurement: '%'
      value_template: >-
        {% set c = states('sensor.motion_switch_count')|int %}
        {% if c > 0 %}
          {% set o = states('sensor.motion_switch_count_on')|int %}
          {{ (o / c * 100)|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_switch_status:
      friendly_name: Switch status 
      icon_template: 'mdi:light-switch'
      value_template: >-
        {{ states('sensor.motion_switch_count_on') -}}/{{- states('sensor.motion_switch_count') -}};
        {{ states('sensor.motion_switch_percent') -}}%

# percent statistics

- platform: statistics
  name: motion_switch_percent_statistics
  entity_id: sensor.motion_switch_percent
  sampling_size: 100
  max_age:
    hours: 72

- platform: template
  sensors:
    motion_switch_percent_mean:
      friendly_name: Person confidence mean
      unit_of_measurement: '%'
      icon_template: 'mdi:sigma'
      value_template: >-
        {% if states('sensor.motion_switch_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_switch_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_switch_percent_min_value:
      friendly_name: Person confidence min
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_switch_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_switch_percent_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_switch_percent_max_value:
      friendly_name: Person confidence max
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_switch_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_switch_percent_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_switch_percent_stdev:
      friendly_name: Person confidence stdev
      icon_template: 'mdi:sigma-lower'
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_switch_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_switch_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_switch_percent_change:
      friendly_name: Person confidence change
      unit_of_measurement: delta
      icon_template: 'mdi:delta'
      value_template: >
        {% if states('sensor.motion_switch_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_switch_percent_statistics.attributes.change|float }}
        {%- else -%}null{%- endif -%}
