###
# homeassistant/sensor/motion/switch.yaml
###

- platform: template
  sensors:
    motion_switch_states:
      friendly_name: Switch states
      icon_template: 'mdi:light-switch'
      value_template: >-
       [{% for state in states.switch -%}
         {%- if loop.first %}{% else %},{% endif %}
         {% set s = state.state_with_unit|lower %}
         {% if s == 'on' %}1{% elif s == 'off' %}0{% else %}null{% endif %}
       {%- endfor %}]

- platform: template
  sensors:
    motion_switch_names:
      friendly_name: Switch names
      icon_template: 'mdi:light-switch'
      value_template: >-
       [{% for state in states.switch -%}
         {%- if loop.first %}{% else %},{% endif %}
         {% set n = state.name|lower %}
         "{{ n }}"
       {%- endfor %}]
