###
# vehicle_alpr
###

## human readable status
- platform: template
  sensors:
    motion_vehicle_alpr_status:
      friendly_name: Detected_entity status
      value_template: >-
        {% if is_state('binary_sensor.motion_vehicle_alpr_detected','on') %}
          {% set e = state_attr('sensor.motion_event_annotated','event') %}
          {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
            {% set n = utcnow().timestamp()|int %}
            {% set end = e.end|int %}
            {% set event = e.event %}
            {% set device = e.device %}
            {% set camera = e.camera %}
            {% set elapsed = e.elapsed|int %}
            {% set what = state_attr('sensor.motion_event_annotated','detected') %}
            {% if what is none or what|lower == 'unknown' or what|length == 0 %}{% set what = 'nothing' %}{% endif %}
            {% set count = state_attr('sensor.motion_event_alpr','count')|int %}
            {% set when = end|timestamp_custom("%a %b %d %I:%M:%S %p %Z") %}
            {% set delay = n - end %}
            PERSON FACE DETECTED: {{ count }} {{ what }};
            from {{ device -}}/{{- camera -}}/{{- event -}};
            at {{ when }};
            delay: {{ delay }};
            duration: {{ elapsed }};
            counter: {{ states('counter.motion_alpr_detected_counter') -}}/{{- states('sensor.motion_alpr_detected_counter') -}}
          {% else %}Never{% endif %}
        {% else %}
          {% set s = states('sensor.motion_vehicle_alpr_status') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}NO STATUS{% endif %}
        {% endif %}

## counter
- platform: template
  sensors:
    motion_vehicle_alpr_counter:
      friendly_name: vehicle alpr counter
      unit_of_measurement: count
      value_template: >
        {% set value = states('counter.motion_vehicle_alpr_counter') %}
        {% if value|lower != 'unavailable' and value|lower != 'unknown' %}
          {{ value|int }}
        {% else %}null{% endif %}

## device
- platform: template
  sensors:
    # device
    motion_vehicle_alpr_device:
      friendly_name: Detected_entity device
      value_template: >-
        {% if is_state('binary_sensor.motion_vehicle_alpr_detected','on') %}
          {% set e = state_attr('sensor.motion_event_alpr','event') %}
          {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
            {% set s = e.device %}
            {% if s is not none and s|lower != 'unknown' and s != 'null' and s|int > 0 %}
              {{ s }}
            {%- else -%}null{%- endif -%}
          {%- else -%}null{%- endif -%}
        {% else %}
          {% set s = states('sensor.motion_vehicle_alpr_device') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## camera
- platform: template
  sensors:
    motion_vehicle_alpr_camera:
      friendly_name: Detected_entity camera
      value_template: >-
        {% if is_state('binary_sensor.motion_vehicle_alpr_detected','on') %}
          {% set e = state_attr('sensor.motion_event_alpr','event') %}
          {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
            {% set s = e.camera %}
            {% if s is not none and s|lower != 'unknown' and s != 'null' and s|int > 0 %}
              {{ s }}
            {%- else -%}null{%- endif -%}
          {%- else -%}null{%- endif -%}
        {% else %}
          {% set s = states('sensor.motion_vehicle_alpr_camera') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## date
- platform: template
  sensors:
    motion_vehicle_alpr_date:
      unit_of_measurement: seconds
      value_template: >-
        {% if is_state('binary_sensor.motion_vehicle_alpr_detected','on') %}
          {% set e = state_attr('sensor.motion_event_alpr','event') %}
          {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
            {% set s = e.end %}
            {% if s is not none and s|lower != 'unknown' and s != 'null' and s|int > 0 %}
              {{ s|int }}
            {%- else -%}null{%- endif -%}
          {%- else -%}null{%- endif -%}
        {% else %}
          {% set s = states('sensor.motion_vehicle_alpr_date') %}
          {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != 'null' %}
            {{ s }}
          {% else %}null{% endif %}
        {% endif %}

## when - human readable
- platform: template
  sensors:
    motion_vehicle_alpr_when:
      friendly_name: Detected_entity at
      value_template: >-
        {% set s = states('sensor.motion_vehicle_alpr_date')|int %}
        {% if s > 0 %}
          {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
        {% else %}never{% endif %}

## ago
- platform: template
  sensors:
    motion_vehicle_alpr_ago:
      friendly_name: Detected_entity ago
      unit_of_measurement: seconds
      value_template: >
        {% set t = states('sensor.time') %}
        {% set s = states('sensor.motion_vehicle_alpr_date')|int %}
        {% if s > 0 %}
          {% set s = utcnow().timestamp()|int - s %}
          {% if s < 86400 %}{{ s }}{%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
