###
## homeassistant/motion/sensor/yolo4motion.yaml
###

- platform: rest
  name: motion_yolo_status
  json_attributes:
    - mqtt
    - timestamp
    - date
    - hzn
    - config
    - service
  force_update: true
  resource_template: >-
    {% set s = states('input_text.motion_yolo_ip') %}
    {% if s is none or s|lower == 'unavailable' or s|lower == 'unknown' or s|length == 0 %}
      {% set s = '127.0.0.1' %}
    {% endif %}
    {% set s = 'http://' + s|string + ':4662' %}
    {{  s }}
  value_template: >-
    {% if value_json is defined %}True{% else %}False{% endif %}

- platform: template
  sensors:
    motion_yolo_date:
      friendly_name: YOLO date
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','date') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ s|int }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_yolo_when:
      friendly_name: YOLO when 
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','date') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_yolo_config:
      friendly_name: YOLO config
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','config') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ state_attr('sensor.motion_yolo_status','config').yolo.config }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_yolo_entity:
      friendly_name: YOLO entity
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','config') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ state_attr('sensor.motion_yolo_status','config').yolo.entity }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_yolo_scale:
      friendly_name: YOLO scale
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','config') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ state_attr('sensor.motion_yolo_status','config').yolo.scale }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_yolo_threshold:
      friendly_name: YOLO threshold
      value_template: >-
        {% set s = state_attr('sensor.motion_yolo_status','config') %}
        {% if s is not none and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ state_attr('sensor.motion_yolo_status','config').yolo.darknet.threshold }}
        {% else %}null{% endif %}
