###
## motion/binary_sensor/annotated.yaml
###

## annotated
- platform: template
  sensors:
    motion_annotated:
      friendly_name: Annotated
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {{ states('sensor.motion_event_annotated')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_expired:
      entity_id:
        - sensor.motion_annotated_ago
        - input_number.motion_annotated_ago
      value_template: >-
        {{ is_state('binary_sensor.motion_annotated','on') and states('sensor.motion_annotated_ago')|int > states('input_number.motion_annotated_ago')|int }}
