###
## motion/binary_sensor/detected.yaml
###

- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_annotated_count
      value_template: >-
        {{ states('sensor.motion_annotated_count')|int > 0 and is_state('binary_sensor.motion_detected_expired','off') }}

- platform: template
  sensors:
    motion_detected_expired:
      entity_id:
        - sensor.motion_detected_ago
      value_template: >-
        {{ states('sensor.motion_detected_ago')|int > states('input_number.motion_detected_ago')|int }}
