###
## motion/binary_sensor/detected.yaml
###

## detected
- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_annotated_count
      value_template: >-
        {% set count = states('sensor.motion_annotated_count') %}
        {% if count is not none and count|lower != 'unknown' and count != 'null' %}
          {{ count|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_expired:
      entity_id:
        - sensor.motion_detected_ago
        - input_number.motion_detected_ago
      value_template: >-
        {{ is_state('binary_sensor.motion_detected','on') and states('sensor.motion_detected_ago')|int > states('input_number.motion_detected_ago')|int }}
