###
## motion/binary_sensor/face_detected.yaml
###

## face_detected
- platform: template
  sensors:
    motion_face_detected:
      entity_id:
        - sensor.motion_event_face
      friendly_name: Detected
      value_template: >-
        {{ is_state('binary_sensor.motion_face','on') and state_attr('sensor.motion_event_face','count')|int > 0 }}

- platform: template
  sensors:
    motion_face_detected_expired:
      entity_id:
        - sensor.motion_face_detected_ago
        - input_number.motion_face_detected_ago
      value_template: >-
        {{ states('sensor.motion_face_detected_ago')|int > states('input_number.motion_face_detected_ago')|int }}
