###
## motion/binary_sensor/found.yaml
###

- platform: template
  sensors:
    motion_status_camera_found:
      friendly_name: Camera found
      entity_id:
        - sensor.motion_status_camera_found
      value_template: >
        {{ states('sensor.motion_status_camera_found')|lower == 'true' }}

