- platform: template
  sensors:
    motion_status_camera_lost:
      friendly_name: Camera lost
      entity_id:
        - sensor.motion_status_camera_lost
      value_template: >
        {{ states('sensor.motion_status_camera_lost')|lower == 'true' }}
