###
### EXCHANGE BINARY_SENSOR
###

- platform: template
  sensors:
    exchange_state:
      entity_id:
        - sensor.exchange_status
      value_template: >-
        {% if states.sensor.exchange_status is defined
           and states.sensor.exchange_status.state is defined %}
          {{ states.sensor.exchange_status.state == 'True' }}
        {% else %}False{% endif %}
