- platform: command_line
  command: echo '{"date":'$(date "+%s")',"hostname":"'$(hostname)'","ipv4":"'$(ip addr | egrep "global" | sed "s/.* \([0-9\.]*\)\/.*/\1/" | head -1)'"}'
  name: host_lan_ip
  scan_interval: 14400
  command_timeout: 30
  json_attributes:
    - date
    - hostname
    - ipv4
  value_template: >
    {%- if value_json is defined -%}
      {{ value_json.date | int | timestamp_custom("%a %b %d @ %I:%M %p %Z") }}
    {%- else -%}null{%- endif -%}
