###
# homeassistant/sensor/switch
###

- platform: template
  sensors:
    switch_status:
      entity_id:
        - sensor.time
      unit_of_measurement: Mbps
      value_template: >-
        [
        {% for state in states.switch -%}
          {%- if loop.first %}{% else %},{% endif -%}
          {"{{- state.name| lower -}}":"{{- state.state_with_unit -}}"}
        {% endfor %}
        ]

- platform: template
  sensors:
    switch_count:
      entity_id:
        - sensor.switch_status
      unit_of_measurement: count
      value_template: >-
        {{ states('sensor.switch_status')|from_json|length }}
