###
## sensor/systemmonitor.yaml
###

- platform: systemmonitor
  resources:
    #
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    #
    - type: network_in
      arg: eth0
    #
    - type: network_out
      arg: eth0

# {
#   "api": 1,
#   "id": "system.cpu",
#   "name": "system.cpu",
#   "view_update_every": 1,
#   "update_every": 1,
#   "first_entry": 1590332189,
#   "last_entry": 1590336185,
#   "before": 1590336185,
#   "after": 1590335706,
#   "dimension_names": [ "softirq", "irq", "user", "system", "nice", "iowait" ],
#   "dimension_ids": [ "softirq", "irq", "user", "system", "nice", "iowait" ],
#   "latest_values": [ 1.5345269, 1.790281, 7.41688, 5.626598, 0, 0 ],
#   "view_latest_values": [ 1.5345269, 1.790281, 7.41688, 5.626598, 0, 0 ],
#   "dimensions": 6,
#   "points": 480,
#   "format": "array",
#   "result": [],
#   "min": 6.2814072,
#   "max": 62.2449022
# }

- platform: rest
  name: netdata_system_cpu
  resource: http://127.0.0.1:19999/api/v1/data?chart=system.cpu&format=array&points=480&group=average%3Eime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-480
  force_update: true
  method: GET
  timeout: 5
  json_attributes:
    - api
    - id
    - name
    - view_update_every
    - update_every
    - first_entry
    - last_entry
    - before
    - after
    - dimension_names
    - dimension_ids
    - latest_values
    - view_latest_values
    - dimensions
    - points
    - format
    - result
    - min
    - max
  value_template: >
    {%- if value_json is defined -%} {{ value_json.latest_values|first }} {%- else -%}null{%- endif -%}

# {
#    "api": 1,
#    "id": "system.ram",
#    "name": "system.ram",
#    "view_update_every": 1,
#    "update_every": 1,
#    "first_entry": 1590331621,
#    "last_entry": 1590335617,
#    "before": 1590335617,
#    "after": 1590335138,
#    "dimension_names": ["used", "buffers"],
#    "dimension_ids": ["used", "buffers"],
#    "latest_values": [2219.625, 164.87891],
#    "view_latest_values": [2219.625, 164.87891],
#    "dimensions": 2,
#    "points": 480,
#    "format": "array",
#    "result": [],
#    "min": 0,
#    "max": 73.8615053
# }

- platform: rest
  name: netdata_system_ram
  resource: http://127.0.0.1:19999/api/v1/data?chart=system.ram&format=array&points=480&group=average&options=absolute|percentage|jsonwrap|nonzero&after=-480&dimensions=used|buffers|active|wired
  force_update: true
  method: GET
  timeout: 5
  json_attributes:
    - api
    - id
    - name
    - view_update_every
    - update_every
    - first_entry
    - last_entry
    - before
    - after
    - dimension_names
    - dimension_ids
    - latest_values
    - view_latest_values
    - dimensions
    - points
    - format
    - result
    - min
    - max
  value_template: >
    {%- if value_json is defined -%} {{ value_json.latest_values|first }} {%- else -%}null{%- endif -%}
