###
## sensor/systemmonitor.yaml
###

- platform: systemmonitor
  resources:
    #
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    #
    - type: network_in
      arg: eth0
    #
    - type: network_out
      arg: eth0

- platform: rest
  name: netdata_system_cpu
  resource: http://127.0.0.1:19999/api/v1/data?chart=system.cpu&format=array&points=480&group=average%3Eime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-480
  value_template: >
    {%- if value_json is defined -%} {{ value_json.latest_values|first }} {%- else -%}null{%- endif -%}
