###
### group/default.yaml
###

default_view:
  name: HOME
  view: true
  control: hidden
  icon: mdi:home
  entities:
    - group.datetime
    - group.motion_brief

datetime:
  name: datetime
  view: no
  control: hidden
  entities:
    - sensor.date
    - sensor.time
