###
### group/default.yaml
###

default_view:
  name: HOME
  view: true
  icon: mdi:home
  entities:
    - group.datetime
    - group.systemmonitor
    - group.motion_config
    - group.motion_brief

datetime:
  name: datetime
  entities:
    - sensor.date
    - sensor.time

systemmonitor:
  name: systemmonitor
  entities:
    - sensor.last_boot
    - sensor.load_15m
    - sensor.load_5m
    - sensor.load_1m
    - sensor.memory_free
