##
## most recent image (via MQTT)
##
- platform: generic
  name: motion_detected_picture
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture') %}
    {% endif %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_nosignal_picture') }}
    {% endif %}
