- platform: generic
  name: motion_testsignal
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states.sensor.motion_base_url != none %}
      {{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}
    {% else %}null{% endif %}
