###
### woodshed cameras
###

- platform: mjpeg
  name: motion_live_woodshed
  mjpeg_url: http://woodshed.dcmartin.com/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_woodshed
  topic: 'motion/+/woodshed/image'
- platform: mqtt
  name: motion_event_average_woodshed
  topic: 'motion/+/woodshed/image-average'
- platform: mqtt
  name: motion_event_blend_woodshed
  topic: 'motion/+/woodshed/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_woodshed
  topic: 'motion/+/woodshed/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_woodshed
  topic: 'motion/+/woodshed/image-composite'
- platform: mqtt
  name: motion_event_animated_woodshed
  topic: 'motion/+/woodshed/image-animated'
- platform: mqtt
  name: motion_event_cropped_woodshed
  topic: 'motion/+/woodshed/image-cropped'

- platform: mqtt
  name: motion_event_end_woodshed
  topic: 'motion/+/woodshed/image/end'
- platform: mqtt
  name: motion_event_annotated_woodshed
  topic: 'motion/+/woodshed/image/end/+'

# end
- platform: generic
  name: motion_end_picture_woodshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_woodshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_woodshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_woodshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_woodshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_woodshed') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_woodshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_woodshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
