###
### upperpathgate cameras
###

- platform: mjpeg
  name: motion_live_upperpathgate
  mjpeg_url: http://upperpathgate.dcmartin.com/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_upperpathgate
  topic: 'motion/+/upperpathgate/image'
- platform: mqtt
  name: motion_event_average_upperpathgate
  topic: 'motion/+/upperpathgate/image-average'
- platform: mqtt
  name: motion_event_blend_upperpathgate
  topic: 'motion/+/upperpathgate/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_upperpathgate
  topic: 'motion/+/upperpathgate/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_upperpathgate
  topic: 'motion/+/upperpathgate/image-composite'
- platform: mqtt
  name: motion_event_animated_upperpathgate
  topic: 'motion/+/upperpathgate/image-animated'
- platform: mqtt
  name: motion_event_cropped_upperpathgate
  topic: 'motion/+/upperpathgate/image-cropped'

- platform: mqtt
  name: motion_event_end_upperpathgate
  topic: 'motion/+/upperpathgate/image/end'
- platform: mqtt
  name: motion_event_annotated_upperpathgate
  topic: 'motion/+/upperpathgate/image/end/+'

# end
- platform: generic
  name: motion_end_picture_upperpathgate
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_upperpathgate') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_upperpathgate
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_upperpathgate') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_upperpathgate
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_upperpathgate') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_upperpathgate
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_upperpathgate') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
