###
### gravelpad cameras
###

- platform: mjpeg
  name: motion_live_gravelpad
  mjpeg_url: http://192.168.1.175/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_gravelpad
  topic: 'motion/+/gravelpad/image'
- platform: mqtt
  name: motion_event_average_gravelpad
  topic: 'motion/+/gravelpad/image-average'
- platform: mqtt
  name: motion_event_blend_gravelpad
  topic: 'motion/+/gravelpad/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_gravelpad
  topic: 'motion/+/gravelpad/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_gravelpad
  topic: 'motion/+/gravelpad/image-composite'
- platform: mqtt
  name: motion_event_animated_gravelpad
  topic: 'motion/+/gravelpad/image-animated'
- platform: mqtt
  name: motion_event_cropped_gravelpad
  topic: 'motion/+/gravelpad/image-cropped'

- platform: mqtt
  name: motion_event_end_gravelpad
  topic: 'motion/+/gravelpad/image/end'
- platform: mqtt
  name: motion_event_annotated_gravelpad
  topic: 'motion/+/gravelpad/image/end/+'

# end
- platform: generic
  name: motion_end_picture_gravelpad
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_gravelpad') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_gravelpad
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_gravelpad') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_gravelpad
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_gravelpad') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_gravelpad
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_gravelpad') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
