###
### dogshed cameras
###

- platform: mjpeg
  name: motion_live_dogshed
  mjpeg_url: http://192.168.1.173/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_dogshed
  topic: 'motion/+/dogshed/image'
- platform: mqtt
  name: motion_event_average_dogshed
  topic: 'motion/+/dogshed/image-average'
- platform: mqtt
  name: motion_event_blend_dogshed
  topic: 'motion/+/dogshed/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_dogshed
  topic: 'motion/+/dogshed/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_dogshed
  topic: 'motion/+/dogshed/image-composite'
- platform: mqtt
  name: motion_event_animated_dogshed
  topic: 'motion/+/dogshed/image-animated'
- platform: mqtt
  name: motion_event_cropped_dogshed
  topic: 'motion/+/dogshed/image-cropped'

- platform: mqtt
  name: motion_event_end_dogshed
  topic: 'motion/+/dogshed/image/end'
- platform: mqtt
  name: motion_event_annotated_dogshed
  topic: 'motion/+/dogshed/image/end/+'

# end
- platform: generic
  name: motion_end_picture_dogshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_dogshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_dogshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_dogshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_dogshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_dogshed') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_dogshed
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_dogshed') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
