###
### foyer cameras
###

- platform: mjpeg
  name: motion_live_foyer
  mjpeg_url: http://192.168.1.178/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_foyer
  topic: 'motion/+/foyer/image'
- platform: mqtt
  name: motion_event_average_foyer
  topic: 'motion/+/foyer/image-average'
- platform: mqtt
  name: motion_event_blend_foyer
  topic: 'motion/+/foyer/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_foyer
  topic: 'motion/+/foyer/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_foyer
  topic: 'motion/+/foyer/image-composite'
- platform: mqtt
  name: motion_event_animated_foyer
  topic: 'motion/+/foyer/image-animated'
- platform: mqtt
  name: motion_event_cropped_foyer
  topic: 'motion/+/foyer/image-cropped'

- platform: mqtt
  name: motion_event_end_foyer
  topic: 'motion/+/foyer/image/end'
- platform: mqtt
  name: motion_event_annotated_foyer
  topic: 'motion/+/foyer/image/end/+'

# end
- platform: generic
  name: motion_end_picture_foyer
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_foyer') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_foyer
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_foyer') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_foyer
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_foyer') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_foyer
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_foyer') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
