###
### frontdoor cameras
###

- platform: mjpeg
  name: motion_live_frontdoor
  mjpeg_url: http://192.168.1.37:8090/1
  verify_ssl: false
  username: username
  password: password

- platform: mqtt
  name: motion_current_frontdoor
  topic: 'motion/+/frontdoor/image'
- platform: mqtt
  name: motion_event_average_frontdoor
  topic: 'motion/+/frontdoor/image-average'
- platform: mqtt
  name: motion_event_blend_frontdoor
  topic: 'motion/+/frontdoor/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_frontdoor
  topic: 'motion/+/frontdoor/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_frontdoor
  topic: 'motion/+/frontdoor/image-composite'
- platform: mqtt
  name: motion_event_animated_frontdoor
  topic: 'motion/+/frontdoor/image-animated'
- platform: mqtt
  name: motion_event_cropped_frontdoor
  topic: 'motion/+/frontdoor/image-cropped'

- platform: mqtt
  name: motion_event_end_frontdoor
  topic: 'motion/+/frontdoor/image/end'
- platform: mqtt
  name: motion_event_annotated_frontdoor
  topic: 'motion/+/frontdoor/image/end/+'

# end
- platform: generic
  name: motion_end_picture_frontdoor
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_frontdoor') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_frontdoor
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_frontdoor') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_frontdoor
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_frontdoor') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_frontdoor
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_frontdoor') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
