###
### pi32 cameras
###

- platform: mjpeg
  name: motion_live_pi32
  mjpeg_url: http://192.168.1.72:8090/1
  verify_ssl: false
  username: username
  password: password

- platform: mqtt
  name: motion_current_pi32
  topic: 'motion/+/pi32/image'
- platform: mqtt
  name: motion_event_average_pi32
  topic: 'motion/+/pi32/image-average'
- platform: mqtt
  name: motion_event_blend_pi32
  topic: 'motion/+/pi32/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_pi32
  topic: 'motion/+/pi32/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_pi32
  topic: 'motion/+/pi32/image-composite'
- platform: mqtt
  name: motion_event_animated_pi32
  topic: 'motion/+/pi32/image-animated'
- platform: mqtt
  name: motion_event_cropped_pi32
  topic: 'motion/+/pi32/image-cropped'

- platform: mqtt
  name: motion_event_end_pi32
  topic: 'motion/+/pi32/image/end'
- platform: mqtt
  name: motion_event_annotated_pi32
  topic: 'motion/+/pi32/image/end/+'

# end
- platform: generic
  name: motion_end_picture_pi32
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_pi32') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_pi32
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_pi32') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_pi32
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_pi32') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_pi32
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_pi32') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
