###
### backyard cameras
###

- platform: mjpeg
  name: motion_live_backyard
  mjpeg_url: http://192.168.1.183/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_backyard
  topic: 'motion/+/backyard/image'
- platform: mqtt
  name: motion_event_average_backyard
  topic: 'motion/+/backyard/image-average'
- platform: mqtt
  name: motion_event_blend_backyard
  topic: 'motion/+/backyard/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_backyard
  topic: 'motion/+/backyard/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_backyard
  topic: 'motion/+/backyard/image-composite'
- platform: mqtt
  name: motion_event_animated_backyard
  topic: 'motion/+/backyard/image-animated'
- platform: mqtt
  name: motion_event_cropped_backyard
  topic: 'motion/+/backyard/image-cropped'

- platform: mqtt
  name: motion_event_end_backyard
  topic: 'motion/+/backyard/image/end'
- platform: mqtt
  name: motion_event_annotated_backyard
  topic: 'motion/+/backyard/image/end/+'

# end
- platform: generic
  name: motion_end_picture_backyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_backyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_backyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_backyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_backyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_backyard') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_backyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_backyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
