###
### frontwalk cameras
###

- platform: mjpeg
  name: motion_live_frontwalk
  mjpeg_url: http://192.168.1.179/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_frontwalk
  topic: 'motion/+/frontwalk/image'
- platform: mqtt
  name: motion_event_average_frontwalk
  topic: 'motion/+/frontwalk/image-average'
- platform: mqtt
  name: motion_event_blend_frontwalk
  topic: 'motion/+/frontwalk/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_frontwalk
  topic: 'motion/+/frontwalk/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_frontwalk
  topic: 'motion/+/frontwalk/image-composite'
- platform: mqtt
  name: motion_event_animated_frontwalk
  topic: 'motion/+/frontwalk/image-animated'
- platform: mqtt
  name: motion_event_cropped_frontwalk
  topic: 'motion/+/frontwalk/image-cropped'

- platform: mqtt
  name: motion_event_end_frontwalk
  topic: 'motion/+/frontwalk/image/end'
- platform: mqtt
  name: motion_event_annotated_frontwalk
  topic: 'motion/+/frontwalk/image/end/+'

# end
- platform: generic
  name: motion_end_picture_frontwalk
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_frontwalk') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_frontwalk
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_frontwalk') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_frontwalk
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_frontwalk') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_frontwalk
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_frontwalk') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
