###
### kitchen cameras
###

- platform: mjpeg
  name: motion_live_kitchen
  mjpeg_url: http://192.168.1.34:8090/1
  verify_ssl: false
  username: username
  password: password

- platform: mqtt
  name: motion_current_kitchen
  topic: 'motion/+/kitchen/image'
- platform: mqtt
  name: motion_event_average_kitchen
  topic: 'motion/+/kitchen/image-average'
- platform: mqtt
  name: motion_event_blend_kitchen
  topic: 'motion/+/kitchen/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_kitchen
  topic: 'motion/+/kitchen/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_kitchen
  topic: 'motion/+/kitchen/image-composite'
- platform: mqtt
  name: motion_event_animated_kitchen
  topic: 'motion/+/kitchen/image-animated'
- platform: mqtt
  name: motion_event_cropped_kitchen
  topic: 'motion/+/kitchen/image-cropped'

- platform: mqtt
  name: motion_event_end_kitchen
  topic: 'motion/+/kitchen/image/end'
- platform: mqtt
  name: motion_event_annotated_kitchen
  topic: 'motion/+/kitchen/image/end/+'

# end
- platform: generic
  name: motion_end_picture_kitchen
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_kitchen') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_kitchen
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_kitchen') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_kitchen
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_kitchen') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_kitchen
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_kitchen') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
