###
### dogshedfront cameras
###

- platform: mjpeg
  name: motion_live_dogshedfront
  mjpeg_url: http://192.168.1.172/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_dogshedfront
  topic: 'motion/+/dogshedfront/image'
- platform: mqtt
  name: motion_event_average_dogshedfront
  topic: 'motion/+/dogshedfront/image-average'
- platform: mqtt
  name: motion_event_blend_dogshedfront
  topic: 'motion/+/dogshedfront/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_dogshedfront
  topic: 'motion/+/dogshedfront/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_dogshedfront
  topic: 'motion/+/dogshedfront/image-composite'
- platform: mqtt
  name: motion_event_animated_dogshedfront
  topic: 'motion/+/dogshedfront/image-animated'
- platform: mqtt
  name: motion_event_cropped_dogshedfront
  topic: 'motion/+/dogshedfront/image-cropped'

- platform: mqtt
  name: motion_event_end_dogshedfront
  topic: 'motion/+/dogshedfront/image/end'
- platform: mqtt
  name: motion_event_annotated_dogshedfront
  topic: 'motion/+/dogshedfront/image/end/+'

# end
- platform: generic
  name: motion_end_picture_dogshedfront
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_dogshedfront
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_dogshedfront
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_dogshedfront') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_dogshedfront
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
