###
### dogpond cameras
###

- platform: mjpeg
  name: motion_live_dogpond
  mjpeg_url: http://192.168.1.165/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_dogpond
  topic: 'motion/+/dogpond/image'
- platform: mqtt
  name: motion_event_average_dogpond
  topic: 'motion/+/dogpond/image-average'
- platform: mqtt
  name: motion_event_blend_dogpond
  topic: 'motion/+/dogpond/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_dogpond
  topic: 'motion/+/dogpond/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_dogpond
  topic: 'motion/+/dogpond/image-composite'
- platform: mqtt
  name: motion_event_animated_dogpond
  topic: 'motion/+/dogpond/image-animated'
- platform: mqtt
  name: motion_event_cropped_dogpond
  topic: 'motion/+/dogpond/image-cropped'

- platform: mqtt
  name: motion_event_end_dogpond
  topic: 'motion/+/dogpond/image/end'
- platform: mqtt
  name: motion_event_annotated_dogpond
  topic: 'motion/+/dogpond/image/end/+'

# end
- platform: generic
  name: motion_end_picture_dogpond
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_dogpond') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_dogpond
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_dogpond') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_dogpond
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_dogpond') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_dogpond
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_dogpond') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
