###
### laundry cameras
###

- platform: mjpeg
  name: motion_live_laundry
  mjpeg_url: http://192.168.1.177/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_laundry
  topic: 'motion/+/laundry/image'
- platform: mqtt
  name: motion_event_average_laundry
  topic: 'motion/+/laundry/image-average'
- platform: mqtt
  name: motion_event_blend_laundry
  topic: 'motion/+/laundry/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_laundry
  topic: 'motion/+/laundry/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_laundry
  topic: 'motion/+/laundry/image-composite'
- platform: mqtt
  name: motion_event_animated_laundry
  topic: 'motion/+/laundry/image-animated'
- platform: mqtt
  name: motion_event_cropped_laundry
  topic: 'motion/+/laundry/image-cropped'

- platform: mqtt
  name: motion_event_end_laundry
  topic: 'motion/+/laundry/image/end'
- platform: mqtt
  name: motion_event_annotated_laundry
  topic: 'motion/+/laundry/image/end/+'

# end
- platform: generic
  name: motion_end_picture_laundry
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_laundry') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_laundry
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_laundry') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_laundry
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_laundry') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_laundry
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_laundry') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
