###
### fireplace cameras
###

- platform: mjpeg
  name: motion_live_fireplace
  mjpeg_url: http://192.168.1.166/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_fireplace
  topic: 'motion/+/fireplace/image'
- platform: mqtt
  name: motion_event_average_fireplace
  topic: 'motion/+/fireplace/image-average'
- platform: mqtt
  name: motion_event_blend_fireplace
  topic: 'motion/+/fireplace/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_fireplace
  topic: 'motion/+/fireplace/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_fireplace
  topic: 'motion/+/fireplace/image-composite'
- platform: mqtt
  name: motion_event_animated_fireplace
  topic: 'motion/+/fireplace/image-animated'
- platform: mqtt
  name: motion_event_cropped_fireplace
  topic: 'motion/+/fireplace/image-cropped'

- platform: mqtt
  name: motion_event_end_fireplace
  topic: 'motion/+/fireplace/image/end'
- platform: mqtt
  name: motion_event_annotated_fireplace
  topic: 'motion/+/fireplace/image/end/+'

# end
- platform: generic
  name: motion_end_picture_fireplace
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_fireplace') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_fireplace
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_fireplace') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_fireplace
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_fireplace') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_fireplace
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_fireplace') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
