###
### diningroom cameras
###

- platform: mjpeg
  name: motion_live_diningroom
  mjpeg_url: http://192.168.1.182/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_diningroom
  topic: 'motion/+/diningroom/image'
- platform: mqtt
  name: motion_event_average_diningroom
  topic: 'motion/+/diningroom/image-average'
- platform: mqtt
  name: motion_event_blend_diningroom
  topic: 'motion/+/diningroom/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_diningroom
  topic: 'motion/+/diningroom/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_diningroom
  topic: 'motion/+/diningroom/image-composite'
- platform: mqtt
  name: motion_event_animated_diningroom
  topic: 'motion/+/diningroom/image-animated'
- platform: mqtt
  name: motion_event_cropped_diningroom
  topic: 'motion/+/diningroom/image-cropped'

- platform: mqtt
  name: motion_event_end_diningroom
  topic: 'motion/+/diningroom/image/end'
- platform: mqtt
  name: motion_event_annotated_diningroom
  topic: 'motion/+/diningroom/image/end/+'

# end
- platform: generic
  name: motion_end_picture_diningroom
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_diningroom') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_diningroom
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_diningroom') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_diningroom
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_diningroom') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_diningroom
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_diningroom') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
