###
### sideyard cameras
###

- platform: mjpeg
  name: motion_live_sideyard
  mjpeg_url: http://192.168.1.171/img/video.mjpeg
  verify_ssl: false
  username: !secret webcam-username
  password: !secret webcam-password

- platform: mqtt
  name: motion_current_sideyard
  topic: 'motion/+/sideyard/image'
- platform: mqtt
  name: motion_event_average_sideyard
  topic: 'motion/+/sideyard/image-average'
- platform: mqtt
  name: motion_event_blend_sideyard
  topic: 'motion/+/sideyard/image-blend'
- platform: mqtt
  name: motion_event_animated_mask_sideyard
  topic: 'motion/+/sideyard/image-animated-mask'
- platform: mqtt
  name: motion_event_composite_sideyard
  topic: 'motion/+/sideyard/image-composite'
- platform: mqtt
  name: motion_event_animated_sideyard
  topic: 'motion/+/sideyard/image-animated'
- platform: mqtt
  name: motion_event_cropped_sideyard
  topic: 'motion/+/sideyard/image-cropped'

- platform: mqtt
  name: motion_event_end_sideyard
  topic: 'motion/+/sideyard/image/end'
- platform: mqtt
  name: motion_event_annotated_sideyard
  topic: 'motion/+/sideyard/image/end/+'

# end
- platform: generic
  name: motion_end_picture_sideyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_end_picture_sideyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# annotated
- platform: generic
  name: motion_annotated_picture_sideyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture_sideyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected
- platform: generic
  name: motion_detected_picture_sideyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_picture_sideyard') %}
    {% if  p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

# detected_entity
- platform: generic
  name: motion_detected_entity_picture_sideyard
  verify_ssl: false
  #framerate: 5
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture_sideyard') %}
    {% if p != 'unknown' and p != 'null' %}
      {{ p }}
    {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}
