###
### sdr2msghub BINARY_SENSOR
###

- platform: template
  sensors:
    ## state
    sdr2msghub_state:
      entity_id:
        - sensor.sdr2msghub_event
      value_template: >
        {{ states.sensor.sdr2msghub_event.state|lower == 'true'  }}
