###
# group/settings.yaml
###

settings_view:
  name: SETTINGS
  view: true
  icon: mdi:settings
  control: hidden
  entities:
    - group.settings_frontend
    - group.settings_internet
    - group.settings_sdr2msghub
    - group.settings_yolo2msghub
    - group.settings_startup
    - group.settings_motion

settings_frontend:
  name: settings_frontend
  view: false
  control: hidden
  icon: mdi:spray
  entities:
    - input_select.theme_select
    - input_select.homeassistant_url
    - sensor.motion_base_url

settings_internet:
  name: settings_internet
  control: hidden
  entities:
    - input_number.internet_deviation

settings_sdr2msghub:
  name: settings_sdr2msghub
  control: hidden
  entities:
    - input_number.sdr2msghub_confidence
    - input_number.sdr2msghub_relevance

settings_yolo2msghub:
  name: settings_yolo2msghub
  control: hidden
  entities:
    - input_number.yolo2msghub_detected_deviation
    - input_number.yolo2msghub_client_deviation

settings_startup:
  name: settings_startup
  control: hidden
  entities:
    - input_number.startup_download_deviation
    - input_number.startup_average_deviation
    - input_number.startup_measurement_deviation
    - input_number.startup_client_deviation

settings_motion:
  name: settings_motion
  control: hidden
  entities:
    - input_select.motion_detect_entity
    - sensor.motion_detect_entity
    - sensor.motion_device_start_camera_count
    - sensor.motion_device_start_camera_names
    - input_boolean.motion_detected_entity_notify
    - input_boolean.motion_detected_notify
    - input_boolean.motion_reset_found
    - input_boolean.motion_reset_lost
    - input_boolean.motion_snapshot
    - input_boolean.motion_status_camera_notify
    - input_number.motion_complete
    - input_number.motion_annotated_ago
    - input_number.motion_detected_ago
    - input_number.motion_detected_entity_ago
    - input_number.motion_annotated_counter_deviation
    - input_number.motion_detected_counter_deviation
    - input_number.motion_detected_entity_counter_deviation
    - input_number.motion_end_counter_deviation
    - input_number.motion_annotated_count_deviation
    - input_number.motion_detected_count_deviation
    - input_number.motion_detected_entity_count_deviation
