##
## CAMERA FOUND - 'motion/pi41/+/status/found'
##

- platform: mqtt
  name: motion_camera_found
  state_topic: 'motion/pi41/+/status/found'
  qos: 2
  expire_after: 1
  force_update: True
  json_attributes:
    - device
    - camera
    - date
    - status
  value_template: >
    {% if value_json is defined %}True{% else %}null{% endif %}
