###
### detected_entity SENSOR
###

## annotations that detected_entity entity(s)
- platform: template
  sensors:

    ## human readable status
    motion_detected_entity_status:
      entity_id:
        - sensor.motion_detected_entity_counter
        - sensor.motion_detected_entity_camera
        - sensor.motion_detected_entity_device
      value_template: >-
        Detected
         {% if states.sensor.motion_detected_entity_count != none and states.sensor.motion_detected_entity_count.state|int > 0 %}
          {{ states.sensor.motion_detected_entity_count.state|int }}
        {% else %}zero{% endif %}
        {{ states.sensor.motion_detect_entity.state -}}(s)
        from {{ states.sensor.motion_detected_entity_device.state -}}/{{- states.sensor.motion_detected_entity_camera.state }}

    ## timing
    motion_detected_entity_date:
      entity_id:
        - counter.motion_detected_entity_counter
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_date != none and states.sensor.motion_detected_date.state != 'null' %}
          {{ states.sensor.motion_detected_date.state|int }}
        {% else %}null{% endif %}
    # human readable
    motion_detected_entity_when:
      entity_id:
        - sensor.motion_detected_entity_date
      value_template: >-
        {% if states.sensor.motion_detected_entity_date != none and states.sensor.motion_detected_entity_date.state|int > 0 %}
          {{ states.sensor.motion_detected_entity_date.state|int|timestamp_custom("%a %b %d ~ %I:%M %p") }}
        {% else %}null{% endif %}

    # ago
    motion_detected_entity_ago:
      entity_id:
        - sensor.motion_detected_entity_date
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_entity_date != none
              and states.sensor.motion_detected_entity_date.state|int > 0 %}
          {{ (now().timestamp()|int) - (states.sensor.motion_detected_entity_date.state|int) }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_entity_ago_mean:
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_min_value:
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_max_value:
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_stdev:
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_change_rate:
      entity_id:
        - sensor.motion_detected_entity_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_ago_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_ago_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## elapsed
    motion_detected_entity_elapsed:
      entity_id:
        - sensor.motion_detected_entity_counter
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_event_annotated != none
              and state_attr('sensor.motion_event_annotated','event') != none %}
          {{ states.sensor.motion_event_annotated.attributes.event.elapsed|int }}
        {% else %}null{% endif %}
    # statistics
    motion_detected_entity_elapsed_mean:
      entity_id:
        - sensor.motion_detected_entity_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_elapsed_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_elapsed_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_elapsed_min_value:
      entity_id:
        - sensor.motion_detected_entity_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_elapsed_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_elapsed_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_elapsed_max_value:
      entity_id:
        - sensor.motion_detected_entity_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states('sensor.motion_detected_entity_elapsed_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_elapsed_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_elapsed_stdev:
      entity_id:
        - sensor.motion_detected_entity_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_elapsed_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_elapsed_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_elapsed_change_rate:
      entity_id:
        - sensor.motion_detected_entity_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states('sensor.motion_detected_entity_elapsed_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_elapsed_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## counter of detected_entity events
    motion_detected_entity_counter:
      entity_id:
        - counter.motion_detected_entity_counter
      unit_of_measurement: count
      value_template: >
        {% if states('counter.motion_detected_entity_counter') != 'unknown' %}
          {{ states.counter.motion_detected_entity_counter.state|int }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_entity_counter_mean:
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_min_value:
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_max_value:
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_stdev:
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_change_rate:
      entity_id:
        - sensor.motion_detected_entity_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states('sensor.motion_detected_entity_counter_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_counter_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## percent of detected which contain detect_entity
    motion_detected_entity_percent:
      entity_id:
        - sensor.motion_detected_entity_counter
        - sensor.motion_annotated_counter
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_entity_counter != none
              and states.sensor.motion_detected_entity_counter.state != 'null'
              and states.sensor.motion_detected_counter != none
              and states.sensor.motion_detected_counter.state|int > 0 %}
          {{ ( states.sensor.motion_detected_entity_counter.state|int / states.sensor.motion_detected_counter.state|int ) * 100.0 }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_entity_percent_mean:
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_min_value:
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_max_value:
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_stdev:
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_percent_change_rate:
      entity_id:
        - sensor.motion_detected_entity_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states('sensor.motion_detected_entity_percent_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_percent_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## counting entities detected
    motion_detected_entity_count:
      entity_id:
        - sensor.motion_detected_entity_loop
      unit_of_measurement: entities
      # use loop count or zero
      value_template: >-
        {% if states.sensor.motion_detected_entity_loop != none
              and states.sensor.motion_detected_entity_loop.state != 'null' %}
          {{ states.sensor.motion_detected_entity_loop.state|int }}
        {% else %}null{% endif %}
    # statistics
    # loop through all entities & count
    motion_detected_entity_loop:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >-
        {% if states.sensor.motion_event_annotated != none
              and state_attr('sensor.motion.event_annotated','count') != none
              and states.sensor.motion_event_annotated.attributes.count|int > 0 %}
          {% for detected in states.sensor.motion_event_annotated.attributes.detected %}
            {% if detected.entity == states.sensor.motion_detect_entity.state and detected.count|int > 0 %}
              {{ detected.count }}
            {% endif %}
          {% endfor %}
        {% else %}0{% endif %}
    motion_detected_entity_count_mean:
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_min_value:
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_max_value:
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_stdev:
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_count_change_rate:
      entity_id:
        - sensor.motion_detected_entity_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states('sensor.motion_detected_entity_count_statistics') != 'unknown' %}
          {{ states.sensor.motion_detected_entity_count_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## attributes (change on counter)
    # device
    motion_detected_entity_device:
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
          {% if states.sensor.motion_event_annotated != none
              and states.sensor.motion_event_annotated.attributes.detected|lower != 'none' %}
            {{ states.sensor.motion_event_annotated.attributes.event.device }}
          {% else %}null{% endif %}
    # camera
    motion_detected_entity_camera:
      entity_id:
        - counter.motion_detected_entity_counter
      value_template: >-
          {% if states.sensor.motion_event_annotated != none
              and state_attr('sensor.motion_event_annotated','detected') != none %}
            {{ states.sensor.motion_event_annotated.attributes.event.camera }}
          {% else %}null{% endif %}
    # picture
    motion_detected_entity_picture:
      entity_id:
        - sensor.motion_detected_entity_camera
        - sensor.motion_base_url
      value_template: >-
        {% if states.sensor.motion_detected_entity_camera != none and states.sensor.motion_detected_entity_camera.state != 'null' %}
          {{ states.sensor.motion_base_url.state + '/local/images/motion_detected_entity-' + states.sensor.motion_detected_entity_camera.state + '.jpg' }}
        {% else %}{{ states.sensor.motion_base_url.state + '/local/images/no-signal.jpg' }}{% endif %}
    # old_picture
    motion_detected_entity_old_picture:
      entity_id:
        - sensor.motion_detected_entity_camera
        - sensor.motion_base_url
      value_template: >-
        {% if states.sensor.motion_detected_entity_camera != none 
              and states.sensor.motion_detected_entity_camera.state != 'null' %}
          {{ state_attr('camera.motion_annotated_' + states.sensor.motion_detected_entity_camera.state, 'entity_picture') }}
        {% else %}{{ states.sensor.motion_base_url.state + '/local/images/test-signal.jpg' }}{% endif %}

## history_stats

- platform: history_stats
  name: motion_detected_entity_history
  entity_id: binary_sensor.motion_detected_entity
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

## statistics

# counter
- platform: statistics
  name: motion_detected_entity_counter_statistics
  entity_id: sensor.motion_detected_entity_counter
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_entity_counter_stdev_statistics
  entity_id: sensor.motion_detected_entity_counter_stdev
  sampling_size: 100
  max_age:
    hours: 24

# entity count
- platform: statistics
  name: motion_detected_entity_count_statistics
  entity_id: sensor.motion_detected_entity_count
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_entity_count_stdev_statistics
  entity_id: sensor.motion_detected_entity_count_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds ago
- platform: statistics
  name: motion_detected_entity_ago_statistics
  entity_id: sensor.motion_detected_entity_ago
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_entity_ago_stdev_statistics
  entity_id: sensor.motion_detected_entity_ago_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds elapsed
- platform: statistics
  name: motion_detected_entity_elapsed_statistics
  entity_id: sensor.motion_detected_entity_elapsed
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_entity_elapsed_stdev_statistics
  entity_id: sensor.motion_detected_entity_elapsed_stdev
  sampling_size: 100
  max_age:
    hours: 24

# detected_entity entity percent
- platform: statistics
  name: motion_detected_entity_percent_statistics
  entity_id: sensor.motion_detected_entity_percent
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_entity_percent_stdev_statistics
  entity_id: sensor.motion_detected_entity_percent_stdev
  sampling_size: 100
  max_age:
    hours: 24
