###
### detected SENSOR
###

## human readable status
- platform: template
  sensors:
    motion_detected_status:
      friendly_name: Seen
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_device
        - sensor.motion_detected_camera
        - sensor.motion_detected_count
        - sensor.motion_detected_when
        - sensor.motion_detected_entity_list
      value_template: >-
        {% set count = states('sensor.motion_detected_count')|int %}
        {% set entities = states('sensor.motion_detected_entity_list') %}
        {% set device = states('sensor.motion_detected_device') %}
        {% set camera = states('sensor.motion_detected_camera') %}
        {% set when = states('sensor.motion_detected_when') %}
        {{ when -}}; {{ device -}}/{{- camera -}};
        {% if count > 0 %} {{ count }} entity(s): {{ entities -}} {% else %}nothing{% endif %}

## timing
- platform: template
  sensors:
    motion_detected_date:
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_event_annotated != none and state_attr('sensor.motion_event_annotated','event') != none %}
          {% set date = states.sensor.motion_event_annotated.attributes.event.end|int %}
          {% if date > 0 %}{{ date }}{% else %}null{% endif %}
        {% else %}null{% endif %}
    # human readable
    motion_detected_when:
      friendly_name: Detected at
      entity_id:
        - sensor.motion_detected_date
      value_template: >-
        {% set date = states('sensor.motion_detected_date')|int %}
        {% if date > 0 %} {{ date|timestamp_custom("%a %b %d ~ %I:%M %p") }} {% else %}never{% endif %}

    # ago
    motion_detected_ago:
      friendly_name: Detected ago
      entity_id:
        - sensor.motion_detected_date
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_date != none
              and states.sensor.motion_detected_date.state|int > 0 %}
          {{ (now().timestamp()|int) - (states.sensor.motion_detected_date.state|int) }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_ago_mean:
      friendly_name: Detected ago avg
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics != none %}
          {% if states.sensor.motion_detected_ago_statistics.state|int is number %}
            {{ states.sensor.motion_detected_ago_statistics.state|float }}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_min_value:
      friendly_name: Detected ago min
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics != none %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_max_value:
      friendly_name: Detected ago max
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics != none %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_stdev:
      friendly_name: Detected ago stdev
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_ago_statistics != none %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_change_rate:
      friendly_name: Detected ago change
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_ago_statistics != none %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## elapsed
    motion_detected_elapsed:
      friendly_name: Detected elapsed
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: seconds
      value_template: >
        {% if state_attr('sensor.motion_event_annotated','event') != none
              and states.sensor.motion_event_annotated.attributes.event.elapsed|int > 0 %}
          {{ states.sensor.motion_event_annotated.attributes.event.elapsed|int }}
        {% else %}null{% endif %}
    # statistics
    motion_detected_elapsed_mean:
      friendly_name: Detected elapsed avg
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics != none %}
          {{ states.sensor.motion_detected_elapsed_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_min_value:
      friendly_name: Detected elapsed min
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics != none %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_max_value:
      friendly_name: Detected elapsed max
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics != none %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_stdev:
      friendly_name: Detected elapsed stdev
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_elapsed_statistics != none %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_change_rate:
      friendly_name: Detected elapsed change
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_elapsed_statistics != none %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## counter of detected events
    motion_detected_counter:
      friendly_name: Total seen
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: count
      value_template: >
        {% if states.counter.motion_detected_counter != none %}
          {{ states.counter.motion_detected_counter.state|int }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_counter_mean:
      friendly_name: Detected counter avg
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics != none %}
          {{ states.sensor.motion_detected_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_min_value:
      friendly_name: Detected counter min
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics != none %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_max_value:
      friendly_name: Detected counter max
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics != none %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_stdev:
      friendly_name: Detected counter stdev
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_counter_statistics != none %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_change_rate:
      friendly_name: Detected counter change
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_counter_statistics != none %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## percent of annotated detecting entity
    motion_detected_percent:
      friendly_name: Detected percent
      entity_id:
        - counter.motion_detected_counter
        - counter.motion_annotated_counter
      unit_of_measurement: '%'
      value_template: >-
        {% if states.counter.motion_detected_counter != none
              and states.counter.motion_detected_counter.state|int is number
              and states.counter.motion_annotated_counter != none 
              and states.counter.motion_annotated_counter.state|int > 0 %}
          {{ ( states.counter.motion_detected_counter.state|int / states.counter.motion_annotated_counter.state|int ) * 100.0 }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_percent_mean:
      friendly_name: Detected percent avg
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics != none %}
          {{ states.sensor.motion_detected_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_min_value:
      friendly_name: Detected percent min
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics != none %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_max_value:
      friendly_name: Detected percent max
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics != none %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_stdev:
      friendly_name: Detected percent stdev
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states.sensor.motion_detected_percent_statistics != none %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_change_rate:
      friendly_name: Detected percent change
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states.sensor.motion_detected_percent_statistics != none %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## detected entities
    motion_detected_count:
      friendly_name: Detected count
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_annotated_count != none 
              and states.sensor.motion_annotated_count.state|int is number %}
          {{ states.sensor.motion_annotated_count.state|int }}
        {% else %}null{% endif %}
    # statistics
    motion_detected_count_mean:
      friendly_name: Detected count avg
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics != none %}
          {{ states.sensor.motion_detected_count_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_min_value:
      friendly_name: Detected count min
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics != none %}
          {{ states.sensor.motion_detected_count_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_max_value:
      friendly_name: Detected count max
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics != none %}
          {{ states.sensor.motion_detected_count_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_stdev:
      friendly_name: Detected count stdev
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states.sensor.motion_detected_count_statistics != none %}
          {{ states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_change_rate:
      friendly_name: Detected count change
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states.sensor.motion_detected_count_statistics != none %}
          {{ states.sensor.motion_detected_count_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## attributes (change on counter)
    # device
    motion_detected_device:
      friendly_name: Detected device
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
          {% if states.sensor.motion_event_annotated != none and state_attr('sensor.motion_event_annotated','event') != none %}
            {{ states.sensor.motion_event_annotated.attributes.event.device }}
          {% else %}null{% endif %}
    # camera
    motion_detected_camera:
      friendly_name: Detected camera
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
          {% if states.sensor.motion_event_annotated != none and state_attr('sensor.motion_event_annotated','event') != none %}
            {{ states.sensor.motion_event_annotated.attributes.event.camera }}
          {% else %}null{% endif %}

    ## entity_list
    motion_detected_entity_list:
      friendly_name: Detected entity list
      entity_id:
        - counter.motion_detected_counter
      value_template: >-
        {% if states.sensor.motion_event_annotated != none
              and state_attr('sensor.motion_event_annotated','count')|lower != none
              and state_attr('sensor.motion_event_annotated','count')|int > 0 %}
          {% for detected in states.sensor.motion_event_annotated.attributes.detected %}
           {%- if loop.first -%}{%- else -%},{%- endif -%}
           {{- detected.entity -}}
          {% endfor %}
        {% else %}null{% endif %}

# picture
- platform: template
  sensors:
    motion_detected_picture:
      friendly_name: Detected picture
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_detected_count
        - sensor.motion_detected_camera
      value_template: >-
        {% if states('sensor.motion_detected_count')|int > 0 %}
          {% set c = states('sensor.motion_detected_camera') %}
          {% if c != none and c != 'unknown' and c|length > 0 %}
            {% if states('input_boolean.motion_snapshot') == 'on' %}
              {% set bu = states('sensor.motion_base_url') %}
              {% if bu != 'unknown' %}
                {% set p = bu + '/local/images/motion_detected-' + c + '.jpg' %}
              {% else %}
                {% set p = states('sensor.motion_testsignal_picture') %}
              {% endif %}
            {% else %}
              {% set ap = states('sensor.motion_annotated_picture_' + c) %}
              {% if ap|lower != none and ap != 'null' and ap|length > 0 %}
                {% set p = ap %}
              {% else %}
                {% set p = states('sensor.motion_noisesignal_picture') %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% else %}
          {% set p = states('sensor.motion_detected_picture') %}
        {% endif %}
        {% if p is defined and p != none and p != 'unknown' and p != 'null' and p|length > 0 %}
          {{ p }}
        {% else %}
           {{ states('sensor.motion_nosignal_picture') }}
        {% endif %}

## statistics

# counter
- platform: statistics
  name: motion_detected_counter_statistics
  entity_id: sensor.motion_detected_counter
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_counter_stdev_statistics
  entity_id: sensor.motion_detected_counter_stdev
  sampling_size: 100
  max_age:
    hours: 24

# entity count
- platform: statistics
  name: motion_detected_count_statistics
  entity_id: sensor.motion_detected_count
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_count_stdev_statistics
  entity_id: sensor.motion_detected_count_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds ago
- platform: statistics
  name: motion_detected_ago_statistics
  entity_id: sensor.motion_detected_ago
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_ago_stdev_statistics
  entity_id: sensor.motion_detected_ago_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds elapsed
- platform: statistics
  name: motion_detected_elapsed_statistics
  entity_id: sensor.motion_detected_elapsed
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_elapsed_stdev_statistics
  entity_id: sensor.motion_detected_elapsed_stdev
  sampling_size: 100
  max_age:
    hours: 24

# detected entity percent
- platform: statistics
  name: motion_detected_percent_statistics
  entity_id: sensor.motion_detected_percent
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_percent_stdev_statistics
  entity_id: sensor.motion_detected_percent_stdev
  sampling_size: 100
  max_age:
    hours: 24

## history_stats

#- platform: history_stats
#  name: motion_detected_count_today
#  entity_id: binary_sensor.motion_detected
#  state: 'on'
#  type: count
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
#
#- platform: history_stats
#  name: motion_detected_ratio_today
#  entity_id: binary_sensor.motion_detected
#  state: 'on'
#  type: ratio
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
