###
### DETECTED
###

## annotations that detected entity(s)
- platform: template
  sensors:
    ## human readable status
    motion_detected_status:
      entity_id:
        - sensor.motion_detected_date
      value_template: >-
        Detected
        {% if states.sensor.motion_detected_count is defined %}
          {% if states.sensor.motion_detected_count.state|int > 0 %}
            {{ states.sensor.motion_detected_count.state }}
          {% else %}zero{% endif %}
        {% else %}zero{% endif %}
        entity(s); from {{ states.sensor.motion_detected_device.state -}}/{{- states.sensor.motion_detected_camera.state }} 
    ## timing
    motion_detected_date:
      entity_id:
        - sensor.motion_detected_counter
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_event_annotated is defined %}
          {% if states.sensor.motion_event_annotated.attributes.event.end|int is number %}
            {% if states.sensor.motion_event_annotated.attributes.event.end|int > 0 %}
                {{ states.sensor.motion_event_annotated.attributes.event.end|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}
    # last
    motion_detected_last:
      entity_id:
        - sensor.motion_detected_date
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_date is defined %}
          {% if states.sensor.motion_detected_date.state|int is number %}
            {% if states.sensor.motion_detected_date.state|int > 0 %}
              {{ states.sensor.motion_detected_date.state|int }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}
    # human readable
    motion_detected_when:
      entity_id:
        - sensor.motion_detected_last
      value_template: >-
        {% if states.sensor.motion_detected_last is defined %}
          {% if states.sensor.motion_detected_last.state|int is number %}
            {% if states.sensor.motion_detected_last.state|int > 0 %}
              {{ states.sensor.motion_detected_last.state|int|timestamp_custom("%a %b %d ~ %I:%M %p") }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}
    # ago
    motion_detected_ago:
      entity_id:
        - sensor.motion_detected_last
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_last is defined %}
          {% if states.sensor.motion_detected_last.state|int is number %}
            {% if states.sensor.motion_detected_last.state|int > 0 %}
              {{ (now().timestamp()|int) - (states.sensor.motion_detected_last.state|int) }}
            {%- else -%}null{%- endif -%}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    # derived ago
    motion_detected_ago_mean:
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics is defined %}
          {% if states.sensor.motion_detected_ago_statistics.state|int is number %}
            {{ states.sensor.motion_detected_ago_statistics.state|float }}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_min_value:
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics is defined %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_max_value:
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_ago_statistics is defined %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_stdev:
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_ago_statistics is defined %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_ago_change_rate:
      entity_id:
        - sensor.motion_detected_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_ago_statistics is defined %}
          {{ states.sensor.motion_detected_ago_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    # elapsed
    motion_detected_elapsed:
      entity_id:
        - sensor.motion_detected_last
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_event_annotated is defined %}
          {{ states.sensor.motion_event_annotated.attributes.event.elapsed|int }}
        {% else %}null{% endif %}
    # statistics
    motion_detected_elapsed_mean:
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics is defined %}
          {{ states.sensor.motion_detected_elapsed_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_min_value:
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics is defined %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_max_value:
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >-
        {% if states.sensor.motion_detected_elapsed_statistics is defined %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_stdev:
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_elapsed_statistics is defined %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_elapsed_change_rate:
      entity_id:
        - sensor.motion_detected_elapsed_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_detected_elapsed_statistics is defined %}
          {{ states.sensor.motion_detected_elapsed_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    # count of detected events
    motion_detected_counter:
      entity_id:
        - counter.motion_detected_counter
      unit_of_measurement: count
      value_template: >
        {% if states.counter.motion_detected_counter is defined %}
          {{ states.counter.motion_detected_counter.state|int }}
        {%- else -%}null{%- endif -%}
    # statistics
    motion_detected_counter_mean:
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics is defined %}
          {{ states.sensor.motion_detected_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_min_value:
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics is defined %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_max_value:
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >-
        {% if states.sensor.motion_detected_counter_statistics is defined %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_stdev:
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_counter_statistics is defined %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_counter_change_rate:
      entity_id:
        - sensor.motion_detected_counter_statistics
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_counter_statistics is defined %}
          {{ states.sensor.motion_detected_counter_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    # percent of motion events which were detected
    motion_detected_percent:
      entity_id:
        - sensor.motion_detected_counter
        - sensor.motion_annotated_counter
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_counter is defined and states.sensor.motion_detected_counter.state|int is number and 
              states.sensor.motion_annotated_counter is defined and states.sensor.motion_annotated_counter.state|int > 0 %}
          {{ ( states.sensor.motion_detected_counter.state|int / states.sensor.motion_annotated_counter.state|int ) * 100.0 }}
        {%- else -%}null{%- endif -%}
    ## detected entity percent
    motion_detected_percent_mean:
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics is defined %}
          {{ states.sensor.motion_detected_percent_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_min_value:
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics is defined %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.min_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_max_value:
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >-
        {% if states.sensor.motion_detected_percent_statistics is defined %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.max_value|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_stdev:
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states.sensor.motion_detected_percent_statistics is defined %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_percent_change_rate:
      entity_id:
        - sensor.motion_detected_percent_statistics
      unit_of_measurement: '%'
      value_template: >
        {% if states.sensor.motion_detected_percent_statistics is defined %}
          {{ states.sensor.motion_detected_percent_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}
    ## detected entities
    motion_detected_count:
      entity_id:
        - sensor.motion_event_annotated
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_event_annotated is defined %}
          {{ states.sensor.motion_event_annotated.attributes.count|int }}
        {% else %}0{% endif %}
    # derived motion detected entity count statistics
    motion_detected_count_mean:
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics is defined %}
          {{ states.sensor.motion_detected_count_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_min_value:
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics is defined %}
          {{ states.sensor.motion_detected_count_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_max_value:
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >-
        {% if states.sensor.motion_detected_count_statistics is defined %}
          {{ states.sensor.motion_detected_count_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_stdev:
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states.sensor.motion_detected_count_statistics is defined %}
          {{ states.sensor.motion_detected_count_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_detected_count_change_rate:
      entity_id:
        - sensor.motion_detected_count_statistics
      unit_of_measurement: entities
      value_template: >
        {% if states.sensor.motion_detected_count_statistics is defined %}
          {{ states.sensor.motion_detected_count_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## attributes change on counter
    motion_detected_device:
      entity_id:
        - sensor.motion_detected_counter
      value_template: >-
        {% if states.sensor.motion_event_annotated is defined %}
            {{ states.sensor.motion_event_annotated.attributes.event.device }}
        {% else %}null{% endif %}
    motion_detected_camera:
      entity_id:
        - sensor.motion_detected_counter
      value_template: >-
        {% if states.sensor.motion_event_annotated is defined %}
            {{ states.sensor.motion_event_annotated.attributes.event.camera }}
        {% else %}null{% endif %}
    ## picture
    motion_detected_picture:
      entity_id:
        - sensor.motion_detected_camera
      value_template: >-
        {% set camera = states.sensor.motion_detected_camera.state %}
        {% if camera is defined and camera|length %}
          {% set device = 'camera.motion_annotated_' + camera %}
          http://192.168.1.251:3092{{- state_attr(device, 'entity_picture') -}}
        {% else %}null{% endif %}

## history_stats

- platform: history_stats
  name: motion_detected_history
  entity_id: binary_sensor.motion_detected_entity
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

## statistics

# counter
- platform: statistics
  name: motion_detected_counter_statistics
  entity_id: sensor.motion_detected_counter
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_counter_stdev_statistics
  entity_id: sensor.motion_detected_counter_stdev
  sampling_size: 100
  max_age:
    hours: 24

# entity count
- platform: statistics
  name: motion_detected_count_statistics
  entity_id: sensor.motion_detected_count
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_count_stdev_statistics
  entity_id: sensor.motion_detected_count_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds ago
- platform: statistics
  name: motion_detected_ago_statistics
  entity_id: sensor.motion_detected_ago
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_ago_stdev_statistics
  entity_id: sensor.motion_detected_ago_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds elapsed
- platform: statistics
  name: motion_detected_elapsed_statistics
  entity_id: sensor.motion_detected_elapsed
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_elapsed_stdev_statistics
  entity_id: sensor.motion_detected_elapsed_stdev
  sampling_size: 100
  max_age:
    hours: 24

# detected entity percent
- platform: statistics
  name: motion_detected_percent_statistics
  entity_id: sensor.motion_detected_percent
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_detected_percent_stdev_statistics
  entity_id: sensor.motion_detected_percent_stdev
  sampling_size: 100
  max_age:
    hours: 24
