
##
## EVENT IMAGE - motion/+/+/event/image
##

- platform: mqtt
  name: motion_event_image
  qos: 2
  state_topic: 'motion/+/+/event/image'
  expire_after: 1
  force_update: True
  json_attributes:
    - device
    - camera
    - type
    - date
    - seqno
    - event
    - id
    - center
    - width
    - height
    - size
    - noise
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}

## standard event count, ago, mean, status
- platform: template
  sensors:
    ## human readable
    motion_image_status:
      entity_id:
        - sensor.motion_event_image
      value_template: >-
        {% if states.sensor.motion_event_image is defined and states.sensor.motion_event_image.attributes.camera is defined %}
          From {{ states.sensor.motion_event_image.attributes.device }} {{ states.sensor.motion_event_image.attributes.camera }}
        {% else %} null {% endif %}
    ## timing
    motion_image_date:
      entity_id:
        - sensor.motion_event_image
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_event_image.attributes.date is defined %}
          {% if states.sensor.motion_event_image.attributes.date|int is number %}
            {% if states.sensor.motion_event_image.attributes.date|int > 0 %}
              {{ states.sensor.motion_event_image.attributes.date|int }}
            {%- else -%}null{%- endif -%}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    # human readable
    motion_image_when:
      entity_id:
        - sensor.motion_image_date
      value_template: >
        {% if states.sensor.motion_image_date is defined %}
          {{ states.sensor.motion_image_date.state|int|timestamp_custom("%a %b %d ~ %I:%M %p") }}
        {% else %} null {% endif %}
    # seconds ago
    motion_image_ago:
      entity_id:
        - sensor.motion_image_date
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_date is defined %}
          {% if states.sensor.motion_image_date.state|int is number %}
              {{ (now().timestamp()|int) - (states.sensor.motion_image_date.state|int) }}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    motion_image_ago_mean:
      entity_id:
        - sensor.motion_image_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_ago_statistics is defined %}
          {{ states.sensor.motion_image_ago_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_image_ago_min_value:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_event_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_ago_statistics is defined %}
          {{ states.sensor.motion_image_ago_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_image_ago_max_value:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_event_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_ago_statistics is defined %}
          {{ states.sensor.motion_image_ago_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_image_ago_stdev:
      entity_id:
        - sensor.motion_image_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_ago_statistics is defined %}
          {{ states.sensor.motion_image_ago_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_image_ago_change_rate:
      entity_id:
        - sensor.motion_image_ago_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_ago_statistics is defined %}
          {{ states.sensor.motion_image_ago_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## counting
    motion_image_counter:
      entity_id:
        - counter.motion_image_counter
      unit_of_measurement: count
      value_template: >
        {% if states.counter.motion_image_counter is defined %}
          {{ states.counter.motion_image_counter.state|int }}
        {%- else -%}null{%- endif -%}
    motion_image_counter_mean:
      entity_id:
        - sensor.motion_image_counter_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_counter_statistics is defined %}
          {{ states.sensor.motion_image_counter_statistics.state|float }}
        {%- else -%}null{%- endif -%}
    motion_image_counter_min_value:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_event_counter_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_counter_statistics is defined %}
          {{ states.sensor.motion_image_counter_statistics.attributes.min_value|int }}
        {%- else -%}null{%- endif -%}
    motion_image_counter_max_value:
      entity_id:
        - sensor.motion_event_image
        - sensor.motion_event_counter_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_counter_statistics is defined %}
          {{ states.sensor.motion_image_counter_statistics.attributes.max_value|int }}
        {%- else -%}null{%- endif -%}
    motion_image_counter_stdev:
      entity_id:
        - sensor.motion_image_counter_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_counter_statistics is defined %}
          {{ states.sensor.motion_image_counter_statistics.attributes.standard_deviation|float }}
        {%- else -%}null{%- endif -%}
    motion_image_counter_change_rate:
      entity_id:
        - sensor.motion_image_counter_statistics
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_image_counter_statistics is defined %}
          {{ states.sensor.motion_image_counter_statistics.attributes.change_rate|float }}
        {%- else -%}null{%- endif -%}

    ## attributes
    motion_image_device:
      entity_id:
        - sensor.motion_event_image
      value_template: >
        {% if states.sensor.motion_event_image is defined and states.sensor.motion_event_image.attributes.device is defined %}
          {{ states.sensor.motion_event_image.attributes.device }}
        {% else %} null {% endif %}
    motion_image_camera:
      entity_id:
        - sensor.motion_event_image
      value_template: >
        {% if states.sensor.motion_event_image is defined and states.sensor.motion_event_image.attributes.camera is defined %}
          {{ states.sensor.motion_event_image.attributes.camera }}
        {% else %} null {% endif %}
    motion_image_type:
      entity_id:
        - sensor.motion_event_image
      value_template: >
        {% if states.sensor.motion_event_image is defined and states.sensor.motion_event_image.attributes.type is defined %}
          {{ states.sensor.motion_event_image.attributes.type }}
        {% else %} null {% endif %}
    motion_image_center:
      entity_id:
        - sensor.motion_event_image
      value_template: >
        {% if states.sensor.motion_event_image is defined and states.sensor.motion_event_image.attributes.center is defined %}
          {{ states.sensor.motion_event_image.attributes.center }}
        {% else %} null {% endif %}

- platform: history_stats
  name: motion_image_history
  entity_id: binary_sensor.motion_image_state
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

# counting event_image
- platform: statistics
  name: motion_image_counter_statistics
  entity_id: sensor.motion_image_counter
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_image_counter_stdev_statistics
  entity_id: sensor.motion_image_counter_stdev
  sampling_size: 100
  max_age:
    hours: 24

# seconds ago
- platform: statistics
  name: motion_image_ago_statistics
  entity_id: sensor.motion_image_ago
  sampling_size: 100
  max_age:
    hours: 24
- platform: statistics
  name: motion_image_ago_stdev_statistics
  entity_id: sensor.motion_image_ago_stdev
  sampling_size: 100
  max_age:
    hours: 24
