##
## START EVENT
##

- platform: mqtt
  name: motion_event_start
  qos: 2
  state_topic: 'motion/+/+/event/start'
  expire_after: 1
  force_update: True
  json_attributes:
    - device
    - camera
    - event
    - start
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}
- platform: template
  sensors:
    ## timing
    motion_event_start_ago:
      entity_id:
        - sensor.motion_event_start
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.sensor.motion_event_start.attributes.date is defined %}
          {{ (now().timestamp()|int) - (states.sensor.motion_event_start.attributes.start|int) }}
        {%- else -%}null{%- endif -%}
    motion_start_device:
      entity_id:
        - sensor.motion_event_start
      value_template: >
        {% if states.sensor.motion_event_start is defined %}
          {{ states.sensor.motion_event_start.attributes.device }}
        {% else %} null {% endif %}
    motion_start_camera:
      entity_id:
        - sensor.motion_event_start
      value_template: >
        {% if states.sensor.motion_event_start is defined %}
          {{ states.sensor.motion_event_start.attributes.camera }}
        {% else %} null {% endif %}
    motion_start_when:
      entity_id:
        - sensor.motion_event_start
      value_template: >
        {% if states.sensor.motion_event_start is defined %}
          {{ states.sensor.motion_event_start.attributes.start | int | timestamp_custom("%a %b %d ~ %I:%M %p") }}
        {% else %} null {% endif %}
