##
## webcams SENSOR
##

- platform: template
  sensors:
    motion_detected_entity_counter_webcams:
      entity_id:
        - group.motion_detected_entity_counter_webcams
        - sensor.motion_event_end
      unit_of_measurement: count
      value_template: >
        {% if states.group.motion_detected_entity_counter_webcams != none
              and state_attr('group.motion_detected_entity_counter_webcams','entity_id') != none
              and states.group.motion_detected_entity_counter_webcams.attributes.entity_id|list|length > 0 %}
          {% for eid in states.group.motion_detected_entity_counter_webcams.attributes.entity_id|list %}
            {%- if loop.first %}{% else %}{% if loop.last %}{% else %},{% endif %}{% endif -%}
             {{- states(eid) -}}
          {% endfor %}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_webcams_count:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {{ states.group.motion_detected_entity_counter_webcams.attributes.entity_id|list|length }}
    motion_detected_entity_counter_webcams_sum:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_counter_webcams != none %}
          {{ states.sensor.motion_detected_entity_counter_webcams.state|list|map('int')|map('sum') }}
        {%- else -%}null{%- endif -%}
