##
## webcams SENSOR
##

- platform: template
  sensors:
    motion_detected_entity_counter_webcams:
      entity_id:
        - group.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {% if states.group.motion_detected_entity_counter_webcams != none
              and state_attr('group.motion_detected_entity_counter_webcams','entity_id') != none
              and states.group.motion_detected_entity_counter_webcams.attributes.entity_id|list|length > 0 %}
          {% for e in states.group.motion_detected_entity_counter_webcams.attributes.entity_id %}
            {%- set s = states(e)|int -%}
            {%- if loop.first -%}[{% else -%},{%- endif -%}
            {"e":"{{- e|replace('sensor.motion_detected_entity_counter_','') -}}","v":{{- s -}}}
            {%- if loop.last -%}]{%- endif -%}
          {%- endfor -%}
        {% else %}null{% endif %}
    motion_detected_entity_counter_webcams_count:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {{ states.group.motion_detected_entity_counter_webcams.attributes.entity_id|list|length }}
    motion_detected_entity_counter_webcams_min:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_counter_webcams != none %}
          {{ states.sensor.motion_detected_entity_counter_webcams.state|from_json|min }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_webcams_max:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_counter_webcams != none %}
          {{ states.sensor.motion_detected_entity_counter_webcams.state|from_json|max }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_counter_webcams_sum:
      entity_id:
        - sensor.motion_detected_entity_counter_webcams
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_counter_webcams != none %}
          {{ states.sensor.motion_detected_entity_counter_webcams.state|from_json|sum }}
        {%- else -%}null{%- endif -%}

- platform: template
  sensors:
    motion_detected_entity_ago_webcams:
      entity_id:
        - group.motion_detected_entity_ago_webcams
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.group.motion_detected_entity_ago_webcams != none
              and state_attr('group.motion_detected_entity_ago_webcams','entity_id') != none
              and states.group.motion_detected_entity_ago_webcams.attributes.entity_id|list|length > 0 %}
          {% for e in states.group.motion_detected_entity_ago_webcams.attributes.entity_id %}
            {%- set s = states(e)|int -%}
            {%- if loop.first -%}[{% else -%},{%- endif -%}
            "{{- e|replace('sensor.motion_detected_entity_ago_','') -}}"
            {%- if loop.last -%}]{%- endif -%}
          {%- endfor -%}
        {% else %}null{% endif %}
    motion_detected_entity_ago_values:
      entity_id:
        - group.motion_detected_entity_ago_webcams
        - sun.sun
      unit_of_measurement: seconds
      value_template: >
        {% if states.group.motion_detected_entity_ago_webcams != none
              and state_attr('group.motion_detected_entity_ago_webcams','entity_id') != none
              and states.group.motion_detected_entity_ago_webcams.attributes.entity_id|list|length > 0 %}
          {% for e in states.group.motion_detected_entity_ago_webcams.attributes.entity_id %}
            {%- set s = states(e)|int -%}
            {%- if loop.first -%}[{% else -%},{%- endif -%}
            {"e":{{- loop.index -}},"v":{{- s -}}}
            {%- if loop.last -%}]{%- endif -%}
          {%- endfor -%}
        {% else %}null{% endif %}
    motion_detected_entity_ago_webcams_count:
      entity_id:
        - sensor.motion_detected_entity_ago_webcams
      unit_of_measurement: count
      value_template: >
        {{ states.group.motion_detected_entity_ago_webcams.attributes.entity_id|list|length }}
    motion_detected_entity_ago_webcams_min:
      entity_id:
        - sensor.motion_detected_entity_ago_values
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_ago_values != none %}
          {{ states.sensor.motion_detected_entity_ago_values.state|from_json|sort(attribute='v')|first }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_webcams_max:
      entity_id:
        - sensor.motion_detected_entity_ago_values
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_ago_values != none %}
          {{ states.sensor.motion_detected_entity_ago_values.state|from_json|sort(attribute='v')|last }}
        {%- else -%}null{%- endif -%}
    motion_detected_entity_ago_webcams_sum:
      entity_id:
        - sensor.motion_detected_entity_ago_values
      unit_of_measurement: count
      value_template: >
        {% if states.sensor.motion_detected_entity_ago_values != none %}
          {{ states.sensor.motion_detected_entity_ago_values.state|from_json|map(attribute='v')|sum }}
        {%- else -%}null{%- endif -%}
