###
### woodshed sensors
###

## MOTION_CAMERA FOUND - 'motion/+/woodshed/status/found'
- platform: mqtt
  name: motion_found_woodshed
  state_topic: 'motion/+/woodshed/status/found'
  expire_after: 1
  force_update: true
  json_attributes:
    - device
    - camera
    - date
    - status
  value_template: >
    {% if value_json is defined %}true{% else %}null{% endif %}

## MOTION_CAMERA LOST - 'motion/+/woodshed/status/lost' 
- platform: mqtt
  name: motion_lost_woodshed
  state_topic: 'motion/+/woodshed/status/lost'
  expire_after: 1
  force_update: true
  json_attributes:
    - device
    - camera
    - date
    - status
  value_template: >
    {% if value_json is defined %}true{% else %}null{% endif %}

## EVENT IMAGE - motion/+/woodshed/event/image
- platform: mqtt
  name: motion_image_woodshed
  qos: 1
  state_topic: 'motion/+/woodshed/event/image'
  expire_after: 1
  force_update: true
  json_attributes:
    - device
    - camera
    - type
    - date
    - seqno
    - event
    - id
    - center
    - width
    - height
    - size
    - noise
  value_template: >
    {% if value_json is defined %}true{% else %}null{% endif %}

## START EVENT
- platform: mqtt
  name: motion_start_woodshed
  qos: 1
  state_topic: 'motion/+/woodshed/event/start'
  expire_after: 1
  force_update: true
  json_attributes:
    - device
    - camera
    - event
    - start
  value_template: >
    {% if value_json is defined %}true{% else %}null{% endif %}

## END EVENT
- platform: mqtt
  name: motion_end_woodshed
  qos: 1
  state_topic: 'motion/+/woodshed/event/end'
  expire_after: 1
  force_update: true
  json_attributes:
    - device
    - camera
    - event
    - start
    - end
    - elapsed
    - date
  value_template: >
    {% if value_json is defined %}true{% else %}null{% endif %}

## ANNOTATED EVENT
- platform: mqtt
  name: motion_annotated_woodshed
  state_topic: 'motion/+/woodshed/event/end/+'
  expire_after: 1
  force_update: true
  json_attributes:
    - timestamp
    - date
    - time
    - count
    - event
    - info
    - detected
  value_template: >
    {% if value_json is defined %}
      {% if value_json.count|int > 0 %}true{% else %}null{% endif %}
    {% else %}null{% endif %}
