- platform: template
  sensors:
    homeassistant_url:
      friendly_name: HA URL
      entity_id:
        - input_text.homeassistant_url
      value_template: >-
        {{ states('input_text.homeassistant_url') }}
