###
## sensor/systemmonitor.yaml
###

- platform: systemmonitor
  resources:
    #
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    #
    - type: disk_use_percent
      arg: /usr/share/hassio
    #
    - type: network_in
      arg: eth0
    #
    - type: network_out
      arg: eth0
