###
### device_tracker
###

- platform: mqtt
  name: motion_camera_tracker
  devices:
    frontdoor: 'motion/+/frontdoor/status/found'
    backyard: 'motion/+/backyard/status/found'
    diningroom: 'motion/+/diningroom/status/found'
    dogpond: 'motion/+/dogpond/status/found'
    dogshed: 'motion/+/dogshed/status/found'
    dogshedfront: 'motion/+/dogshedfront/status/found'
    dogshedmiddle: 'motion/+/dogshedmiddle/status/found'
    dogyard: 'motion/+/dogyard/status/found'
    fireplace: 'motion/+/fireplace/status/found'
    foyer: 'motion/+/foyer/status/found'
    frontwalk: 'motion/+/frontwalk/status/found'
    gravelpad: 'motion/+/gravelpad/status/found'
    laundry: 'motion/+/laundry/status/found'
    livingroom: 'motion/+/livingroom/status/found'
    phexterior: 'motion/+/phexterior/status/found'
    pondview: 'motion/+/pondview/status/found'
    sideyard: 'motion/+/sideyard/status/found'
    upperpathgate: 'motion/+/upperpathgate/status/found'
    woodshed: 'motion/+/woodshed/status/found'
