###
### device_tracker
###

- platform: mqtt
  name: motion_webcam_tracker
  devices:
    motion_webcam_frontdoor: 'motion/+/frontdoor/status/found'
    motion_webcam_backyard: 'motion/+/backyard/status/found'
    motion_webcam_diningroom: 'motion/+/diningroom/status/found'
    motion_webcam_dogpond: 'motion/+/dogpond/status/found'
    motion_webcam_dogshed: 'motion/+/dogshed/status/found'
    motion_webcam_dogshedfront: 'motion/+/dogshedfront/status/found'
    motion_webcam_dogshedmiddle: 'motion/+/dogshedmiddle/status/found'
    motion_webcam_dogyard: 'motion/+/dogyard/status/found'
    motion_webcam_fireplace: 'motion/+/fireplace/status/found'
    motion_webcam_foyer: 'motion/+/foyer/status/found'
    motion_webcam_frontwalk: 'motion/+/frontwalk/status/found'
    motion_webcam_gravelpad: 'motion/+/gravelpad/status/found'
    motion_webcam_laundry: 'motion/+/laundry/status/found'
    motion_webcam_livingroom: 'motion/+/livingroom/status/found'
    motion_webcam_phexterior: 'motion/+/phexterior/status/found'
    motion_webcam_pondview: 'motion/+/pondview/status/found'
    motion_webcam_sideyard: 'motion/+/sideyard/status/found'
    motion_webcam_upperpathgate: 'motion/+/upperpathgate/status/found'
    motion_webcam_woodshed: 'motion/+/woodshed/status/found'
