- platform: template
  sensors:
    motion_alarm_wake_interval_detect:
      friendly_name: 'Wake interval person'
      icon_template: 'mdi:account-check'
      value_template: >-
        {% set b = states('input_number.motion_alarm_wake_begin')|int %}
        {% set e = states('input_number.motion_alarm_wake_end')|int %}
        {{ is_state('binary_sensor.motion_detected_person','on')
           or is_state('binary_sensor.motion_detected_person','off')
           and e > now().timestamp()|int > b }}

- platform: template
  sensors:
    motion_schedule_wake_detected:
      friendly_name: 'Wake detected'
      icon_template: >-
        {%- if is_state('automation.motion_schedule_wake_detected_notify','on') -%}
          {%- if state_attr('automation.motion_schedule_wake_detected_notify','current')|int > 0 -%}
             {{- 'mdi:check-outline' -}}
          {%- else -%}{{- 'mdi:check-bold' -}}{%- endif -%}
        {%- else -%}{{- 'mdi:alarm-off' -}}{%- endif -%}
      value_template: >-
        {%- set e = states('sensor.motion_schedule_wake_detected') -%}
        {{- e|lower != 'none' and e|lower != 'unavailable' and e|lower != 'unknown' and e != null and e|int > 0 -}}

- platform: template
  sensors:
    motion_schedule_wake_undetected:
      friendly_name: 'Wake not detected'
      icon_template: >-
        {%- if is_state('automation.motion_schedule_wake_undetected_notify','on') -%}
          {%- if state_attr('automation.motion_schedule_wake_undetected_notify','current')|int > 0 -%}
             {{- 'mdi:check-outline' -}}
          {%- else -%}{{- 'mdi:check-bold' -}}{%- endif -%}
        {%- else -%}{{- 'mdi:alarm-off' -}}{%- endif -%}
      value_template: >-
        {%- set e = state_attr('automation.motion_schedule_wake_undetected_notify','current') -%}
        {{- e|lower != 'none' and e|lower != 'unavailable' and e|lower != 'unknown' and e != null and e|int > 0 -}}
