###
## motion/binary_sensor/alpr.yaml
###

## alpr
- platform: template
  sensors:
    motion_alpr:
      friendly_name: ALPR success
      value_template: >
        {% set e = state_attr('sensor.motion_event_alpr','event') %}
        {% if e is mapping %}
          {{ e.images|length > 0 }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_alpr_expired:
      value_template: >-
        {{ states('sensor.motion_alpr_ago')|int > states('input_number.motion_alpr_ago')|int }}
