###
## motion/binary_sensor/alpr.yaml
###

## alpr
- platform: template
  sensors:
    motion_alpr:
      friendly_name: Faces
      entity_id:
        - sensor.motion_event_alpr
      value_template: >
        {{ states('sensor.motion_event_alpr')|lower == 'true' }}

- platform: template
  sensors:
    motion_alpr_expired:
      entity_id:
        - sensor.motion_alpr_ago
        - input_number.motion_alpr_ago
      value_template: >-
        {{ states('sensor.motion_alpr_ago')|int > states('input_number.motion_alpr_ago')|int }}
