###
## motion/binary_sensor/annotated.yaml
###

## annotated
- platform: template
  sensors:
    motion_annotated:
      friendly_name: Annotated
      value_template: >
        {% set e = state_attr('sensor.motion_event_annotated','count') %}
        {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
          {{ e|int >= 0 }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_annotated_expired:
      value_template: >-
        {{ states('sensor.motion_annotated_ago')|int > states('input_number.motion_annotated_ago')|int }}
