- platform: template
  sensors:
    motion_status_camera:
      friendly_name: Status Cameras
      entity_id:
        - group.motion_status_camera
      value_template: >-
        {{ states('group.motion_status_camera') }}
