###
## motion/binary_sensor/detected.yaml
###

## detected entity
- platform: template
  sensors:
    motion_detected:
      entity_id:
        - counter.motion_annotated_counter
      friendly_name: Detected
      value_template: >-
        {% set detected = state_attr('sensor.motion_event_annotated','detected') %}
        {% if detected is not none and detected|lower != 'unknown' and detected != 'null' %}
          {% set count = detected|map(attribute='count')|sum %}
          {% if count is not none and count|lower != 'unknown' and count != 'null' %}
            {{ count|int > 0 }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_expired:
      entity_id:
        - sensor.motion_detected_ago
        - input_number.motion_detected_ago
      value_template: >-
        {{ states('sensor.motion_detected_ago')|int > states('input_number.motion_detected_ago')|int }}
