###
## motion/binary_sensor/detected.yaml
###

## detected
- platform: template
  sensors:
    motion_detected:
      entity_id:
        - sensor.motion_event_annotated
      friendly_name: Detected
      value_template: >-
        {{ is_state('binary_sensor.motion_annotated','on') and state_attr('sensor.motion_event_annotated','count')|int > 0 }}

- platform: template
  sensors:
    motion_detected_expired:
      entity_id:
        - sensor.motion_detected_ago
        - input_number.motion_detected_ago
      value_template: >-
        {{ states('sensor.motion_detected_ago')|int > states('input_number.motion_detected_ago')|int }}
