###
## motion/binary_sensor/detected_entity.yaml
###

## detected entity
- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - sensor.motion_event_annotated
      friendly_name: Detected entity
      value_template: >-
        {% if is_state('binary_sensor.motion_annotated','on') %}
          {% set detected = state_attr('sensor.motion_event_annotated','detected') %}
          {% if detected is not none and detected|lower != 'unknown' and detected != 'null' %}
            {% set count = detected|selectattr('entity','==',states('sensor.motion_detect_entity'))|map(attribute='count')|sum %}
            {% if count is not none and count|lower != 'unknown' and count != 'null' %}
              {{ count|int > 0 }}
            {% else %}false{% endif %}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_entity_expired:
      entity_id:
        - sensor.motion_detected_entity_ago
        - input_number.motion_detected_entity_ago
      value_template: >-
        {{ states('sensor.motion_detected_entity_ago')|int > states('input_number.motion_detected_entity_ago')|int }}

###
### class detection
###

- platform: template
  sensors:
    motion_detected_person:
      friendly_name: Detected person
      entity_id:
        - sensor.motion_detected_person
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none'
              and states.sensor.motion_detected_person.state|lower != 'unknown'
              and states.sensor.motion_detected_person.state|lower != 'none'
              and states.sensor.motion_detected_person.state|from_json != 'null'
              and states.sensor.motion_detected_person.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle:
      friendly_name: Detected vehicle
      entity_id:
        - sensor.motion_detected_vehicle
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none'
              and states.sensor.motion_detected_vehicle.state|lower != 'none'
              and states.sensor.motion_detected_vehicle.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal:
      friendly_name: Detected animal
      entity_id:
        - sensor.motion_detected_animal
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none' 
              and states.sensor.motion_detected_animal.state|lower != 'none'
              and states.sensor.motion_detected_animal.state|lower != 'unknown'
              and states.sensor.motion_detected_animal.state|from_json != 'null' 
              and states.sensor.motion_detected_animal.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
