###
# homeassistant/binary_sensor/motion/detected_person.yaml
###

- platform: template
  sensors:
    motion_detected_person:
      friendly_name: Person detected
      icon_template: 'mdi:account-circle'
      value_template: >-
        {% set s = states('sensor.motion_detected_person') %}
        {% if s|lower != 'unknown' and s|lower != 'none' %}
          {% set s = s|from_json %}
          {% if s|lower != 'unknown' and s|lower != 'none' and s is iterable %}
            {{ s|sum|int > 0 }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_person_expired:
      friendly_name: Person detected expired
      icon_template: 'mdi:account-circle-outline'
      device_class: occupancy
      value_template: >-
        {{ states('sensor.motion_detected_person_ago')|int > states('input_number.motion_detected_entity_ago')|int }}
