###
## motion/binary_sensor/detected.yaml
###

## detected entity
- platform: template
  sensors:
    motion_detected:
      friendly_name: Detected
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {{ states('sensor.motion_event_annotated')|lower == 'true' and state_attr('sensor.motion_event_annotated','count')|int > 0 }}

- platform: template
  sensors:
    motion_detected_expired:
      entity_id:
        - sensor.motion_detected_ago
        - input_number.motion_detected_ago
      value_template: >-
        {{ states('sensor.motion_detected_ago')|int > states('input_number.motion_detected_ago')|int }}
