###
# homeassistant/binary_sensor/motion/detected_vehicle.yaml
###

- platform: template
  sensors:
    motion_detected_vehicle:
      friendly_name: Vehicle detected
      icon_template: 'mdi:car'
      value_template: >-
        {% set s = states('sensor.motion_detected_vehicle') %}
        {% if s|lower != 'unknown' and s|lower != 'none' %}
          {% set s = s|from_json %}
          {% if s|lower != 'unknown' and s|lower != 'none' and s is iterable %}
            {{ s|sum|int > 0 }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_vehicle_detected:
      friendly_name: Detected vehicle
      icon_template: 'mdi:car'
      value_template: >-
        {% set results = state_attr('sensor.motion_event_annotated','results') %}
        {% if results is not none and results|lower != 'unavailable' and results|lower != 'unknown' and results|length > 0 %}
          {% set confidence = results|selectattr('entity','==','vehicle')|map(attribute='confidence')|max %}
            {{ confidence|int >= states('input_number.motion_vehicle_detected_percent')|int }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_expired:
      friendly_name: Vehicle detected expired
      icon_template: 'mdi:car'
      device_class: occupancy
      value_template: >-
        {{ states('sensor.motion_detected_vehicle_ago')|int > states('input_number.motion_detected_vehicle_ago')|int }}
