###
# homeassistant/binary_sensor/motion/detected_animal.yaml
###

- platform: template
  sensors:
    motion_detected_animal:
      friendly_name: Animal detected
      icon_template: 'mdi:cow'
      value_template: >-
        {% set s = states('sensor.motion_detected_animal') %}
        {% if s|lower != 'unknown' and s|lower != 'none' %}
          {% set s = s|from_json %}
          {% if s|lower != 'unknown' and s|lower != 'none' and s is iterable %}
            {{ s|sum|int > 0 }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_animal_expired:
      friendly_name: Animal detected expired
      icon_template: 'mdi:motion-sensor-off'
      device_class: occupancy
      value_template: >-
        {{ states('sensor.motion_detected_animal_ago')|int > states('input_number.motion_detected_entity_ago')|int }}
