###
## motion/binary_sensor/detected_entity.yaml
###

## detected entity
- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - counter.motion_annotated_counter
      friendly_name: Detected entity
      value_template: >-
        {% set detected = state_attr('sensor.motion_event_annotated','detected') %}
        {% if detected is not none and detected|lower != 'unknown' and detected != 'null' %}
          {% set count = detected|selectattr('entity','==',states('sensor.motion_detect_entity'))|map(attribute='count')|sum %}
          {% if count is not none and count|lower != 'unknown' and count != 'null' %}
            {{ count|int > 0 }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_detected_entity_expired:
      entity_id:
        - sensor.motion_detected_entity_ago
        - input_number.motion_detected_entity_ago
      value_template: >-
        {{ states('sensor.motion_detected_entity_ago')|int > states('input_number.motion_detected_entity_ago')|int }}
