###
## motion/binary_sensor/end.yaml
###

- platform: template
  sensors:
    motion_end:
      value_template: >
        {% set e = state_attr('sensor.motion_event_annotated','event') %}
        {% if e is not none and e|lower != 'unavailable' and e|lower != 'unknown' and e != 'null' %}
          {{ e.images|length > 0 }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_end_expired:
      value_template: >
        {{ states('sensor.motion_end_ago')|int > states('input_number.motion_end_ago')|int }}
