###
## motion/binary_sensor/end.yaml
###

- platform: template
  sensors:
    motion_end:
      entity_id:
        - sensor.motion_event_end
      value_template: >
        {{ states('sensor.motion_event_end')|lower == 'true' }}

- platform: template
  sensors:
    motion_end_expired:
      entity_id:
        - sensor.motion_end_ago
      value_template: >
        {{ states('sensor.motion_end_ago')|int > states('input_number.motion_end_ago')|int }}
