###
## motion/binary_sensor/face.yaml
###

## face
- platform: template
  sensors:
    motion_face:
      friendly_name: Faces
      value_template: >
        {% set e = state_attr('sensor.motion_event_face','event') %}
        {% if e is mapping %}
          {{ e.images|length > 0 }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_face_expired:
      value_template: >-
        {{ states('sensor.motion_face_ago')|int > states('input_number.motion_face_ago')|int }}
