###
## motion/binary_sensor/face.yaml
###

## face
- platform: template
  sensors:
    motion_face:
      friendly_name: Faces
      entity_id:
        - sensor.motion_event_face
      value_template: >
        {{ states('sensor.motion_event_face')|lower == 'true' }}

- platform: template
  sensors:
    motion_face_expired:
      entity_id:
        - sensor.motion_face_ago
        - input_number.motion_face_ago
      value_template: >-
        {{ states('sensor.motion_face_ago')|int > states('input_number.motion_face_ago')|int }}
