###
## motion/binary_sensor/face_detected.yaml
###

## face_detected
- platform: template
  sensors:
    motion_face_detected:
      entity_id:
        - sensor.motion_event_face
      friendly_name: Detected
      value_template: >-
        {% set count = state_attr('sensor.motion_event_face','count') %}
        {% set percents = state_attr('sensor.motion_event_face','detected') %}
        {% if count is not none and percents is not none and count != 'null' and percents|length > 0 %}
          {{ is_state('binary_sensor.motion_face','on') and count|int > 0 and percents|max|int >= states('input_number.motion_face_detected_percent')|int }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_face_detected_expired:
      entity_id:
        - sensor.motion_face_detected_ago
        - input_number.motion_face_detected_ago
      value_template: >-
        {{ states('sensor.motion_face_detected_ago')|int > states('input_number.motion_face_detected_ago')|int }}
