###
# homeassistant/binary_sensor/motion/mqtt.yaml
###

- platform: template
  sensors:
    motion_status_mqtt:
      friendly_name: MQTT status
      device_class: connectivity
      value_template: >-
        {{
          is_state('binary_sensor.motion_status_mqtt_active','on') and
          is_state('binary_sensor.motion_status_mqtt_broker','on') and
          is_state('binary_sensor.motion_status_mqtt_port','on') 
        }}
    motion_status_mqtt_active:
      friendly_name: MQTT active
      device_class: connectivity
      value_template: >-
        {% set m = states('sensor.motion_mqtt_load_messages_received_1min') %}
        {% if m|lower != 'none' and m|lower != 'unknown' and m|lower != 'unavailable' and m|lower != 'null' %}
          {{ m|int > 0 }}
        {% else %}null{% endif %}
    motion_status_mqtt_broker:
      friendly_name: All connected
      device_class: connectivity
      value_template: >-
        {% set it = states('input_text.motion_mqtt_broker') %}
        {% set yolo = states('sensor.motion_yolo_test_mqtt_broker') %}
        {% set ha = states('sensor.motion_mqtt_broker') %}
        {% set addon = states('sensor.motion_addon_config_mqtt_broker') %}
        {% if it|lower != 'none' and it|lower != 'unknown' and it|lower != 'unavailable' and it|lower != 'null' %}
          {{ it|lower == yolo|lower and
             it|lower == ha|lower and
             it|lower == addon|lower }}
        {% else %}null{% endif %}
    motion_status_mqtt_port:
      friendly_name: All connected
      device_class: connectivity
      value_template: >-
        {% set it = states('input_text.motion_mqtt_port') %}
        {% set yolo = states('sensor.motion_yolo_test_mqtt_port') %}
        {% set ha = states('sensor.motion_mqtt_port') %}
        {% set addon = states('sensor.motion_addon_config_mqtt_port') %}
        {% if it|lower != 'none' and it|lower != 'unknown' and it|lower != 'unavailable' and it|lower != 'null' %}
          {{ it|lower == yolo|lower and
             it|lower == ha|lower and
             it|lower == addon|lower }}
        {% else %}null{% endif %}
