- platform: template
  sensors:
    motion_person_face:
      icon_template: 'mdi:account-check'
      friendly_name: Person w/ FACE
      value_template: >-
        {% set pc = states('sensor.motion_detected_person_camera') %}
        {% set fc = states('sensor.motion_face_detected_camera') %}
        {% set pd = states('sensor.motion_detected_person_device') %}
        {% set fd = states('sensor.motion_face_detected_device') %}
        {% set pe = states('sensor.motion_detected_person_event') %}
        {% set fe = states('sensor.motion_face_detected_event') %}
        {{ 
           pc != null and pc|lower != 'unavailable' and pc|lower != 'none' and pc|lower != 'unknown' and
           fc != null and fc|lower != 'unavailable' and fc|lower != 'none' and fc|lower != 'unknown' and
           pd != null and pd|lower != 'unavailable' and pd|lower != 'none' and pd|lower != 'unknown' and
           fd != null and fd|lower != 'unavailable' and fd|lower != 'none' and fd|lower != 'unknown' and
           pe != null and pe|lower != 'unavailable' and pe|lower != 'none' and pe|lower != 'unknown' and
           fe != null and fe|lower != 'unavailable' and fe|lower != 'none' and fe|lower != 'unknown' and
           pc == fc and pd == fd and pe == fe
        }}

- platform: template
  sensors:
    motion_person_face_expired:
      friendly_name: Person w/ FACE expired
      value_template: >-
        {{ states('sensor.motion_person_face_ago')|int > states('input_number.motion_face_detected_ago')|int or
           states('sensor.motion_person_face_ago')|int > states('input_number.motion_detected_person_ago')|int }}
