- platform: template
  sensors:
    motion_person_face:
      icon_template: 'mdi:account-check'
      friendly_name: Person w/ FACE
      value_template: >-
        {% set pc = states('sensor.motion_detected_person_camera') %}
        {% set fc = states('sensor.motion_face_detected_camera') %}
        {% set pd = states('sensor.motion_detected_person_device') %}
        {% set fd = states('sensor.motion_face_detected_device') %}
        {% set pe = states('sensor.motion_detected_person_event') %}
        {% set fe = states('sensor.motion_face_detected_event') %}
        {{ 
           pc|lower != 'null' and pc|lower != 'unavailable' and pc|lower != 'none' and pc|lower != 'unknown' and
           fc|lower != 'null' and fc|lower != 'unavailable' and fc|lower != 'none' and fc|lower != 'unknown' and
           pd|lower != 'null' and pd|lower != 'unavailable' and pd|lower != 'none' and pd|lower != 'unknown' and
           fd|lower != 'null' and fd|lower != 'unavailable' and fd|lower != 'none' and fd|lower != 'unknown' and
           pe|lower != 'null' and pe|lower != 'unavailable' and pe|lower != 'none' and pe|lower != 'unknown' and
           fe|lower != 'null' and fe|lower != 'unavailable' and fe|lower != 'none' and fe|lower != 'unknown' and
           pc == fc and pd == fd and pe == fe
           and is_state('binary_sensor.motion_detected_person','on')
           and is_state('binary_sensor.motion_face_detected','on')
        }}

- platform: template
  sensors:
    motion_person_face_expired:
      friendly_name: Person w/ FACE expired
      value_template: >-
        {{ states('sensor.motion_person_face_ago')|int > states('input_number.motion_face_detected_ago')|int or
           states('sensor.motion_person_face_ago')|int > states('input_number.motion_detected_person_ago')|int }}
