- platform: template
  sensors:
    motion_person_face:
      friendly_name: Person w/ face
      entity_id:
        - counter.motion_detected_person_counter
        - counter.motion_face_detected_counter
      value_template: >-
        {% set ea = state_attr('sensor.motion_event_annotated','event') %}
        {% set ef = state_attr('sensor.motion_event_face','event') %}
        {% if ea is not none and ea|lower != 'none' and ea|lower != 'unavailable' and ea != 'null' 
             and ef is not none and ef|lower != 'none' and ef|lower != 'unavailable' and ef != 'null' %}
          {{ ea.event == ef.event and ea.group == ef.group and ea.device == ef.device and ea.camera == ef.camera }}
        {% else %}false{% endif %}
