- platform: template
  sensors:
    motion_vehicle_alpr:
      friendly_name: Vehicle w/ ALPR
      value_template: >-
        {% set ea = state_attr('sensor.motion_event_annotated','event') %}
        {% set ef = state_attr('sensor.motion_event_alpr','event') %}
        {% if ea is not none and ea|lower != 'none' and ea|lower != 'unavailable' and ea != 'null' 
             and ef is not none and ef|lower != 'none' and ef|lower != 'unavailable' and ef != 'null' %}
          {{ ea.event == ef.event and ea.group == ef.group and ea.device == ef.device and ea.camera == ef.camera 
             and states('binary_sensor.motion_detected_vehicle') == 'on'
             and states('binary_sensor.motion_alpr_detected') == 'on'
           }}
        {% else %}false{% endif %}
