- platform: template
  sensors:
    motion_vehicle_alpr:
      icon_template: 'mdi:car-info'
      friendly_name: Vehicle w/ ALPR 
      value_template: >-
        {% set da = states('sensor.motion_vehicle_camera') %}
        {% set df = states('sensor.motion_alpr_detected_camera') %}
        {% set ca = states('sensor.motion_vehicle_camera') %}
        {% set cf = states('sensor.motion_alpr_detected_camera') %}
        {% set ea = states('sensor.motion_vehicle_event') %}
        {% set ef = states('sensor.motion_alpr_detected_event') %}
        {{ 
           ea != null and ef != null and ea|lower != 'unavailable' and ef|lower != 'unavailable' and ea|lower != 'none' and ef|lower != 'none' and ea|lower != 'unknown' and ef|lower != 'unknown' 
           and 
           ca != null and cf != null and ca|lower != 'unavailable' and cf|lower != 'unavailable' and ca|lower != 'none' and cf|lower != 'none' and ca|lower != 'unknown' and cf|lower != 'unknown'
          and 
          da != null and df != null and da|lower != 'unavailable' and df|lower != 'unavailable' and da|lower != 'none' and df|lower != 'none' and da|lower != 'unknown' and df|lower != 'unknown'
          and ea == ef and da == df and ca == cf
        }}
