###
# motion/binary_sensor/webcams.yaml
###

- platform: template
  sensors:
    motion_detected_entity_webcams:
      entity_id:
        - group.motion_detected_entity
      value_template: >
        {{ is_state('group.motion_detected_entity','on') }}

- platform: template
  sensors:
    motion_detected_webcams:
      entity_id:
        - group.motion_detected
      value_template: >
        {{ is_state('group.motion_detected','on') }}

- platform: template
  sensors:
    motion_annotated_webcams:
      entity_id:
        - group.motion_annotated
      value_template: >
        {{ is_state('group.motion_annotated','on') }}

- platform: template
  sensors:
    motion_end_webcams:
      entity_id:
        - group.motion_end
      value_template: >
        {{ is_state('group.motion_end','on') }}

- platform: template
  sensors:
    motion_face_webcams:
      entity_id:
        - group.motion_face
      value_template: >
        {{ is_state('group.motion_face','on') }}

- platform: template
  sensors:
    motion_face_detected_webcams:
      entity_id:
        - group.motion_face_detected
      value_template: >
        {{ is_state('group.motion_face_detected','on') }}
