###
## camera/motion/annotated_picture.yaml
###

- platform: generic
  name: motion_annotated_picture
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture') %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_testsignal_picture') }}
    {% endif %}
