###
## motion/camera/detected_animal.yaml
###

- platform: local_file
  name: motion_detected_animal
  friendly_name: Animal detected
  file_path: /config/www/images/motion_detected_animal.jpg

- platform: local_file
  name: motion_detected_animal_animated
  friendly_name: Animal animated
  file_path: /config/www/images/motion_detected_animal.gif

- platform: local_file
  name: motion_detected_animal_animated_mask
  friendly_name: Animal animated mask
  file_path: /config/www/images/motion_detected_animal_mask.gif

- platform: generic
  name: motion_camera_detected_animal_live
  friendly_name: Animal animated live
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_detected_animal_live') }}
