###
## motion/camera/detected_vehicle.yaml
###

- platform: local_file
  name: motion_detected_vehicle
  friendly_name: Vehicle detected
  file_path: /config/www/images/motion_detected_vehicle.jpg

- platform: local_file
  name: motion_detected_vehicle_animated
  friendly_name: Vehicle animated
  file_path: /config/www/images/motion_detected_vehicle.gif

- platform: local_file
  name: motion_detected_vehicle_animated_mask
  file_path: /config/www/images/motion_detected_vehicle_mask.gif

- platform: generic
  name: motion_camera_detected_vehicle_live
  friendly_name: Vehicle mask
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_detected_vehicle_live') }}
