###
## motion/camera/detected_person.yaml
###

#- platform: generic
#  name: motion_detected_person_picture
#  verify_ssl: false
#  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
#  still_image_url: >-
#    {% if states('input_boolean.motion_snapshot') == 'on' %}
#      {% set p = states('sensor.motion_detected_person_snapshot') %}
#    {% else %}
#      {% set p = states('sensor.motion_detected_person_picture') %}
#    {% endif %}
#    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
#      {{ p }}
#    {% else %}
#      {{ states('sensor.motion_testsignal_picture') }}
#    {% endif %}

#- platform: generic
#  name: motion_detected_person_snapshot
#  verify_ssl: false
#  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
#  still_image_url: >-
#    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
#      {% set p = states('sensor.motion_detected_person_snapshot') %}
#    {% else %}
#      {% set p = states('sensor.motion_nosignal_picture') %}
#    {% endif %}
#    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
#      {{ p }}
#    {% else %}
#      {{ states('sensor.motion_testsignal_picture') }}
#    {% endif %}

#- platform: generic
#  name: motion_detected_person_animated
#  verify_ssl: false
#  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
#  still_image_url: >-
#    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
#      {% set p = states('sensor.motion_detected_person_animated') %}
#    {% else %}
#      {% set p = states('sensor.motion_detected_person_animated') %}
#    {% endif %}
#    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
#      {{ p }}
#    {% else %}
#      {{ states('sensor.motion_testsignal_picture') }}
#    {% endif %}

- platform: local_file
  name: motion_detected_person
  file_path: /config/www/images/motion_detected_person.jpg

- platform: local_file
  name: motion_detected_person_animated
  file_path: /config/www/images/motion_detected_person.gif

- platform: generic
  name: motion_camera_detected_person_live
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_detected_person_live') }}
