###
## motion/camera/detected.yaml
###

- platform: generic
  name: motion_detected_picture
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture') %}
    {% endif %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_testsignal_picture') }}
    {% endif %}

- platform: generic
  name: motion_detected_snapshot
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot') %}
    {% else %}
      {% set p = states('sensor.motion_nosignal_picture') %}
    {% endif %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_testsignal_picture') }}
    {% endif %}

- platform: generic
  name: motion_detected_animated
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
      {% set p = states('sensor.motion_detected_animated') %}
    {% else %}
      {% set p = states('sensor.motion_detected_animated') %}
    {% endif %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_testsignal_picture') }}
    {% endif %}
