###
## camera/motion/end_snapshot.yaml
###

- platform: generic
  name: motion_end_snapshot
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot') %}
    {% endif %}
    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}
      {{ states('sensor.motion_testsignal_picture') }}
    {% endif %}
