###
## motion/camera/face_detected.yaml
###

#- platform: generic
#  name: motion_face_detected_picture
#  verify_ssl: false
#  limit_refetch_to_url_change: false
#  still_image_url: >-
#    {% if states('input_boolean.motion_snapshot') == 'on' %}
#      {% set p = states('sensor.motion_face_detected_snapshot') %}
#    {% else %}
#      {% set p = states('sensor.motion_face_detected_picture') %}
#    {% endif %}
#    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
#      {{ p }}
#    {% else %}
#      {{ states('sensor.motion_testsignal_picture') }}
#    {% endif %}

#- platform: generic
#  name: motion_face_detected_snapshot
#  verify_ssl: false
#  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
#  still_image_url: >-
#    {% if states('input_boolean.motion_snapshot_save') == 'on' %}
#      {% set p = states('sensor.motion_face_detected_snapshot') %}
#    {% else %}
#      {% set p = states('sensor.motion_testsignal_picture') %}
#    {% endif %}
#    {% if p is defined and p is not none and p|lower != 'unknown' and p != 'null' and p|length > 0 %}
#      {{ p }}
#    {% else %}
#      {{ states('sensor.motion_testsignal_picture') }}
#    {% endif %}

- platform: local_file
  name: motion_face_detected
  file_path: /config/www/images/motion_face_detected.jpg

- platform: local_file
  name: motion_face_detected_animated
  file_path: /config/www/images/motion_face_detected.gif

- platform: generic
  name: motion_camera_face_detected_live
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_face_detected_live') }}
