###
## homeassistant/camera/motion/selected.yaml
###

## live
- platform: generic
  name: motion_camera_selected_live
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {% set c = states('sensor.motion_camera_selected_live') %}
    {% if c is not none and c|lower != 'unknown' and c|length > 0 %}
      {{ c }}
    {% else %}
      {{ states('sensor.motion_noisesignal_animated') }}
    {% endif %}

## annotated
- platform: generic
  name: motion_camera_selected_annotated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_annotated') }}

- platform: generic
  name: motion_camera_selected_annotated_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_annotated_animated') }}

## detected
- platform: generic
  name: motion_camera_selected_detected
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected') }}

- platform: generic
  name: motion_camera_selected_detected_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_animated') }}

- platform: generic
  name: motion_camera_selected_detected_composite
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_composite') }}

## detected_entity
- platform: generic
  name: motion_camera_selected_detected_entity
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_entity') }}

- platform: generic
  name: motion_camera_selected_detected_entity_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_entity_animated') }}
 
- platform: generic
  name: motion_camera_selected_detected_entity_composite
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_entity_composite') }}
 
## detected_person
- platform: generic
  name: motion_camera_selected_detected_person
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_person') }}

- platform: generic
  name: motion_camera_selected_detected_person_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_person_animated') }}
 
- platform: generic
  name: motion_camera_selected_detected_person_composite
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_person_composite') }}
 
## detected_vehicle
- platform: generic
  name: motion_camera_selected_detected_vehicle
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_vehicle') }}

- platform: generic
  name: motion_camera_selected_detected_vehicle_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_vehicle_animated') }}
 
- platform: generic
  name: motion_camera_selected_detected_vehicle_composite
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_vehicle_composite') }}
 
## detected_animal
- platform: generic
  name: motion_camera_selected_detected_animal
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_animal') }}

- platform: generic
  name: motion_camera_selected_detected_animal_animated
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_animal_animated') }}

- platform: generic
  name: motion_camera_selected_detected_animal_composite
  verify_ssl: false
  limit_refetch_to_url_change: !secret limit-refetch-to-url-change
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_animal_composite') }}
