###
## homeassistant/camera/motion/selected.yaml
###

## live
- platform: generic
  name: motion_camera_selected_live
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {% set c = states('sensor.motion_camera_selected_live') %}
    {% if c is not none and c|lower != 'unknown' and c|length > 0 %}
      {{ c }}
    {% else %}
      {{ states('sensor.motion_noisesignal_animated') }}
    {% endif %}

## annotated
- platform: generic
  name: motion_camera_selected_annotated
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_annotated') }}

- platform: generic
  name: motion_camera_selected_animated_annotated
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_animated_annotated') }}

## detected
- platform: generic
  name: motion_camera_selected_detected
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected') }}

- platform: generic
  name: motion_camera_selected_animated_detected
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_animated_detected') }}

## detected_entity
- platform: generic
  name: motion_camera_selected_detected_entity
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_detected_entity') }}

- platform: generic
  name: motion_camera_selected_animated_detected_entity
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected_animated_detected_entity') }}
