###
## homeassistant/camera/motion/selected.yaml
###

- platform: generic
  name: motion_camera_selected
  verify_ssl: false
  limit_refetch_to_url_change: false
  still_image_url: >-
    {{ states('sensor.motion_camera_selected') }}
